---
jupyter: python3
---

```{python}
import os
import sys
```

```{python}
os.environ["R_HOME"] = "/Library/Frameworks/R.framework/Resources"
# r_home = "/Library/Frameworks/R.framework/Resources"
```
```{python}

# os.environ["r_home"] = "/Library/Frameworks/R.framework/Resources"

import rpy2.robjects as robjects
from rpy2.robjects import r, vectors
from rpy2 import rinterface

import pandas as pd
import numpy as np
import seaborn as sns
import itertools

from rpy2.robjects import pandas2ri, default_converter, conversion

import torch
from torch.utils.data import TensorDataset
from torchvision import transforms
import pyro
import pyro.distributions as dist
from pyro.optim import Adam, ClippedAdam, AdagradRMSProp
from pyro.infer import SVI, Trace_ELBO, RBFSteinKernel

import importlib

# import sklearn
from sklearn.model_selection import train_test_split


from pathlib import Path
import time
```

```{python}
import matplotlib.pyplot as plt
```

```{python}
#| label: Insert path
sys.path.insert(1, "/Users/jonathanhori/multiomic_integration/python")
```

```{python}
#| label: Load data utils
# importlib.reload(sys.modules["data_utils"])

# from data_utils import floatmatrix_to_torch, r_to_torch, load_and_process_rds_data_for_condition, normalize_tensor_by_col, extract_est_decomp, extract_sim_decomp, calc_struct, scale_est_struct, scale_sim_struct, eval_rse, eval_mse, summarise_post_samples, summarise_structure_list, eval_post_coverage, eval_credible_interval, obtain_posterior_pred_samples, calc_all_structures_with_rescaling, eval_performance, zero_variance_col_filter
from data_utils import r_to_torch, normalize_tensor_by_col, \
    zero_variance_col_filter, obtain_posterior_pred_samples, \
        calc_all_structures_with_rescaling, extract_sim_decomp, eval_performance, varimax
```

```{python}
#| label: Load model objects
# importlib.reload(sys.modules["model"])
# importlib.reload(sys.modules["handler"])

# from matrix_decomp import FactorModelARD, do_inference
from model import SupMultiviewDecomp
from handler import ModelHandler
```

```{python}
# importlib.reload(sys.modules["constants"])
from constants import Params, Sites
```

# Load data

## Load multiview data

```{python}
# conversion.set_conversion(default_converter)
# readRDS = robjects.r['readRDS']
# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/n500p100_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/n50p50_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/n500p1000_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
# n50p50_snr2.2_sparse0_rep1
```

```{python}
conversion.set_conversion(default_converter)
readRDS = robjects.r['readRDS']
# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data/n50p50_snr2.2_sparse0.5/sim_data_ywithview_rep1.rds')


# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data/n500p100_snr2.2_sparse0.25/sim_data_ywithview_rep1.rds')

# sim_data_multiview = readRDS('~/multiomic_integration/sim/data/test_sim_data_n1000p1000_snr2.2_ywithview.rds')
sim_data_multiview = readRDS('~/multiomic_integration/sim/data_ortho/train/n500p100_snr2.2_sparse0.25/sim_data_ywithview_rep1.rds')


# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/n50p50_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
# sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/n500p1000_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
# n50p50_snr2.2_sparse0_rep1
```


```{python}
conversion.set_conversion(default_converter)

sim_data_multiview_torch = {name: r_to_torch(sim_data_multiview.rx2(name)) for name in sim_data_multiview.names}

sim_data_multiview_torch
```


```{python}
sns.heatmap(
sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)
```



## Extract and clean
```{python}
#| label: Extract features to use


X_l_list = sim_data_multiview_torch.get("X_l")
X_l_list

y = sim_data_multiview_torch.get("y")
y

k = sim_data_multiview_torch.get("K")
k_l_list = sim_data_multiview_torch.get("K_l")

n = X_l_list[0].shape[0]
```

Process without train/test split
```{python}
X_l_list_column_filters = [zero_variance_col_filter(X) for X in X_l_list]
X_l_list = [X[:, col_filter] for X, col_filter in zip(X_l_list, X_l_list_column_filters)]

clean_X_dict_list = list(map(normalize_tensor_by_col, X_l_list))

X_l_list_clean = [clean["data_clean"] for clean in clean_X_dict_list]

X_l_mean_list = [clean["means"] for clean in clean_X_dict_list]
X_l_sd_list = [clean["sds"] for clean in clean_X_dict_list]

y_mean = torch.mean(y)
y_std = torch.std(y)
y_clean = (y - y_mean) / y_std
```

```{python}
train_subset = TensorDataset(torch.arange(train_X_l_list[0].shape[0]), 
                                         *train_X_l_list, 
                                         train_y_clean)
```

With train/test split

```{python}
TRAINING_SPLIT = False

TRAINING_SIZE = 0.8
RANDOM_SEED = 123
# Perform train/test split if necessary
if TRAINING_SPLIT:
    train_idx, test_idx = train_test_split(
        torch.arange(X_l_list[0].shape[0]),
        train_size = TRAINING_SIZE,
        random_state = RANDOM_SEED,
        shuffle = True
    )
    train_X_l_list = [X[train_idx, :] for X in X_l_list]
    test_X_l_list = [X[test_idx, :] for X in X_l_list]
    
    train_y = y[train_idx]
    test_y = y[test_idx]
else:
    train_idx = torch.arange(n)
    test_idx = torch.arange(n)
    
    train_X_l_list = X_l_list
    test_X_l_list = train_X_l_list
    
    train_y = y
    test_y = train_y

# Clean: remove 0 variance columns and standardize. Using Training data            
X_l_list_column_filters = [zero_variance_col_filter(X) for X in train_X_l_list]

train_X_l_list = [X[:, col_filter] for X, col_filter in zip(train_X_l_list, X_l_list_column_filters)]
test_X_l_list = [X[:, col_filter] for X, col_filter in zip(test_X_l_list, X_l_list_column_filters)]

clean_train_X_dict_list = [normalize_tensor_by_col(X) for X in train_X_l_list]
X_l_mean_list = [clean["means"] for clean in clean_train_X_dict_list]
X_l_sd_list = [clean["sds"] for clean in clean_train_X_dict_list]

clean_test_X_dict_list = [normalize_tensor_by_col(X, means, stds) 
                            for X, means, stds in 
                            zip(test_X_l_list, X_l_mean_list, X_l_sd_list)]

train_X_l_list_clean = [clean["data_clean"] for clean in clean_train_X_dict_list]
test_X_l_list_clean = [clean["data_clean"] for clean in clean_test_X_dict_list]

y_mean = torch.mean(train_y)
y_std = torch.std(train_y)

train_y_clean = (train_y - y_mean) / y_std
test_y_clean = (test_y - y_mean) / y_std
```

```{python}
train_subset = TensorDataset(torch.arange(train_X_l_list_clean[0].shape[0]), 
                                         *train_X_l_list_clean, 
                                         train_y_clean)
test_subset = TensorDataset(torch.arange(test_X_l_list_clean[0].shape[0]), 
                                         *test_X_l_list_clean, 
                                         test_y_clean)
```


DEBUG. Check: is orthogonality preserved after splitting into train/test sets?

```{python}
[torch.norm(Phi[train_idx, :].T @ sim_data_multiview_torch['Z'][train_idx, :]) for Phi in sim_data_multiview_torch['Phi_perp']]
```

```{python}
[torch.norm(Phi.T @ sim_data_multiview_torch['Z']) for Phi in sim_data_multiview_torch['Phi_perp']]
```

Single tensor data


```{python}
clean_data_dict = normalize_tensor_by_col(X)
# X_clean = clean_data_dict.get("data_clean")
# X_means = clean_data_dict.get("means")
# X_stds = clean_data_dict.get("sds")
# torch.mean(X_clean, 0)

```




# Load data into model

```{python}
import importlib
```




```{python}
sim_data_torch["X_l"][0]
```

```{python}
X_l_tensor = torch.utils.data.TensorDataset(sim_data_torch["X_l"][0])
loader = torch.utils.data.DataLoader(X_l_tensor, batch_size = len(X_l_tensor))
one_batch, = next(iter(loader))
one_batch.shape
```

# Visualize model structure

### SupMultiviewDecomp
```{python}
factor_model = SupMultiviewDecomp(int(k), k_l_list.int().tolist(), n, dense = False)

pyro.render_model(
    factor_model, #bayesian_factor_model, 
    model_args = (X_l_list,
                  torch.arange(X_l_list[0].shape[0]),
                  y
    ),
    render_distributions=True, 
    render_params=True,
    render_deterministic = True)
```

# Run model

## Run model: with minibatching

SupMultiviewDecomp



Check trace for data dimensions

```{python}

trace = pyro.poutine.trace(
    SupMultiviewDecomp(
        int(k),
        k_l_list.int().tolist(),
        include_view_factors = True,
        dense = False
    )
    ).get_trace(
        train_X_l_list_clean,
        torch.arange(train_X_l_list_clean[0].shape[0]),
        train_y_clean.squeeze())

trace.compute_log_prob() # optional, but allows printing of log_prob shapes

print(trace.format_shapes())
```


With custom guide.
During training, the model and guide are used. During prediction, save the ParamStore global latent variables and include as prior values in the prediction model and prediction guide. The guide only includes `pyro.param` statements over the local latent variables and only updates these. Run SVI for a certain number of epochs until convergence. Then use 

```{python}
train_subset.__len__()
```

```{python}

pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 500
MIN_EPOCHS = 50
initial_lr = 0.001
gamma = 0.001  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))
OPT = Adam({"lr": initial_lr})
# OPT = AdagradRMSProp({})
# OPT = Adam({"amsgrad": True}) #"lr": initial_lr)
# OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd,, "betas": (0.8, 0.95)}) # (0.9, 0.999) (0.95, 0.999
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10
k_l_upper = [int(k_l) + 10 for k_l in k_l_list.tolist()]

# hyperparam = 5.0
factor_model = SupMultiviewDecomp(
    k_upper,
    k_l_upper,
    ortho_penalty = 0.0,
    include_view_factors = True,
    dense = False
)

train_handler = ModelHandler("train", factor_model, opt = OPT, loss = LOSS)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.1,
    min_epochs = MIN_EPOCHS,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


```{python}
factor_model = SupMultiviewDecomp(
    int(k),
    k_l_list.int().tolist(),
    int(train_X_l_list_clean[0].shape[0]),
    include_view_factors = True,
    dense = False
)
```

```{python}
factor_model.forward(train_X_l_list_clean,
        torch.arange(train_X_l_list_clean[0].shape[0]),
        train_y_clean.squeeze())
```


```{python}
factor_model.predict_forward(train_X_l_list_clean,
        torch.arange(train_X_l_list_clean[0].shape[0]),
        train_y_clean.squeeze())
```

ClippedAdam with learning rate decay.
Start lr = 0.001. Over 1000 epochs 

With autoguide

```{python}

pyro.clear_param_store()

# hyperparam = 5.0
# factor_model = SupMultiviewDecomp(
#     int(k),
#     k_l_list.int().tolist(),
#     int(train_X_l_list_clean[0].shape[0]),
#     include_view_factors = True,
#     dense = False
# )

factor_model = SupMultiviewDecomp(
    k_upper,
    k_l_upper,
    include_view_factors = True,
    dense = False
)

factor_model.n = train_subset.__len__()

def subsample_create_plates(X, batch_idx, y = None):
    # m = len(batch_idx)
    return pyro.plate("obs", factor_model.n, subsample = batch_idx)
# guide = factor_model.guide

guide = pyro.infer.autoguide.AutoNormal(
    factor_model, 
    create_plates = subsample_create_plates)

pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 500
MIN_EPOCHS = 50
initial_lr = 0.001
gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))
OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd, "betas": (0.95, 0.999)}) # (0.9, 0.999)
LOSS = Trace_ELBO(num_particles = 2)

# t0 = time.time()
# svi, opt = do_inference(
#     train_subset,
#     # X_l_list_clean,
#     # y_clean,
#     factor_model,
#     guide,
#     opt = OPT,
#     elbo = LOSS,
#     inference = "svi",
#     tol = 0.5, # tolerance is epoch loss per datum
#     variational_tol = 0.3,
#     min_epochs = 30,
#     epochs = NUM_EPOCHS,
#     minibatch_flag = True,
#     minibatch_size = MINIBATCH_SIZE,
#     verbose = True
#     )

# t1 = time.time()


train_handler = ModelHandler("train", factor_model, guide, OPT, LOSS)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.1,
    min_epochs = MIN_EPOCHS,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


```{python}
# # pyro.set_rng_seed(41)
# pyro.clear_param_store()
# hyperparam = 2.0
# factor_model = SupMultiviewDecomp(
#     int(k),
#     k_l_list.int().tolist(),
#     n,
#     include_view_factors = True,
#     dense = True,
#     a_sigma_joint=hyperparam, # Hyperparams: gamma process prior per factor loadings
#     b_sigma_joint=hyperparam,
#     a_sigma_view=hyperparam, # Hyperparams: gamma process prior per factor loadings
#     b_sigma_view=hyperparam,
#     a_psi=hyperparam, # Hyperparams: per-view error: IG same for all views
#     b_psi=hyperparam
# )

# predictive_prior = pyro.infer.Predictive(factor_model, num_samples=10)
# samples = predictive_prior(X_l_list_clean, torch.arange(n))
```


```{python}
sim_data_multiview_torch['Lambda_l']
# torch.isnan(samples['X_l1'][0]).any()
```

```{python}
samples.keys()
```

```{python}
param_store_curr = pyro.get_param_store()
```

```{python}
{k: v for k, v in param_store_curr.items()
                                         if any(param in k for param in ('loc_Z', 'scale_Z', 'loc_Phi_l', 'scale_Phi_l'))}
```

```{python}
samples['X_l1'][1]
```


Using SVGD

```{python}
factor_model = SupMultiviewDecomp(
    int(k),
    k_l_list.int().tolist(),
    n,
    include_view_factors = True,
    dense = False
)

pyro.clear_param_store()


MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.005 

gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))

OPT = Adam({"lr": initial_lr})
# OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd})
kernel = RBFSteinKernel()

t0 = time.time()
svi, opt = do_inference(
    X_l_list_clean,
    y_clean,
    factor_model,
    kernel,
    opt = OPT,
    # elbo = LOSS,
    inference = "svgd",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.3,
    min_epochs = 10,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```

```{python}
params1 = pyro.get_param_store()
params2 = pyro.get_param_store()
# pa
param_diff_norm_dict = {k: torch.norm(params1[k] - params2[k]).item() for k in pyro.get_param_store()}
```

```{python}

```

```{python}
all(n < 0.01 for n in param_diff_norm_dict.values())
```

```{python}
params1['AutoNormal.locs.Lambda_l1']
```

## Plot loss
```{python}
p = sns.relplot(
    data = factor_model.loss_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = factor_model.var_param_convergence_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```


#### From loaded dict

```{python}
d.keys()
```

```{python}
p = sns.relplot(
    data = d2['loss_history'],
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = d2['param_convergence_history'],
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```




## Evaluating before local training
```{python}
TRAINING_SPLIT = False
```

```{python}
L = int(sim_data_multiview_torch.get("L"))
sites = [Sites.joint_structure_l.format(l = l) for l in range(L)] \
    + [Sites.view_structure_l.format(l = l) for l in range(L)] \
    + [Sites.Z] + [Sites.Phi_l.format(l = l) for l in range(L)]
outcome_sites = ["y"]

post_samples = train_handler.predict(train_X_l_list_clean, 100, sites)
post_samples_y_train = train_handler.predict(train_X_l_list_clean, 100, outcome_sites)
post_samples_y = train_handler.predict(test_X_l_list_clean, 100, outcome_sites)

# if TRAINING_SPLIT:
    
# else:
#     post_samples = train_handler.predict(X_l_list_clean, 100, sites)
#     post_samples_y_train = train_handler.predict(X_l_list_clean, 100, outcome_sites)
#     post_samples_y = train_handler.predict(X_l_list_clean, 100, outcome_sites)
```


```{python}
SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)
                
# Filter corresponding rows of test set structures. Note using PERP structures
train_SIM_decomp = {k: v for k, v in SIM_decomp.items()}
# if TRAINING_SPLIT:
train_SIM_decomp['SIM_Z'] = train_SIM_decomp['SIM_Z'][train_idx, :]
train_SIM_decomp['SIM_Phi_l_list'] = [Phi[train_idx, :] for Phi in train_SIM_decomp['SIM_Phi_l_perp_list']]
train_SIM_decomp['SIM_Phi_l_perp_list'] = [Phi[train_idx, :] for Phi in train_SIM_decomp['SIM_Phi_l_perp_list']]

eval_structures = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    post_samples,
                                                    post_samples_y,
                                                    train_SIM_decomp,
                                                    # train_y_clean.squeeze()) 
                                                    test_y_clean.squeeze())

eval_structures_train = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    post_samples,
                                                    post_samples_y_train,
                                                    train_SIM_decomp,
                                                    # train_y_clean.squeeze()) 
                                                    train_y_clean.squeeze())
```

```{python}
eval_metric_table = eval_performance(**eval_structures)
# eval_metric_table = eval_performance(**eval_structures_train)
eval_metric_table 
```



```{python}
# eval_structures.keys()
# [struct.shape for struct in eval_structures['post_pred_joint_data_struct']]
[struct.shape for struct in eval_structures['sim_joint_data_struct']]
```
```{python}
[eval_rse(est, sim).detach().item() for est, sim in \
        zip(eval_structures['post_pred_joint_data_struct'], eval_structures['sim_joint_data_struct'])]
```

```{python}
post_samples.keys()
```

### Check visual fit of outcome predictions
```{python}
p = sns.scatterplot(x = eval_structures['post_pred_outcome'].tolist(), 
                    y = eval_structures['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = eval_structures['post_pred_outcome'].tolist(), 
            y = eval_structures['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
```

```{python}
# torch.mean(eval_structures['post_pred_outcome'])
# torch.std(eval_structures['post_pred_outcome']))
```

```{python}
p = sns.scatterplot(x = eval_structures_train['post_pred_outcome'].tolist(), 
                    y = eval_structures_train['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = eval_structures_train['post_pred_outcome'].tolist(), 
            y = eval_structures_train['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
```


### Verify: simulated structures are orthogonal

```{python}
[torch.norm(Phi.T @ train_SIM_decomp['SIM_Z']) for Phi in train_SIM_decomp['SIM_Phi_l_perp_list']]
```

### Verify: optimized structures are orthogonal

```{python}
# Calculate structure posterior means
joint_means = [torch.mean(post_samples[Sites.joint_structure_l.format(l = l)], dim = 0) for l in range(L)]
view_means = [torch.mean(post_samples[Sites.view_structure_l.format(l = l)], dim = 0) for l in range(L)]
Z_means = torch.mean(post_samples[Sites.Z], dim = 0)
Phi_l_means = [torch.mean(post_samples[Sites.Phi_l.format(l = l)], dim = 0) for l in range(L)]
```

```{python}
est_joint_struct_cat = torch.cat(joint_means, dim = 1)
```

```{python}
[torch.norm(est_view_struct_l.T @ est_joint_struct_cat) for est_view_struct_l in view_means]
```

```{python}
[torch.norm(Phi_est.T @ Z_means) for Phi_est in Phi_l_means]
```

Save param store before local training

```{python}
train_param_store = pyro.get_param_store()
model_params = factor_model.params
```

```{python}
# model_params
```

```{python}
# new_factor_model = SupMultiviewDecomp(
#     int(k),
#     k_l_list.int().tolist(),
#     include_view_factors = True,
#     dense = False
# )
# new_factor_model.params = model_params
```


```{python}
# factor_model.predict_forward = new_factor_model.predict_forward
# factor_model.predict_guide = new_factor_model.predict_guide
```
## Local training


```{python}
# factor_model.params.keys()
```

```{python}
# factor_model.params[Params.a_rho_gamma_l.format(l = 0)]
```

```{python}
# test_handler = ModelHandler("test",
#                             factor_model,
#                             LOCAL_OPT, 
#                             LOCAL_LOSS)
```

```{python}
import copy
```

```{python}
factor_model_copy = copy.deepcopy(factor_model)
```

```{python}
factor_model_copy.local_loss_history
```

```{python}
factor_model = copy.deepcopy(factor_model_copy)
```


```{python}

```

```{python}
param_store = pyro.get_param_store()
pred_param = [x for x in param_store.keys() if "_pred" in x]
for name in pred_param:
    del param_store[name]
```

```{python}
param_store.keys()
```

```{python}
LOCAL_OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd})
LOCAL_LOSS = Trace_ELBO(num_particles = 1)

test_handler = ModelHandler("predict",
                            factor_model,
                            LOCAL_OPT, 
                            LOCAL_LOSS)

t0 = time.time()
svi = test_handler.do_inference(
    test_subset,
    variational_tol = 0.3,
    min_epochs = 200,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    verbose = True
    )
t1 = time.time()
test_run_minibatch = t1 - t0
print(f"Minibatch runtime: {test_run_minibatch / 60} mins, , {factor_model.local_epochs} epochs")
```

```{python}
p = sns.relplot(
    data = factor_model.local_loss_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = factor_model.local_var_param_convergence_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```

## Evaluate after local training

```{python}
sites = [f'joint_structure_l{l}' for l in range(L)] + [f'view_structure_l{l}' for l in range(L)]
outcome_sites = ["y"]
pred_outcome_sites = ["y_pred"]

local_post_samples = train_handler.predict(train_X_l_list_clean, 100, sites)
local_post_samples_y_train = train_handler.predict(train_X_l_list_clean, 100, outcome_sites)
local_post_samples_y = test_handler.predict(test_X_l_list_clean, 100, pred_outcome_sites)

SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)
                
# Filter corresponding rows of test set structures
train_SIM_decomp = {k: v for k, v in SIM_decomp.items()}
train_SIM_decomp['SIM_Z'] = train_SIM_decomp['SIM_Z'][train_idx, :]
train_SIM_decomp['SIM_Phi_l_perp_list'] = [Phi[train_idx, :] for Phi in train_SIM_decomp['SIM_Phi_l_perp_list']]

local_eval_structures = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    local_post_samples,
                                                    local_post_samples_y,
                                                    train_SIM_decomp,
                                                    # train_y_clean.squeeze()) 
                                                    test_y_clean.squeeze())

local_eval_structures_train = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    local_post_samples,
                                                    local_post_samples_y_train,
                                                    train_SIM_decomp,
                                                    # train_y_clean.squeeze()) 
                                                    train_y_clean.squeeze())
```

```{python}
local_post_samples_y.keys()
```

```{python}
local_eval_structures['sim_outcome']
```

```{python}
local_eval_structures['post_pred_outcome']
```

```{python}
local_eval_metric_table = eval_performance(**local_eval_structures)
# eval_metric_table = eval_performance(**eval_structures_train)
local_eval_metric_table 
```

```{python}
p = sns.scatterplot(x = local_eval_structures['post_pred_outcome'].tolist(), 
                    y = local_eval_structures['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = local_eval_structures['post_pred_outcome'].tolist(), 
            y = local_eval_structures['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
```

```{python}
pyro.param(Sites.sigma2_y)
```

```{python}
p = sns.scatterplot(#x = local_eval_structures_train['post_pred_outcome'].tolist(), 
                    x = (local_eval_structures_train['post_pred_outcome'] * torch.sqrt(sigma2_y_samples).mean()).tolist(), 
                    y = local_eval_structures_train['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(#x = local_eval_structures_train['post_pred_outcome'].tolist(), 
            x = (local_eval_structures_train['post_pred_outcome'] * torch.sqrt(sigma2_y_samples).mean()).tolist(),
            y = local_eval_structures_train['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
```


```{python}
p = sns.scatterplot(x = local_eval_structures_train['post_pred_outcome'].tolist(), 
                    y = local_eval_structures_train['sim_outcome'].squeeze().tolist())
sns.scatterplot(x = eval_structures_train['post_pred_outcome'].tolist(), 
                y = eval_structures_train['sim_outcome'].squeeze().tolist(),
                ax = p,
                color = "red",
                alpha = 0.5)         
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = local_eval_structures_train['post_pred_outcome'].tolist(), 
            y = local_eval_structures_train['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
sns.regplot(x = eval_structures_train['post_pred_outcome'].tolist(), 
            y = eval_structures_train['sim_outcome'].squeeze().tolist(), scatter = False, ax = p,
            color = "red")
```

Have global loadings changed?
```{python}
# torch.equal(pyro.param('loc_Lambda_l0'), 
#             factor_model.params['loc_Lambda_l0']
#             )
torch.equal(pyro.param('loc_Lambda_l0'), 
            train_param_store['loc_Lambda_l0']
            )
            # train_param_store
```


Compare training set predictions before and after local training. Did they change when we performed local training? Do the training set predictions for indices 

```{python}
pd.DataFrame({
    'simulated': eval_structures_train['sim_outcome'].squeeze(),
    'pred_train1': eval_structures_train['post_pred_outcome'],
    'pred_train2': local_eval_structures_train['post_pred_outcome']
})
```


## Plot loadings
```{python}
sns.heatmap(
    pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy(),
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)
# pyro.param(Params.loc_Lambda_l.format(l = 0)).shape
```

```{python}
est_Lambda0 = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy()
est_Lambda0_svd = np.linalg.svd(est_Lambda0)
```

```{python}
np.sqrt(500) + np.sqrt(100)
# p_l_list
```

```{python}
sns.heatmap(
    varimax(est_Lambda0),
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)

```


```{python}
# sns.heatmap(
#     varimax(est_Lambda0),
# # sim_data_multiview_torch.get('Lambda_l')[0],
# cmap="coolwarm"
# )

```


```{python}
np.linalg.svd(varimax(est_Lambda0)).S
```

```{python}
est_Lambda0_svd.S
```
```{python}
np.cumsum(est_Lambda0_svd.S ** 2) / sum(est_Lambda0_svd.S ** 2)
```

```{python}
pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy()[1, :]
```


```{python}
sns.heatmap(
    # pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy(),
    sim_data_multiview_torch.get('Lambda_l')[0],
    cmap="coolwarm"
)
```


```{python}
sns.heatmap(
    pyro.param(Params.loc_Z).detach().numpy(),
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)
```


```{python}
local_post_samples.keys()
```


```{python}
local_post_samples = post_samples
```

```{python}
J0 = local_post_samples[Sites.joint_structure_l.format(l = 0)].mean(dim = 0)
A0 = local_post_samples[Sites.view_structure_l.format(l = 0)].mean(dim = 0)
```


```{python}
J = [local_post_samples[Sites.joint_structure_l.format(l = l)].mean(dim = 0) for l in range(L)]
A = [local_post_samples[Sites.view_structure_l.format(l = l)].mean(dim = 0) for l in range(L)]
```


```{python}
import numpy as np
```
```{python}
np.linalg.matrix_rank(torch.cat(A, dim = 1).detach().numpy())
```

```{python}
np.linalg.matrix_rank(torch.cat(J, dim = 1).detach().numpy())
```


```{python}
[j.shape for j in J]
```

```{python}
(A0.T @ J0)
```

```{python}
Lambda0_est = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy()
Lambda0_sim = sim_data_multiview_torch.get('Lambda_l')[0].numpy()
```

```{python}
Lambda0_est @ Lambda0_est.T - 
```

```{python}
Lambda0_sim @ Lambda0_sim.T
```

```{python}
import numpy as np
```
```{python}
np.linalg.norm(
    Lambda0_est @ Lambda0_est.T - Lambda0_sim @ Lambda0_sim.T,
    ord = "fro")
```

## Debug

```{python}
trace = pyro.poutine.trace(
    factor_model.predict_forward
    ).get_trace(
        test_X_l_list_clean,
        torch.arange(test_X_l_list_clean[0].shape[0]),
        test_y_clean.squeeze())

trace.compute_log_prob() # optional, but allows printing of log_prob shapes

print(trace.format_shapes())
```

```{python}
pred_sites = [f'joint_structure_l{l}_pred' for l in range(L)] + [f'view_structure_l{l}_pred' for l in range(L)] + [Sites.Z_pred]
local_post_samples_test = test_handler.predict(test_X_l_list_clean, 100, pred_sites)

local_post_samples = train_handler.predict(train_X_l_list_clean, 100, sites + [Sites.Z])
# local_post_samples_y_train = train_handler.predict(train_X_l_list_clean, 100, outcome_sites)
# local_post_samples_y = test_handler.predict(test_X_l_list_clean, 100, outcome_sites)
```

```{python}
local_post_samples_test.keys()
```

```{python}
local_post_samples.keys()
```

```{python}
pyro.param(Params.loc_Z_pred).shape
```

```{python}
# Debug: Check variance in samples
y_samples = local_post_samples_y[Sites.y_pred]  # Shape: (100, n_test)
print(f"Y samples shape: {y_samples.shape}")
print(f"Variance across samples per observation:")
print(y_samples.var(dim=0))  # Should have non-trivial variance

# Check if Z_pred is varying
# if Sites.Z_pred in local_post_samples_y:
#     Z_samples = local_post_samples_y[Sites.Z_pred]
#     print(f"Z variance across samples: {Z_samples.var(dim=0).mean()}")
if Sites.Z_pred in local_post_samples_test:
    Z_samples_train = local_post_samples[Sites.Z]
    Z_samples_test = local_post_samples_test[Sites.Z_pred]
    print(f"Z variance across training set samples: {Z_samples_train.var(dim=0).mean()}")
    print(f"Z variance across test set samples: {Z_samples_test.var(dim=0).mean()}")

    # Z_samples_train = local_post_samples[Sites.Z]
    # Z_samples_test = local_post_samples_test[Sites.Z_pred]
    print(f"Z mean across training set samples: {Z_samples_train.mean(dim=0).mean()}")
    print(f"Z mean across test set samples: {Z_samples_test.mean(dim=0).mean()}")
```

```{python}
Z_samples_train.mean(dim = 0).shape
```

```{python}
param_store = pyro.get_param_store()

scale_Z_pred = param_store[Params.scale_Z_pred]
print(f"Scale Z_pred stats:")
print(f"  Mean: {scale_Z_pred.mean():.4f}")
print(f"  Min: {scale_Z_pred.min():.4f}")
print(f"  Max: {scale_Z_pred.max():.4f}")

```

```{python}
# After test inference
param_store = pyro.get_param_store()
a_sigma_y = param_store[Params.a_sigma_y]
b_sigma_y = param_store[Params.b_sigma_y]

print(f"a_sigma_y: {a_sigma_y.item():.4f}")
print(f"b_sigma_y: {b_sigma_y.item():.4f}")

# Expected variance of y noise
if a_sigma_y > 1:
    expected_sigma2_y = b_sigma_y / (a_sigma_y - 1)
    print(f"Expected sigma_y^2: {expected_sigma2_y.item():.4f}")
    print(f"Expected sigma_y: {torch.sqrt(expected_sigma2_y).item():.4f}")

# Sample it directly
sigma2_y_samples = dist.InverseGamma(a_sigma_y, b_sigma_y).sample((1000,))
print(f"Sampled sigma_y mean: {torch.sqrt(sigma2_y_samples).mean():.4f}")
print(f"Sampled sigma_y std: {torch.sqrt(sigma2_y_samples).std():.4f}")
```

```{python}

```

## Save model and optimzer state

```{python}
opt.get_state()
# pyro.get_param_store().get_state()
```

```{python}
out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/rmf_ard")
out_filename = os.path.join(out_path, "batch_run_n1000p500_customguide.pth")
```

```{python}
out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/rmf_ard")
out_filename = os.path.join(out_path, "batch_run_n1000p500_customguide.pth")

torch.save({
    "inference_time": run,
    "model_param_store": pyro.get_param_store(),
    "model_state_dict": pyro.get_param_store().get_state(),
    "optimizer_state": opt.get_state(),
    "loss_history": factor_model.loss_history
}, out_filename)
```

```{python}
pyro.get_param_store().get_state()
```

```{python}
# out_filename_base = "batch_run_n500p100_autonormalguide"
# out_filename_base + ".pth"
```

```{python}
out_filename_base = "batch_run_n500p100_autonormalguide"

out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/model")
out_filename = os.path.join(out_path, out_filename_base + ".pth")

torch.save({
    "inference_time": run_minibatch,
    # "model_param_store": pyro.get_param_store(),
    "model_state_dict": pyro.get_param_store().get_state(),
    "optimizer_state": opt.get_state(),
    "loss_history": factor_model.loss_history
}, out_filename)
```


```{python}
pyro.get_param_store().save(os.path.join(out_path, out_filename_base + "_paramstore.pth"))
```

```{python}
mod_info = torch.load(out_filename)
```


```{python}
mod_info.items()
```


```{python}
print(run)
```

Save parameter store 
```{python}
pyro.get_param_store().save("rmf_ard.params_n2000p10000.save")
```

```{python}
pyro.get_param_store().get_all_param_names()
```


```{python}
for name in pyro.get_param_store().get_all_param_names():
    print(name)
    # print(pyro.param(name))
```

```{python}

sns.heatmap(
    pyro.param('AutoNormal.locs.Lambda_l0').detach(),
    cmap="coolwarm"
)

torch.isclose(pyro.param('AutoNormal.locs.Lambda_l0').detach(), torch.tensor(0.))
```

```{python}
def calc_sparsity(tens):
    return sum((tens == 0).flatten()).item() / (tens).flatten().size()[0]
```

```{python}
calc_sparsity(pyro.param('AutoNormal.locs.Lambda_l0').detach())
torch.linalg.matrix_rank(pyro.param('AutoNormal.locs.Lambda_l0').detach())
```

```{python}
sim_data_multiview_torch.get('Lambda_l')[0]
```


# Optimizer hyperparameter tuning

Run the model on the same data with different optimizer parameters. Save the model and evaluation metrics (RSE) from each fit. Compare which parameters yield the best loss and metrics

```{python}

hyperparam_grid = itertools.product()
```

# Evaluate
## Evaluate latent structure reconstruction
SupMultiviewDecomp


```{python}
#################
# Calculate simulated and posterior sample structures
SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)
            
# Filter corresponding rows of test set structures
train_SIM_decomp = {k: v for k, v in SIM_decomp.items()}
train_SIM_decomp['SIM_Z'] = train_SIM_decomp['SIM_Z'][train_idx, :]
train_SIM_decomp['SIM_Phi_l_list'] = [Phi[train_idx, :] for Phi in train_SIM_decomp['SIM_Phi_l_list']]

eval_structures = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    post_samples,
                                                    post_samples_y,
                                                    train_SIM_decomp,
                                                    test_y_clean.squeeze())

# eval_structures
```

```{python}
eval_metric_table = eval_performance(**eval_structures)
eval_metric_table
```

Individual functions
```{python}
L = int(sim_data_multiview_torch["L"])
```

```{python}
EST_decomp = extract_est_decomp(L, True)

EST_Struct_shared_l_list = list(map(calc_struct, \
    [EST_decomp.get("EST_Z")] * L, EST_decomp.get("EST_Lambda_l_list")))
EST_Struct_view_l_list = list(map(calc_struct, \
    EST_decomp.get("EST_Phi_l_list"), EST_decomp.get("EST_Gamma_l_list")))
```

```{python}
SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)

SIM_Struct_shared_l_list = list(map(calc_struct, \
    [SIM_decomp.get("SIM_Z")]* L, SIM_decomp.get("SIM_Lambda_l_list")))
SIM_Struct_view_l_list = list(map(calc_struct, \
    SIM_decomp.get("SIM_Phi_l_list"), SIM_decomp.get("SIM_Gamma_l_list")))
```


Rescale structures using original data view means and sds
```{python}

EST_Struct_shared_l_list_rescaled = scale_est_struct(EST_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)
SIM_Struct_shared_l_list_rescaled = scale_sim_struct(SIM_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)


EST_Struct_view_l_list_rescaled = scale_est_struct(EST_Struct_view_l_list, X_l_mean_list, X_l_sd_list)
SIM_Struct_view_l_list_rescaled = scale_sim_struct(SIM_Struct_view_l_list, X_l_mean_list, X_l_sd_list)
```

Structure relative squared errors

```{python}
shared_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_shared_l_list_rescaled, SIM_Struct_shared_l_list)]
view_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_view_l_list_rescaled, SIM_Struct_view_l_list)]
```


```{python}
eval_metric_table = pd.melt(pd.DataFrame({
    "shared": shared_rse,
    "view_specific": view_rse
    }
    ).rename_axis('view').reset_index(),
    id_vars = ["view"],
    value_vars = ["shared", "view_specific"],
    var_name = "structure",
    value_name = "rse").\
    assign(n = int(sim_data_multiview_torch.get("N")),
        p = int(sim_data_multiview_torch.get("p_l")[0]),
        snr_x = int(sim_data_multiview_torch.get("snr_x")[0]),
        snr_y = int(sim_data_multiview_torch.get("snr_y"))
        )
eval_metric_table
```


Outcome
```{python}
sim_factors_cat = torch.cat(
    (pyro.param("AutoNormal.locs.Z"),
    *[pyro.param(f"AutoNormal.locs.Phi_l{l}") for l in range(L)]),
    1
)

# sim_factors_cat_rescale = sim_factors_catX_l_sd_list

sim_coef = pyro.param("AutoNormal.locs.beta")

sim_y = torch.matmul(sim_factors_cat, sim_coef)
```


```{python}
sim_y
```

```{python}
sim_y * y_std
```
```{python}
X_l_sd_list
```
```{python}
torch.sum((sim_y - y_clean.squeeze()) ** 2) / len(y)
```
```{python}
# ((sim_y - y) ** 2 / len(y)).shape
torch.nn.functional.mse_loss(sim_y, y_clean.squeeze())

```

If post samples are available, check this:

```{python}
post_sample_y = post_samples.get('y').mean(dim = 0)
post_sample_y
```
```{python}
post_sample_y = post_samples_outcome.get('y').mean(dim = 0)
torch.nn.functional.mse_loss(post_sample_y, y_clean.squeeze())
```

```{python}
y_clean.squeeze()
```

```{python}
sim_coef
```

```{python}
sim_data_multiview_torch.get("beta")
```


Plot

```{python}
import matplotlib.pyplot as plt
```
```{python}
p = sns.scatterplot(x = sim_y.tolist(), y = y_clean.T.tolist()[0])
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = sim_y.tolist(), y = y_clean.T.tolist()[0], scatter = False, ax = p)

```


```{python}
y_clean.squeeze().tolist()
```
```{python}
# USING POSTERIOR SAMPLES
# p = sns.scatterplot(x = sim_y.tolist(), y = y_clean.T.tolist()[0])
p = sns.scatterplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist(), scatter = False, ax = p)

```



## Predict 

```{python}
# import pyro
# import torch
d = torch.load('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n100p100_snr2.2_sparse0_deltak0_rep7.pth')

pyro.get_param_store().load('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n100p100_snr2.2_sparse0_deltak0_rep7_paramstore.pth')
```


```{python}
d2 = torch.load('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n100p100_snr2.2_sparse0_deltak0_rep1.pth')
```

```{python}
d
```

```{python}
os.getcwd()
```

```{python}
#| label: Load param store


pyro.clear_param_store()
# pyro.get_param_store().load("rmf_ard.params_n2000p10000.save")
pyro.get_param_store().load("./results/model/batch_run_n500p100_autonormalguide_paramstore.pth")
```

SupMultiviewDecomp

```{python}
guide = None
```

Initialize model/guide objects for param store 
```{python}
#| label: Initialize model and guide if not already
factor_model = SupMultiviewDecomp(
    int(k),
    k_l_list.int().tolist(),
    n,
    include_view_factors = True
)

def subsample_create_plates(X, batch_idx, y = None):
    # m = len(batch_idx)
    return pyro.plate("obs", factor_model.n, subsample = batch_idx)
# guide = factor_model.guide

guide = pyro.infer.autoguide.AutoNormal(
    factor_model, 
    create_plates = subsample_create_plates)
```

Posterior samples for structures

```{python}
sites = [f'joint_structure_l{l}' for l in range(L)] + [f'view_structure_l{l}' for l in range(L)]
sites
```

```{python}
predictive = pyro.infer.Predictive(
    factor_model, 
    guide = guide, 
    num_samples = 1000,
    return_sites = sites)

post_samples = predictive(
    X_l_list_clean,
    torch.arange(n),
    y.squeeze()
    )
```

```{python}
# post_samples = post_samples_
```

```{python}
joint_structure_summaries = summarise_structure_list(post_samples, L, "joint")
individual_structure_summaries = summarise_structure_list(post_samples, L, "individual")

POST_joint_struct_l_list = [summary.get('mean') for summary in joint_structure_summaries]
POST_individual_struct_l_list = [summary.get('mean') for summary in individual_structure_summaries]
```

```{python}
X_l_list_clean
```

Predictions of y

```{python}
predictive_outcome = pyro.infer.Predictive(
    factor_model, 
    guide = guide, 
    num_samples = 1000,
    return_sites=["y"])

post_samples_outcome = predictive_outcome(
    X_l_list_clean,
    torch.arange(n)
    )
```

```{python}
# post_samples_outcome.get('y')
```

```{python}
PRED_outcome_summary = summarise_post_samples(post_samples_outcome.get("y"))
PRED_y = PRED_outcome_summary.get('mean')
```


Evaluation 

```{python}
SIM_joint_struct_l_list_rescaled = SIM_Struct_shared_l_list_rescaled
SIM_individual_struct_l_list_rescaled = SIM_Struct_view_l_list_rescaled
```
```{python}
joint_rse = [eval_rse(est, sim).detach().item() for est, sim in \
    zip(POST_joint_struct_l_list, 
    SIM_joint_struct_l_list_rescaled)]
individual_rse = [eval_rse(est, sim).detach().item() for est, sim in \
    zip(POST_individual_struct_l_list, SIM_individual_struct_l_list_rescaled)]

joint_coverage = eval_credible_interval(
    SIM_joint_struct_l_list_rescaled,
    joint_structure_summaries,
    '95')
individual_coverage = eval_credible_interval(
    SIM_individual_struct_l_list_rescaled,
    individual_structure_summaries,
    '95')

outcome_mse = eval_mse(PRED_y, y_clean.squeeze()).item()
outcome_coverage = eval_post_coverage(
    y_clean.squeeze(),
    PRED_outcome_summary.get('q2.5'),
    PRED_outcome_summary.get('q97.5')
    ).item()

eval_metric_table = pd.wide_to_long(pd.DataFrame({
    "joint.rse": joint_rse,
    "individual.rse": individual_rse,
    "joint.95p_coverage": joint_coverage,
    "individual.95p_coverage": individual_coverage,
    "outcome.mse": outcome_mse,
    "outcome.95p_coverage": outcome_coverage
    }
    ).rename_axis('view').reset_index(),
    stubnames = ['joint', 'individual', 'outcome'],
    i = 'view',
    j = 'metric',
    sep = '.',
    suffix = '.+')
```

```{python}
eval_metric_table
```


```{python}
# USING POSTERIOR SAMPLES eval_structures
# p = sns.scatterplot(x = sim_y.tolist(), y = y_clean.T.tolist()[0])
# p = sns.scatterplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist())
p = sns.scatterplot(x = eval_structures['post_pred_outcome'].tolist(), 
                    y = eval_structures['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
# sns.regplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist(), scatter = False, ax = p)
sns.regplot(x = eval_structures['post_pred_outcome'].tolist(), 
            y = eval_structures['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)

```

```{python}
post_samples.keys()
# dict_keys(['sigma2_gamma_l0', 'Gamma_l0', 'sigma2_gamma_l1', 'Gamma_l1', 'sigma2_gamma_l2', 'Gamma_l2', 'sigma2_lambda_l0', 'Lambda_l0', 'sigma2_lambda_l1', 'Lambda_l1', 'sigma2_lambda_l2', 'Lambda_l2', 'psi_l0', 'psi_l1', 'psi_l2', 'sigma2_beta', 'beta', 'sigma2_y', 'Z', 'Phi_l0', 'Phi_l1', 'Phi_l2', 'y', 'joint_structure_l0', 'view_structure_l0', 'X_l0', 'joint_structure_l1', 'view_structure_l1', 'X_l1', 'joint_structure_l2', 'view_structure_l2', 'X_l2', 'outcome_structure'])

```
```{python}
post_samples_with_y.keys()
# dict_keys(['sigma2_gamma_l0', 'Gamma_l0', 'sigma2_gamma_l1', 'Gamma_l1', 'sigma2_gamma_l2', 'Gamma_l2', 'sigma2_lambda_l0', 'Lambda_l0', 'sigma2_lambda_l1', 'Lambda_l1', 'sigma2_lambda_l2', 'Lambda_l2', 'psi_l0', 'psi_l1', 'psi_l2', 'sigma2_beta', 'beta', 'sigma2_y', 'Z', 'Phi_l0', 'Phi_l1', 'Phi_l2', 'joint_structure_l0', 'view_structure_l0', 'X_l0', 'joint_structure_l1', 'view_structure_l1', 'X_l1', 'joint_structure_l2', 'view_structure_l2', 'X_l2', 'outcome_structure', 'y'])
```


```{python}
post_samples_outcome.get("y").shape
```

```{python}
torch.norm(torch.mean(post_samples.get("joint_structure_l0"), dim = 0) - \
    torch.mean(post_samples_with_y.get("joint_structure_l0"), dim = 0))
```

```{python}
torch.norm(torch.mean(post_samples.get("joint_structure_l0"), dim = 0) - \
    EST_Struct_shared_l_list_rescaled[0])
```

```{python}
EST_Struct_shared_l_list_rescaled[0]
```

```{python}
# EST_decomp = 
PRED_Struct_shared_l_list = [torch.mean(post_samples.get(f"joint_structure_l{l}"), dim = 0) \
    for l in range(L)]

# EST_Struct_shared_l_list = list(map(calc_struct, \
#     [EST_decomp.get("EST_Z")] * L, EST_decomp.get("EST_Lambda_l_list")))
# EST_Struct_view_l_list = list(map(calc_struct, \
#     EST_decomp.get("EST_Phi_l_list"), EST_decomp.get("EST_Gamma_l_list")))
```

```{python}
PRED_Struct_shared_l_list
```

```{python}
EST_Struct_shared_l_list
```

```{python}
eval_rse(PRED_Struct_shared_l_list[0], SIM_Struct_shared_l_list_rescaled[0])
```
```{python}
EST_Struct_shared_l_list
SIM_Struct_shared_l_list_rescaled
```

```{python}
y_post_pred = torch.mean(post_samples_outcome.get("y"), dim = 0)
```

Compare posterior sample mean/median with variational location params in the param store.

```{python}
# J1_summary = summarise_post_samples(post_samples.get('joint_structure_l1'))


joint_structure_summaries = summarise_structure_list(post_samples, L, "joint")
individual_structure_summaries = summarise_structure_list(post_samples, L, "individual")
```

```{python}
joint_structure_summaries[0]
```

```{python}
SIM_Struct_shared_l_list_rescaled[0]
```

```{python}


    
# [eval_post_coverage(sim_struct, lower, upper) for sim_struct, post_summary in zip(SIM_Struct_shared_l_list_rescaled, joint_structure_summaries)]

# eval_post_coverage(SIM_Struct_shared_l_list_rescaled[1],
# J1_summary.get('q25'),
# J1_summary.get('q75'))
```

```{python}
[eval_post_coverage(sim_struct, post_summary.get(lower), post_summary.get(upper)) for sim_struct, post_summary in zip(SIM_Struct_shared_l_list_rescaled, joint_structure_summaries)]
```

```{python}
joint_coverage = eval_credible_interval(
    SIM_Struct_shared_l_list_rescaled,
    joint_structure_summaries,
    '95')

individual_coverage = eval_credible_interval(
    SIM_Struct_view_l_list_rescaled,
    individual_structure_summaries,
    '95')
```

```{python}
individual_coverage
```


```{python}
post_outcome_summary = summarise_post_samples(post_samples_outcome.get("y"))
```

```{python}
y_clean.squeeze()
# post_outcome_summary.get('q2.5')
```

```{python}
eval_post_coverage(y_clean.squeeze(),
    post_outcome_summary.get('q2.5'),
    post_outcome_summary.get('q97.5'))
```

```{python}
torch.sum(torch.logical_and(
            torch.less_equal(post_outcome_summary.get('q2.5'), y_clean),
            torch.greater_equal(post_outcome_summary.get('q97.5'), y_clean)
        )) #/ torch.numel(sim_struct)
```

```{python}
# torch.numel(y_clean)
post_outcome_summary.get('q97.5')
```

```{python}
pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage
            }
            ).rename_axis('view').reset_index()
```

```{python}
outcome_mse = eval_mse(post_sample_y, y_clean.squeeze()).item()
outcome_coverage = eval_post_coverage(y_clean.squeeze(),
    post_outcome_summary.get('q2.5'),
    post_outcome_summary.get('q97.5')).item()
```
```{python}
pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage,
            "outcome.rse": outcome_mse,
            "outcome.95pcoverage": outcome_coverage
            }
            ).rename_axis('view').reset_index()
```
```{python}
pd.wide_to_long(pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage,
            "outcome.mse": outcome_mse,
            "outcome.95p_coverage": outcome_coverage
            }
            ).rename_axis('view').reset_index(),
            stubnames = ['joint', 'individual', 'outcome'],
            i = 'view',
            j = 'metric',
            sep = '.',
            suffix = '.+').\
            assign(n = n,
                p = 40,
                snr_x = 2,
                snr_y = 2,
                runtime = 0
                )
                
```

```{python}
summarise_post_samples('view_structure_l2')
```


```{python}
# J1_summary.get('mean')
eval_rse(J1_summary.get('mean'), SIM_Struct_shared_l_list_rescaled[1])
```

```{python}
J1_summary.get('mean')
```

```{python}
SIM_Struct_shared_l_list_rescaled[1]
```

```{python}
pyro.param("AutoNormal.locs.Z")
```

```{python}
trace = pyro.poutine.trace(factor_model).get_trace(
    X_l_list_clean,
    torch.arange(X_l_list_clean[0].shape[0]),
    y
)
```

```{python}
trace.nodes.get("joint_structure_l0").get("value")
```

```{python}
EST_Struct_shared_l_list[0]
```

```{python}
Lambda_l_post_samples = [post_samples.get(f"Lambda_l{l}") for l in range(L)]

# EST_Lambda_l_list = [pyro.param(f"AutoNormal.locs.Lambda_l{l}") for l in range(L)]
#         EST_Z = pyro.param("AutoNormal.locs.Z")

#         EST_Gamma_l_list = [pyro.param(f"AutoNormal.locs.Gamma_l{l}") for l in range(L)]
#         EST_Phi_l_list = [pyro.param(f"AutoNormal.locs.Phi_l{l}") for l in range(L)]
```


## Elementwise posterior credible interval nominal coverage


```{python}
eval_post_coverage(SIM_Struct_shared_l_list_rescaled[1],
J1_summary.get('q25'),
J1_summary.get('q75'))

# J1_summary.get('q25')
```

```{python}
J1_summary.get('q75')
```

```{python}
# structure_summary["std"]

```

```{python}
Lambda_post_mean
```

```{python}
Struct_est
```

```{python}
def test_fn(X, k, n):
      print(X, k, n)

test_fn(**{"X": X, "k": 5,"n": X.shape[0]})
```

```{python}
[(a, b) for (a, b) in post_pred.items()]
```

```{python}
torch.mean(post_pred["Lambda"], dim = 0)
```

```{python}


svi_samples = {k: v.reshape(1000).detach().cpu().numpy()
                for k, v in post_pred.items()a
                if k != "obs"}
```


# Simulation replicates

```{python}
sim_data_path = "~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/"

# Absolute paths to directories containing dataset replicates
dirs = [os.path.join(sim_data_path, dir) \
    for dir in os.listdir(os.path.expanduser(sim_data_path)) \
        if os.path.isdir(os.path.expanduser(os.path.join(sim_data_path, dir)))]

dirs[0:5]
```

```{python}
filename_dict = {os.path.basename(name): os.listdir(os.path.expanduser(name)) for name in dirs}
```

Parameters
```{python}
n_array = (50, 100, 500, 1000)
p_array = (50, 100, 1000)
snr_x_array = (2, 1, 0.5)
snr_y_array = (2, 1, 0.5)
reps = 1
loading_sparsity = 0

sim_grid = itertools.product(
    n_array,
    p_array,
    snr_x_array,
    snr_y_array,
    # range(reps),
    [loading_sparsity]
)
```

Load sim_data_path and filename_dict previously

```{python}
[x+1 for x in range(1)]
```

```{python}
MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.01

gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))

file_dir_base = "n{}p{}_snr{}.{}_sparse{}" #/sim_data_ywithview_rep{}.rds"
file_name_base = "sim_data_ywithview_rep{}"

model_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models")
model_out_filename_base = "run_autonormalguide_n{}p{}_snr{}.{}_sparse{}_rep{}"

metric_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/metrics")
metric_out_filename_base = "run_autonormalguide_n{}p{}_snr{}.{}_sparse{}_rep{}"

metric_list = []

for n, p, snr_x, snr_y, sparsity in sim_grid:
    pyro.clear_param_store()
    print("Loading:")
    print(file_dir_base.format(n, p, snr_x, snr_y, sparsity))
    # Load data
    # file_name_base.format(n, p, snr_x, snr_y, sparsity) #, rep)
    files_for_condition = load_and_process_rds_data_for_condition(
        file_dir_base.format(n, p, snr_x, snr_y, sparsity), # "n100p100_snr2.2_sparse0", 
        sim_data_path, # loaded above
        filename_dict, # loaded above
        reps) # how many reps to import

    for rep in range(reps):
        ##################
        # Setup replicate data
        print(file_name_base.format(rep))
        sim_data = files_for_condition.get(file_name_base.format(rep))
        
        k = int(sim_data.get("K"))
        X_l_list = sim_data.get("X_l")
        y = sim_data.get("y")
        k_l_list = sim_data.get("K_l").int().tolist()
        n = X_l_list[0].shape[0]
        p_l = int(sim_data.get("p_l")[0])

        # Clean
        clean_X_dict_list = list(map(normalize_tensor_by_col, X_l_list))
        # normalize_tensor_by_col(X)

        # X_clean = clean_X_dict.get("data_clean")
        # X_means = clean_X_dict.get("means")
        # X_stds = clean_X_dict.get("sds")
    
        X_l_list_clean = [clean["data_clean"] for clean in clean_X_dict_list]
        X_l_mean_list = [clean["means"] for clean in clean_X_dict_list]
        X_l_sd_list = [clean["sds"] for clean in clean_X_dict_list]

        y_mean = torch.mean(y)
        y_std = torch.sd(y)
        y_clean = (y - y_mean) / y_std

        ##################
        # Perform model inference
        factor_model = SupMultiviewDecomp(
            k,
            k_l_list,
            n,
            include_view_factors = True
        )

        def subsample_create_plates(X, batch_idx, y = None):
            return pyro.plate("obs", factor_model.n, subsample = batch_idx)
        guide = pyro.infer.autoguide.AutoNormal(
            factor_model, 
            create_plates = subsample_create_plates)

        # OPT = Adam({"lr": initial_lr})
        OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd})
        LOSS = Trace_ELBO(num_particles = 1)

        t0 = time.time()
        svi, opt = do_inference(
            X_l_list_clean,
            y_clean,
            model = factor_model,
            guide = guide,
            opt = OPT,
            elbo = LOSS,
            tol = 0.5, # tolerance is on epoch loss per datum
            epochs = NUM_EPOCHS,
            minibatch_flag = True,
            minibatch_size = MINIBATCH_SIZE
            )
        t1 = time.time()
        run_minibatch = t1 - t0
        
        #################
        # Inference finished, save and evaluate
        # Save model parameters

        model_out_filename = os.path.join(
            model_out_path, 
            model_out_filename_base.format(n, p, snr_x, snr_y, sparsity, rep))
        print("Exporting:")
        print(model_out_filename)
        

        torch.save({
            "inference_time": run_minibatch,
            # "model_param_store": pyro.get_param_store(),
            "model_state_dict": pyro.get_param_store().get_state(),
            "optimizer_state": opt.get_state(),
            "loss_history": factor_model.loss_history
        }, model_out_filename + ".pth")

        pyro.get_param_store().save(model_out_filename + "_paramstore.pth") #os.path.join(model_out_path, model_out_filename + "_paramstore.pth"))
        
        #################
        # Evaluate model 
        EST_decomp = extract_est_decomp(L, True)

        EST_Struct_shared_l_list = list(map(calc_struct, \
            [EST_decomp.get("EST_Z")] * L, EST_decomp.get("EST_Lambda_l_list")))
        EST_Struct_view_l_list = list(map(calc_struct, \
            EST_decomp.get("EST_Phi_l_list"), EST_decomp.get("EST_Gamma_l_list")))

        SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)

        SIM_Struct_shared_l_list = list(map(calc_struct, \
            [SIM_decomp.get("SIM_Z")]* L, SIM_decomp.get("SIM_Lambda_l_list")))
        SIM_Struct_view_l_list = list(map(calc_struct, \
            SIM_decomp.get("SIM_Phi_l_list"), SIM_decomp.get("SIM_Gamma_l_list")))

        EST_Struct_shared_l_list_rescaled = scale_est_struct(EST_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)
        SIM_Struct_shared_l_list_rescaled = scale_sim_struct(SIM_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)

        EST_Struct_view_l_list_rescaled = scale_est_struct(EST_Struct_view_l_list, X_l_mean_list, X_l_sd_list)
        SIM_Struct_view_l_list_rescaled = scale_sim_struct(SIM_Struct_view_l_list, X_l_mean_list, X_l_sd_list)

        shared_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_shared_l_list_rescaled, SIM_Struct_shared_l_list)]
        view_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_view_l_list_rescaled, SIM_Struct_view_l_list)]

        eval_metric_table = pd.melt(pd.DataFrame({
            "shared": shared_rse,
            "view_specific": view_rse
            }
            ).rename_axis('view').reset_index(),
            id_vars = ["view"],
            value_vars = ["shared", "view_specific"],
            var_name = "structure",
            value_name = "rse").\
            assign(n = n,
                p = p_l,
                snr_x = snr_x,
                snr_y = snr_y,
                runtime = run_minibatch
                )

        # Save evaluation
        metric_out_filename = os.path.join(
            metric_out_path, 
            metric_out_filename_base.format(n, p, snr_x, snr_y, sparsity, rep))
        print("Exporting metrics:")
        print(metric_out_filename)

        eval_metric_table.to_csv(metric_out_filename)
        metric_list.append(eval_metric_table)

```


# *Evaluate replicates

```{python}
metric_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/metrics")
# sim_data_path = "~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/"

# Absolute paths to directories containing dataset replicates
dirs = os.listdir(metric_out_path)
```

```{python}
metric_csvs = [pd.read_csv(os.path.join(metric_out_path, name)) for name in dirs if name != ".DS_Store"]
```

```{python}
full_metric_table = pd.concat(metric_csvs)
```

```{python}
full_metric_table 
```

```{python}
p = sns.catplot(
    data = full_metric_table.loc[full_metric_table['structure'] == 'shared'],
    x = 'n',
    y = 'rse',
    row = 'snr_y',
    col = 'snr_x',
    hue = 'p',
    kind = 'box',
    palette = sns.color_palette(palette='Accent')
)
p.fig.suptitle("Shared reconstruction RSE")
```

```{python}
p = sns.catplot(
    data = full_metric_table.drop_duplicates(subset = ['n', 'p', 'snr_x', 'snr_y'],),
    x = 'n',
    y = 'runtime',
    # row = 'snr_y',
    col = 'p',
    # hue = 'p',
    kind = 'box',
    palette = sns.color_palette(palette='Accent')
)
p.fig.suptitle("Model runtime")
```

```{python}
full_metric_table['structure'].unique()
```

# _____________________________


## Predict from param store model Using full helper functions


```{python}
pyro.clear_param_store()

not_conv_model = '/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n100p100_snr2.2_sparse0_deltak0_rep7_paramstore.pth'
conv_model = '/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n100p100_snr2.2_sparse0_deltak0_rep1_paramstore.pth'

pyro.get_param_store().load(conv_model)

conversion.set_conversion(default_converter)
readRDS = robjects.r['readRDS']

sim_data_multiview = readRDS('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data/n100p100_snr2.2_sparse0/sim_data_ywithview_rep1.rds')
sim_data_multiview_torch = {name: r_to_torch(sim_data_multiview.rx2(name)) for name in sim_data_multiview.names}

##################
X_l_list = sim_data_multiview_torch.get("X_l")
X_l_list

y = sim_data_multiview_torch.get("y")
y

k = sim_data_multiview_torch.get("K")
k_l_list = sim_data_multiview_torch.get("K_l")

n = X_l_list[0].shape[0]

TRAINING_SPLIT = True
TRAINING_SIZE = 0.8
RANDOM_SEED = 123
# Perform train/test split if necessary
if TRAINING_SPLIT:
    train_idx, test_idx = train_test_split(
        torch.arange(X_l_list[0].shape[0]),
        train_size = TRAINING_SIZE,
        random_state = RANDOM_SEED,
        shuffle = True
    )
    train_X_l_list = [X[train_idx, :] for X in X_l_list]
    test_X_l_list = [X[test_idx, :] for X in X_l_list]
    
    train_y = y[train_idx]
    test_y = y[test_idx]
else:
    train_idx = torch.arange(n)
    test_idx = torch.arange(n)
    
    train_X_l_list = X_l_list
    test_X_l_list = train_X_l_list
    
    train_y = y
    test_y = train_y

# Clean: remove 0 variance columns and standardize. Using Training data            
X_l_list_column_filters = [zero_variance_col_filter(X) for X in train_X_l_list]

train_X_l_list = [X[:, col_filter] for X, col_filter in zip(train_X_l_list, X_l_list_column_filters)]
test_X_l_list = [X[:, col_filter] for X, col_filter in zip(test_X_l_list, X_l_list_column_filters)]

clean_train_X_dict_list = [normalize_tensor_by_col(X) for X in train_X_l_list]
X_l_mean_list = [clean["means"] for clean in clean_train_X_dict_list]
X_l_sd_list = [clean["sds"] for clean in clean_train_X_dict_list]

clean_test_X_dict_list = [normalize_tensor_by_col(X, means, stds) 
                            for X, means, stds in 
                            zip(test_X_l_list, X_l_mean_list, X_l_sd_list)]

train_X_l_list_clean = [clean["data_clean"] for clean in clean_train_X_dict_list]
test_X_l_list_clean = [clean["data_clean"] for clean in clean_test_X_dict_list]

y_mean = torch.mean(train_y)
y_std = torch.std(train_y)

train_y_clean = (train_y - y_mean) / y_std
test_y_clean = (test_y - y_mean) / y_std

```

```{python}
p = sns.relplot(
    data = factor_model.loss_history,
    # data = d2['loss_history'],
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = factor_model.var_param_convergence_history,
    # data = d2['param_convergence_history'],
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```

## Evaluate


```{python}
OPT.get_state()['loc_Lambda_l0']['state'][0]['exp_avg']
```

```{python}
OPT.get_state()['a_delta_lambda_l2_k3']['state'][0].keys() #['exp_avg']
```

```{python}
pyro.param('loc_Lambda_l0')
```

```{python}


# factor_model = SupMultiviewDecomp(
#     int(k),
#     k_l_list.int().tolist(),
#     n,
#     include_view_factors = True,
#     dense = False
# )

# def subsample_create_plates(X, batch_idx, y = None):
#     # m = len(batch_idx)
#     return pyro.plate("obs", factor_model.n, subsample = batch_idx)
# # guide = factor_model.guide

# guide = pyro.infer.autoguide.AutoNormal(
#     factor_model, 
#     create_plates = subsample_create_plates)

L = int(sim_data_multiview_torch["L"])

sites = [f'joint_structure_l{l}' for l in range(L)] + [f'view_structure_l{l}' for l in range(L)]
outcome_sites = ["y"]
post_samples, post_samples_y = obtain_posterior_pred_samples(factor_model,
                                                            guide,
                                                            1000,
                                                            train_X_l_list_clean,
                                                            # train_X_l_list_clean, 
                                                            test_X_l_list_clean,
                                                            sites,
                                                            outcome_sites)
```


Posterior samples for all sites from train or test
```{python}
n_train = train_X_l_list_clean[0].shape[0]
predictive = pyro.infer.Predictive(factor_model, 
                        guide = guide, 
                        num_samples = 1000) #,
                        # return_sites = structure_return_sites)
post_samples_usingtrain = predictive(
    train_X_l_list_clean,
    torch.arange(n_train)
    )
post_samples_usingtrain.keys()
```


```{python}
n_test = test_X_l_list_clean[0].shape[0]
predictive = pyro.infer.Predictive(factor_model, 
                        guide = guide, 
                        num_samples = 1000) #,
                        # return_sites = structure_return_sites)
post_samples_usingtest = predictive(
    test_X_l_list_clean,
    torch.arange(n_test)
    )
post_samples_usingtest.keys()
```

```{python}
n_test = test_X_l_list_clean[0].shape[0]
predictive_y = pyro.infer.Predictive(factor_model, 
                        guide = guide, 
                        num_samples = 1000,
                        return_sites = ['y'])
# Do not supply y
post_samples_y = predictive_y(
    test_X_l_list_clean,
    torch.arange(n_test)
    )
```


```{python}
torch.mean(post_samples_y.get('y'), dim = 0).shape
```

```{python}
beta_hat = torch.mean(post_samples_usingtrain.get('beta'), dim = 0)
# torch.mean(post_samples_usingtest.get('beta'), dim = 0)
```


```{python}
post_pred_beta = torch.mean(post_samples.get('beta'), dim = 0)
Z = torch.mean(post_samples.get('Z'), dim = 0)
Phi_l0 = torch.mean(post_samples.get('Phi_l0'), dim = 0)
Phi_l1 = torch.mean(post_samples.get('Phi_l1'), dim = 0)
Phi_l2 = torch.mean(post_samples.get('Phi_l2'), dim = 0)

scores_cat = torch.cat([Z, Phi_l0, Phi_l1, Phi_l2], 1)
```

```{python}
pred_y_fromfactor = scores_cat @ post_pred_beta.squeeze()
```

```{python}
SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)
                
# Filter corresponding rows of test set structures
train_SIM_decomp = {k: v for k, v in SIM_decomp.items()}
train_SIM_decomp['SIM_Z'] = train_SIM_decomp['SIM_Z'][train_idx, :]
train_SIM_decomp['SIM_Phi_l_list'] = [Phi[train_idx, :] for Phi in train_SIM_decomp['SIM_Phi_l_list']]

eval_structures = calc_all_structures_with_rescaling(L,
                                                    X_l_list_column_filters,
                                                    X_l_mean_list,
                                                    X_l_sd_list,
                                                    post_samples,
                                                    post_samples_y,
                                                    train_SIM_decomp,
                                                    # train_y_clean.squeeze()) 
                                                    test_y_clean.squeeze())
```


```{python}
eval_metric_table = eval_performance(**eval_structures)
eval_metric_table 
# = eval_metric_table.\
#     assign(n = n,
#         p = p_l,
#         snr_x = snr_x,
#         snr_y = snr_y,
#         rep = rep,
#         sparsity = sparsity,
#         k = k,
#         runtime = run_minibatch
#         )
```

```{python}
eval_structures['post_pred_outcome']
eval_structures['sim_outcome'].squeeze()
```

Plot posterior predictions versus simulated

```{python}
p = sns.scatterplot(x = eval_structures['post_pred_outcome'].tolist(), 
                    y = eval_structures['sim_outcome'].squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
# sns.regplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist(), scatter = False, ax = p)
sns.regplot(x = eval_structures['post_pred_outcome'].tolist(), 
            y = eval_structures['sim_outcome'].squeeze().tolist(), scatter = False, ax = p)
```


Plot y from posterior predictions versus from factor times beta
```{python}
# p = sns.scatterplot(x = eval_structures['post_pred_outcome'].tolist(), 
#                     y = eval_structures['sim_outcome'].squeeze().tolist())

p = sns.scatterplot(#x = eval_structures['post_pred_outcome'].tolist(), 
                    x = test_y_clean.squeeze().tolist(), 
                    # y = test_y_clean.squeeze().tolist())
                    y = torch.mean(post_samples_y.get('y'), dim = 0).tolist()) 
                    #pred_y_fromfactor.tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
# sns.regplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist(), scatter = False, ax = p)
sns.regplot(x = test_y_clean.squeeze().tolist(), 
            y = torch.mean(post_samples_y.get('y'), dim = 0).tolist(), scatter = False, ax = p)
```


```{python}
eval_structures.get('sim_joint_data_struct')[0].shape
```

```{python}
eval_structures.get('post_pred_joint_data_struct')
# train_SIM_decomp.keys()
```


```{python}
torch.nn.functional.mse_loss(eval_structures['sim_outcome'].squeeze(), eval_structures['post_pred_outcome'])
```


Do posterior predictions for test set align with prior predictive?


```{python}
predictive_prior = pyro.infer.Predictive(factor_model, 
                                        num_samples=1000)
prior_samples = predictive_prior(test_X_l_list_clean, 
                        torch.arange(test_X_l_list_clean[0].shape[0]))
```

```{python}
pred_y_prior_samples_outcomestructure = torch.mean(prior_samples.get('outcome_structure'), dim = 0)
```


```{python}
prior_samples.keys()

Z = torch.mean(prior_samples.get('Z'), dim = 0)
Phi_l0 = torch.mean(prior_samples.get('Phi_l0'), dim = 0)
Phi_l1 = torch.mean(prior_samples.get('Phi_l1'), dim = 0)
Phi_l2 = torch.mean(prior_samples.get('Phi_l2'), dim = 0)

prior_scores_cat = torch.cat([Z, Phi_l0, Phi_l1, Phi_l2], 1)
```

```{python}
prior_scores_cat
```

```{python}
pred_y_fromprior = prior_scores_cat @ post_pred_beta.squeeze()
```

```{python}
pred_y_frompost = torch.mean(post_samples_y.get('y'), dim = 0)
```

```{python}
pd.DataFrame(dict(
    # simulated data
    sim = test_y_clean.squeeze().tolist(),
    # Posterior predictive: conditioned on X_l_test
    post_pred = pred_y_frompost.tolist(),
    # Posterior predictive: manually multiplying scores x beta
    post_pred_manual = pred_y_fromfactor.tolist(),
    # Prior predictive
    prior_pred = pred_y_fromprior.tolist(),
    # Prior predictive: linear 
    prior_pred_linpred = pred_y_prior_samples_outcomestructure)
)
```





```{python}
p = sns.scatterplot(#x = eval_structures['post_pred_outcome'].tolist(), 
                    x = prior_samples_outcomestructure.tolist(), 
                    # y = test_y_clean.squeeze().tolist())
                    y = pred_y_fromprior.tolist())
p.axline((0, 0), slope = 1, color = "black", ls = "--")
```


```{python}
test_y_clean.squeeze().tolist()
```


```{python}
pyro.get_param_store()['AutoNormal.locs.Z'].shape
# pyro.get_param_store()['AutoNormal.scales.Z']
```



```{python}
est_Gamma0 = pyro.get_param_store()['AutoNormal.locs.Gamma_l0']
```


```{python}
[X.shape for X in train_X_l_list_clean]
```


```{python}
def ols_est(Loadings, Data):
    return (torch.inverse(Loadings.T @ Loadings) @ Loadings.T @ Data.T).T
```


```{python}
# torch.inverse(est_Lambda0.T @ est_Lambda0) @ est_Lambda0.T 
# ols_est(est_Gamma0, train_X_l_list_clean[0]) - pyro.get_param_store()['AutoNormal.locs.Phi_l0']
```



```{python}
# est_Gamma0.shape
for key in pyro.get_param_store().keys():
    print(key)
```


```{python}
pyro.get_param_store()['AutoNormal.locs.delta_lambda_l2_k0']
```


# SupMultiviewShared

Multiview model with shared latent scores Z and view-specific loading matrices Lambda_l.
No view-specific factors. Outcome y ~ Z @ beta.

## Setup

```{python}
import os
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"

```

```{python}
import importlib
import sys
sys.path.insert(1, "/Users/jonathanhori/multiomic_integration/python")

import os
os.environ["R_HOME"] = "/Library/Frameworks/R.framework/Resources"

# Reload modules so that any edits to multiview_shared.py or run_methods.py
# are picked up even if the kernel already has old versions cached.
for _mod in ("multiview_shared", "run_methods", "handler", "data_utils", "constants", "factor_interpretation"):
    if _mod in sys.modules:
        importlib.reload(sys.modules[_mod])

import math
import pyro
import torch
import numpy as np
import pandas as pd
import seaborn as sns

import rpy2.robjects as robjects
from rpy2.robjects import default_converter, conversion

from run_methods import (
    process_data_shared,
    train_model_shared,
    train_model_locally_shared,
    evaluate_fitted_model_shared,
    svd_init_shared,
)

from data_utils import r_to_torch, varimax

from constants import Sites, Params

from factor_interpretation import (
    compute_pve, compute_r2_per_factor,
    plot_pve, plot_r2,
    plot_factor_loadings, plot_factor_scores_2d, plot_factor_outcome,
    tabulate_top_features, summarize_factors,
)

from multiview_varimax import multiview_varimax
```


```{python}
os.getcwd()
```
```{python}
import matplotlib.pyplot as plt
```

## Load data

```{python}
conversion.set_conversion(default_converter)
readRDS = robjects.r['readRDS']

# Set USE_MISALIGNED=True to load the asymmetric variance/outcome data, where the
# outcome-relevant factor is not a top-variance direction in X (see
# docs/mofa_comparison_simulations.md). ALIGN_LABEL selects the degree of
# misalignment; it is ignored when USE_MISALIGNED=False.
#   "symmetric"           — beta aligned with top-variance factors (baseline)
#   "mild_misalignment"
#   "strong_misalignment"
#   "anti_aligned"        — beta on the lowest-variance factor
USE_MISALIGNED = True
ALIGN_LABEL    = "anti_aligned"

# rep_config = {
#     "n": 500, "p_l": 1000, "snr_x": 2, "snr_y": 2,
#     "rep": 1, "sparsity": 0.25, "k_delta": 10
# }
rep_config = {
    "n": 100, "p_l": 100, "snr_x": 2, "snr_y": 2,
    "rep": 2, "sparsity": 0.25, "k_delta": 10
}
if USE_MISALIGNED:
    rep_config["align_label"] = ALIGN_LABEL

# Aligned data lives under multi_view_shared/; misaligned under
# multi_view_shared_misaligned/ with an "_align_{label}" suffix on the condition dir.
data_root = "multi_view_shared_misaligned" if USE_MISALIGNED else "multi_view_shared"
cond_dir = (
    f"n{rep_config['n']}p{rep_config['p_l']}"
    f"_snr{rep_config['snr_x']}.{rep_config['snr_y']}"
    f"_sparse{rep_config['sparsity']}"
)
if USE_MISALIGNED:
    cond_dir += f"_align_{ALIGN_LABEL}"

def _shared_rds_path(split):
    return (
        f"~/multiomic_integration/sim/data/{data_root}/k.5/{split}/"
        f"{cond_dir}/sim_data_shared_rep{rep_config['rep']}.rds"
    )

print("Loading:", _shared_rds_path("train"))
train_rds = readRDS(_shared_rds_path("train"))
test_rds  = readRDS(_shared_rds_path("test"))
```

```{python}
conversion.set_conversion(default_converter)

sim_data      = {name: r_to_torch(train_rds.rx2(name)) for name in train_rds.names}
sim_data_test = {name: r_to_torch(test_rds.rx2(name))  for name in test_rds.names}

print("L =", int(sim_data["L"]),
      " K =", int(sim_data["K"]),
      " n =", sim_data["X_l"][0].shape[0],
      " p =", sim_data["X_l"][0].shape[1])
```

## Process data

```{python}
train_subset, test_subset, data_package = process_data_shared(
    sim_data, sim_data_test,
    training_split=False,
    training_size=0.8,
    seed=123,
)

print("train n:", train_subset.tensors[0].shape[0],
      " test n:", test_subset.tensors[0].shape[0])
```

## Train model

```{python}
if torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
elif torch.cuda.is_available():
    DEVICE = torch.device("cuda")
else:
    DEVICE = torch.device("cpu")
DEVICE = torch.device("cpu")
print(f"Using device: {DEVICE}")
```

```{python}
K_DELTA = 10
K_TRUE  = int(sim_data["K"])
# K_DELTA = 10           # over-specification; try 10 to stress-test
K_FIT   = K_TRUE + K_DELTA
```

```{python}
# Best among minibatch sizes (32, 64)
# train_config = {
#     "eta":           0.25,
#     "delta":         1e-16,
#     "t":             0.25, #0.5,
#     "num_particles": 1,
#     "minibatch_size": 64,
#     "min_epochs":    MIN_EPOCHS,
#     "max_epochs":    NUM_EPOCHS,
#     "convergence_criterion": "elbo_snr",
#     "window": 50,
#     "snr_threshold": 1,
# }

# Best among minibatch sizes (32, 64, 128, 256)
# train_config = {
#     "eta":           0.25,
#     "delta":         1e-16,
#     "t":             1,
#     "num_particles": 2,
#     "minibatch_size": 128,
#     "min_epochs":    MIN_EPOCHS,
#     "max_epochs":    NUM_EPOCHS,
#     "convergence_criterion": "elbo_snr",
#     "window": 50,
#     "snr_threshold": 1,
# }
# --- Rank 1  (config_idx=38, mean_rank=18.00) ---
#   eta: 0.25
#   delta: 1e-16
#   t: 1.0
#   num_particles: 2
#   minibatch_size: 128
#   min_epochs: 100
#   max_epochs: 500
#   convergence_criterion: elbo_snr
#   window: 50
#   snr_threshold: 1
#   mean outcome_mse: 0.2332
#   mean cov_frob: 0.0062
#   mean total_time: 22.9119
```

```{python}


NUM_EPOCHS = 500
MIN_EPOCHS = 200

# num_features = sum([train_subset.tensors[i].shape[1] for i in range(1, len(train_subset.tensors)-1)])
num_features = 1

model_config = {
    "k": K_FIT, 
    "dense_model": False,
    "outcome_weight": float(num_features)}

# BASE_SNR_THRESHOLD = 0.15
# N_REF = 500  # condition Optuna was tuned on
# snr_threshold = BASE_SNR_THRESHOLD * math.sqrt(N_REF / rep_config['n'])

train_config = {
    "eta":           0.25,
    "delta":         1e-16,
    "t":             0.1, #0.5,
    "num_particles": 1,
    # "minibatch_size": 128,
    "minibatch_fraction": 0.15,
    "min_epochs":    MIN_EPOCHS,
    "max_epochs":    NUM_EPOCHS,
    "convergence_criterion": "elbo_snr",
    "window": 50,
    "snr_threshold": 5,
}

```

```{python}
pyro.clear_param_store()
factor_model, train_handler, global_state = train_model_shared(
    model_config, train_config, train_subset,
    model_out_filename="/tmp/shared_example_rep1",
    opt="adagrad",
    verbose=True,
    write=False,
    device=DEVICE,
    svd_init=True
)
print(f"Global training: {factor_model.total_epochs} epochs")
```

Plot loss
```{python}
p = sns.relplot(
    data = factor_model.loss_history[1:],
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = np.diff(factor_model.loss_history)[1:],
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = factor_model.var_param_convergence_history[1:],
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```

## Local inference on test set

```{python}
local_config = {**train_config} #, "minibatch_size": 64} #, "min_epochs": 100, 4}

factor_model, test_handler, local_state = train_model_locally_shared(
    factor_model, local_config, test_subset,
    opt="adagrad",
    verbose=True,
    device=DEVICE,
)
print(f"Local training: {factor_model.local_epochs} epochs")
```

## Evaluate

```{python}
eval_table, cov_table, post_samples, post_samples_test = evaluate_fitted_model_shared(
    {**rep_config, 'k_delta': 10}, data_package,
    train_handler, test_handler,
    global_state, local_state,
    N_POSTERIOR_SAMPLES=300,
    metric_out_filename="/tmp/shared_example_metrics_rep1",
)
eval_table
```

```{python}
cov_table
```

```{python}
# post_samples['y']
```

```{python}
import seaborn as sns, matplotlib.pyplot as plt

# Loss curve
fig, ax = plt.subplots()
ax.plot(factor_model.loss_history)
ax.set(xlabel="Epoch", ylabel="ELBO loss", title="SupMultiviewShared training loss")
plt.show()
```

```{python}
# Per-view metrics
print(eval_table[["view", "joint_rse", "test_rse", "joint_95p_coverage"]].to_string(index=False))

print(f"\nOutcome MSE:  {eval_table['outcome_mse'].iloc[0]:.4f}")
print(f"Outcome 95% CI coverage: {eval_table['outcome_95p_coverage'].iloc[0]:.2f}")
```

## Outcome predictions: train and test



```{python}
# from data_utils import summarise_post_samples

# Training: posterior mean of Z_train @ beta (global model, no outcome noise)
# train_post = train_handler.predict(
#     data_package["train_X_l_list_clean"],
#     300,
#     [Sites.outcome_structure],
# )
# train_post[Sites.outcome_structure]
train_pred_mean = post_samples['y'] .mean(dim=0).squeeze()

# Test: posterior mean of Z_test @ beta (local model, no outcome noise)
# test_post = test_handler.predict(
#     data_package["test_X_l_list_clean"],
#     300,
#     [Sites.outcome_structure_pred],
# )
# test_post[Sites.outcome_structure_pred]
test_pred_mean = post_samples_test['y_pred'].mean(dim=0).squeeze()

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
for ax, pred, true, title in [
    (axes[0], train_pred_mean, data_package["train_y_clean"], "Train"),
    (axes[1], test_pred_mean,  data_package["test_y_clean"],  "Test"),
]:
    ax.scatter(pred.tolist(), true.tolist(), alpha=0.6)
    lim = max(abs(true).max().item(), abs(pred).max().item()) * 1.1
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.axline((0, 0), slope=1, color="black", ls="--")
    ax.set_xlabel("Predicted y")
    ax.set_ylabel("True y")
    ax.set_title(f"Outcome predictions — {title}")
plt.tight_layout()
plt.show()
```


## Train: Outcome up-weighting (`outcome_weight`)

The shared scores `Z` are informed by two likelihood terms: the reconstruction
of the views (`X_l = Z @ Lambda_l^T + E_l`) and the outcome (`y = Z @ beta + e`).
Per observation the reconstruction contributes `sum_l p_l` Gaussian terms while
the outcome contributes a single term, so the ELBO is dominated by reconstruction
by a factor of `sum_l p_l` (here in the hundreds–thousands). When the
outcome-relevant factor is *not* a high-variance direction in `X` (the misaligned
regime), the reconstruction gradient barely registers it and whether a given run
recovers it is left to SVI noise — producing large run-to-run variance in
outcome MSE.

`SupMultiviewShared` now accepts `outcome_weight`, which up-weights the outcome
log-likelihood via `pyro.poutine.scale` so it informs `Z` comparably to the
views. `outcome_weight=1.0` is the original objective. A natural scale is the
per-observation count of reconstruction terms, `sum_l p_l`; the cell below sweeps
a few values and compares held-out outcome MSE. Tune it by cross-validation for a
real analysis.

```{python}
# Per-observation reconstruction term count — the imbalance the outcome fights.
X_views_train = data_package["train_X_l_list_clean"]
L_views   = len(X_views_train)
total_p   = sum(int(x.shape[1]) for x in X_views_train)
print(f"L = {L_views} views, total features sum_l p_l = {total_p}")

# Candidate weights: baseline, one-view's worth, and full rebalance.
outcome_weight_grid = [1.0, float(total_p // L_views), float(total_p)]
print("outcome_weight grid:", outcome_weight_grid)
```

```{python}
ow_results = []
fractions = [0.2] #[0.1, 0.2, 0.3, 0.4, 0.5]

for frac in fractions:
    for ow in outcome_weight_grid:
        pyro.clear_param_store()

        ow_model_config = {**model_config, "outcome_weight": ow}
        ow_train_config = {**train_config, "minibatch_fraction": frac}

        fm_ow, train_handler_ow, global_state_ow = train_model_shared(
            ow_model_config, ow_train_config, train_subset,
            model_out_filename=f"/tmp/shared_ow{ow:.0f}_rep1",
            opt="adagrad", verbose=False, write=False, device=DEVICE,
        )

        # Local inference for test Z uses X only — outcome_weight does not leak in.
        fm_ow, test_handler_ow, local_state_ow = train_model_locally_shared(
            fm_ow, {**ow_train_config}, test_subset,
            opt="adagrad", verbose=False, device=DEVICE,
        )

        eval_table_ow, _, _, _ = evaluate_fitted_model_shared(
            {**rep_config, "k_delta": K_DELTA}, data_package,
            train_handler_ow, test_handler_ow,
            global_state_ow, local_state_ow,
            N_POSTERIOR_SAMPLES=300,
            metric_out_filename=f"/tmp/shared_ow{ow:.0f}_metrics_rep1",
        )

        ow_results.append({
            "outcome_weight":  ow,
            "minibatch_fraction": frac,
            "outcome_mse":     float(eval_table_ow["outcome_mse"].iloc[0]),
            "mean_joint_rse":  float(eval_table_ow["joint_rse"].mean()),
            "global_epochs":   int(fm_ow.total_epochs),
        })
        print(f"outcome_weight={ow:>8.1f}  "
            f"minibatch_fraction={frac}  "
            f"outcome_mse={ow_results[-1]['outcome_mse']:.4f}  "
            f"mean_joint_rse={ow_results[-1]['mean_joint_rse']:.4f}")

ow_df = pd.DataFrame(ow_results)
ow_df
```

```{python}
# Outcome MSE vs outcome_weight. The Bayes floor for snr_y is 1 / (1 + snr_y).
snr_y_used = float(rep_config["snr_y"])
bayes_floor = 1.0 / (1.0 + snr_y_used)

fig, ax = plt.subplots(figsize=(6, 4))
ax.plot(ow_df["outcome_weight"], ow_df["outcome_mse"], marker="o")
ax.axhline(bayes_floor, color="black", ls="--",
           label=f"Bayes floor 1/(1+snr_y) = {bayes_floor:.2f}")
ax.set_xscale("log")
ax.set_xlabel("outcome_weight (log scale)")
ax.set_ylabel("Test outcome MSE")
ax.set_title("Effect of outcome up-weighting on held-out prediction")
ax.legend()
plt.tight_layout()
plt.show()
```


## Outcome up-weighting across misaligned scenarios

Sweep `outcome_weight` × `minibatch_fraction` (the two grids from the section
above) for all four alignment regimes, at three `(n, p)` cells:
`(100, 100)`, `(500, 100)`, `(500, 1000)`. This shows where up-weighting the
outcome and/or a larger minibatch recovers prediction in the misaligned regime,
and how that interacts with sample size and dimensionality.

`outcome_weight` is dimension-dependent, so each cell rebuilds the grid with the
same *recipe* as `outcome_weight_grid` above — `[1.0, sum_l p_l / L, sum_l p_l]`
— labelled `1x` / `per-view` / `full` so heatmaps are comparable across `p`.

> **Cost.** This is `len(cells) × 4 labels × SWEEP_REPS × len(outcome_weight_grid)
> × len(fractions)` full train + local-inference + evaluate runs
> (= 3 × 4 × 1 × 3 × 5 = 180 at the defaults). Results are checkpointed to CSV
> after every run and already-completed rows are skipped, so the cell is safe to
> interrupt and resume. Increase `SWEEP_REPS` to quantify the run-to-run variance
> that up-weighting is meant to reduce.

```{python}
# --- sweep configuration -------------------------------------------------------
sweep_cells   = [(100, 100), (500, 100), (500, 1000)]   # (n, p_l)
sweep_labels  = ["symmetric", "mild_misalignment",
                 "strong_misalignment", "anti_aligned"]
SWEEP_REPS    = 3                 # reps per (cell, label); >1 reveals variance
SWEEP_N_POST  = 100               # posterior samples for evaluation
SWEEP_CSV     = "/tmp/shared_misaligned_owframe_sweep.csv"

# Reuses `fractions` and the `outcome_weight_grid` recipe from the section above.
weight_kinds = ["1x", "per-view", "full"]   # labels for the 3 recipe entries


def _load_shared_cell(n, p_l, align_label, rep, snr_x=2, snr_y=2, sparsity=0.25):
    """Load + process one misaligned shared condition into model-ready subsets."""
    conversion.set_conversion(default_converter)
    cond = (f"n{n}p{p_l}_snr{snr_x}.{snr_y}_sparse{sparsity}"
            f"_align_{align_label}")
    root = "~/multiomic_integration/sim/data/multi_view_shared_misaligned/k.5"
    tr = readRDS(f"{root}/train/{cond}/sim_data_shared_rep{rep}.rds")
    te = readRDS(f"{root}/test/{cond}/sim_data_shared_rep{rep}.rds")
    sd      = {nm: r_to_torch(tr.rx2(nm)) for nm in tr.names}
    sd_test = {nm: r_to_torch(te.rx2(nm)) for nm in te.names}
    return process_data_shared(sd, sd_test, training_split=False,
                               training_size=0.8, seed=123)


def _weight_grid_for(dp):
    """Same recipe as outcome_weight_grid, recomputed for this cell's p."""
    views = dp["train_X_l_list_clean"]
    L = len(views)
    tot = sum(int(x.shape[1]) for x in views)
    return [1.0, float(tot // L), float(tot)]
```


```{python}
os.getcwd()
```

```{python}
import os

# Resume from any existing checkpoint.
if os.path.exists(SWEEP_CSV):
    sweep_df = pd.read_csv(SWEEP_CSV)
    done = set(map(tuple, sweep_df[
        ["n", "p_l", "align_label", "rep", "weight_kind", "minibatch_fraction"]
    ].values))
    print(f"Resuming: {len(sweep_df)} rows already done.")
else:
    sweep_df = pd.DataFrame()
    done = set()

for (n_cell, p_cell) in sweep_cells:
    for label in sweep_labels:
        for rep in range(1, SWEEP_REPS + 1):
            dp_subsets = None   # lazy-load only if work remains for this cell

            # Build per-cell weight grid lazily (needs the data dims).
            for frac in fractions:
                for kind in weight_kinds:
                    key = (n_cell, p_cell, label, rep, kind, frac)
                    if key in done:
                        continue
                    if dp_subsets is None:
                        train_sub, test_sub, dp_subsets = _load_shared_cell(
                            n_cell, p_cell, label, rep)
                        cell_weights = dict(zip(weight_kinds,
                                                _weight_grid_for(dp_subsets)))
                    ow = cell_weights[kind]

                    pyro.clear_param_store()
                    ow_cfg = {**model_config, "outcome_weight": ow}
                    tr_cfg = {**train_config, "minibatch_fraction": frac}

                    fm, th, gs = train_model_shared(
                        ow_cfg, tr_cfg, train_sub,
                        model_out_filename="/tmp/sweep_model",
                        opt="adagrad", verbose=False, write=False, device=DEVICE,
                    )
                    fm, teh, ls = train_model_locally_shared(
                        fm, {**tr_cfg}, test_sub,
                        opt="adagrad", verbose=False, device=DEVICE,
                    )
                    et, _, _, _ = evaluate_fitted_model_shared(
                        {**rep_config, "n": n_cell, "p_l": p_cell,
                         "align_label": label, "rep": rep, "k_delta": K_DELTA},
                        dp_subsets, th, teh, gs, ls,
                        N_POSTERIOR_SAMPLES=SWEEP_N_POST,
                        metric_out_filename="/tmp/sweep_metrics",
                    )

                    row = {
                        "n": n_cell, "p_l": p_cell, "align_label": label,
                        "rep": rep, "weight_kind": kind, "outcome_weight": ow,
                        "minibatch_fraction": frac,
                        "outcome_mse": float(et["outcome_mse"].iloc[0]),
                        "mean_joint_rse": float(et["joint_rse"].mean()),
                        "global_epochs": int(fm.total_epochs),
                    }
                    sweep_df = pd.concat([sweep_df, pd.DataFrame([row])],
                                         ignore_index=True)
                    sweep_df.to_csv(SWEEP_CSV, index=False)
                    done.add(key)
                    print(f"n={n_cell} p={p_cell} {label:<20} rep{rep} "
                          f"{kind:<8} frac={frac} -> "
                          f"mse={row['outcome_mse']:.4f}")

print(f"\nDone. {len(sweep_df)} rows in {SWEEP_CSV}")
sweep_df
```

```{python}
# Mean outcome MSE over reps, as a heatmap grid:
#   rows = alignment regime, cols = (n, p) cell; axes = weight_kind × minibatch_fraction.
import seaborn as sns

agg = (sweep_df
       .groupby(["n", "p_l", "align_label", "weight_kind", "minibatch_fraction"])
       ["outcome_mse"].mean().reset_index())

bayes_floor = 1.0 / (1.0 + float(rep_config["snr_y"]))
vmin = agg["outcome_mse"].min()
vmax = agg["outcome_mse"].max()

n_rows, n_cols = len(sweep_labels), len(sweep_cells)
fig, axes = plt.subplots(n_rows, n_cols,
                         figsize=(4 * n_cols, 3.2 * n_rows), squeeze=False)

for i, label in enumerate(sweep_labels):
    for j, (n_cell, p_cell) in enumerate(sweep_cells):
        ax = axes[i][j]
        sub = agg[(agg["align_label"] == label) &
                  (agg["n"] == n_cell) & (agg["p_l"] == p_cell)]
        if sub.empty:
            ax.set_visible(False)
            continue
        pivot = (sub.pivot(index="weight_kind", columns="minibatch_fraction",
                           values="outcome_mse")
                    .reindex(weight_kinds))
        sns.heatmap(pivot, ax=ax, vmin=vmin, vmax=vmax, cmap="viridis_r",
                    annot=True, fmt=".2f", cbar=(j == n_cols - 1),
                    cbar_kws={"label": "outcome MSE"})
        if i == 0:
            ax.set_title(f"n={n_cell}, p={p_cell}")
        if j == 0:
            ax.set_ylabel(f"{label}\noutcome_weight")
        else:
            ax.set_ylabel("")
        ax.set_xlabel("minibatch_fraction" if i == n_rows - 1 else "")

fig.suptitle(f"Test outcome MSE by outcome_weight × minibatch_fraction "
             f"(Bayes floor = {bayes_floor:.2f})", y=1.002)
plt.tight_layout()
plt.show()
```

```{python}
# Per-cell best configuration (lowest mean outcome MSE) and the no-up-weight baseline.
best = (agg.loc[agg.groupby(["n", "p_l", "align_label"])["outcome_mse"].idxmin()]
           .rename(columns={"weight_kind": "best_weight_kind",
                            "minibatch_fraction": "best_minibatch_fraction",
                            "outcome_mse": "best_mse"}))
baseline = (agg[(agg["weight_kind"] == "1x") & (agg["minibatch_fraction"] == 0.1)]
            .rename(columns={"outcome_mse": "baseline_mse_1x_frac0.1"})
            [["n", "p_l", "align_label", "baseline_mse_1x_frac0.1"]])
summary = best.merge(baseline, on=["n", "p_l", "align_label"], how="left")
summary["improvement"] = summary["baseline_mse_1x_frac0.1"] - summary["best_mse"]
summary[["n", "p_l", "align_label", "best_weight_kind",
         "best_minibatch_fraction", "best_mse",
         "baseline_mse_1x_frac0.1", "improvement"]]
```


## OLD: Plot loadings
```{python}
est_Lambda0 = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().cpu().numpy()
est_Lambda0_varimax, R = varimax(est_Lambda0)
```


```{python}
R.shape
```

```{python}
R @ pyro.param('loc_beta').detach().cpu().numpy()
```

```{python}
sns.heatmap(
    est_Lambda0,
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)
```


```{python}
sns.heatmap(
    est_Lambda0_varimax,
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)

```


When does tau become large?
```{python}
delta_sites = [Sites.delta_lambda_l_k.format(l = 0, m = m) for m in range(K_FIT)]
delta_post_samples = train_handler.predict(data_package['train_X_l_list_clean'], 100, delta_sites)
```

```{python}
delta_means = [np.mean(delta_post_samples[site].squeeze().tolist()) for site in delta_sites]
tau = np.cumprod(delta_means)
# delta_post_samples.items() #['delta_lambda_l0_k0'].shape
# sns.relplot(1 / tau, kind = "scatter")
p = sns.relplot(tau, kind = "scatter")
p.set(xlabel = "Factor k", ylabel = "Mean Tau (global shrinkage)")
# p.set_title("Global shrinkage over increasing factor dimension")
```



Plot varimax loadings after order selection
```{python}
# est_Lambda0 = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy()
est_Lambda0_varimax_sliced, R = varimax(est_Lambda0[:, 0:7])

sns.heatmap(
    est_Lambda0_varimax_sliced,
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)

```




```{python}
ssl_all = (est_Lambda0 ** 2).sum(axis = 0).sum()
```

```{python}
pve = ((est_Lambda0 ** 2).sum(axis = 0) / ssl_all)
pve
```

```{python}
sns.relplot(
    pve.detach().cpu().numpy() if isinstance(pve, torch.Tensor) else pve,
    # np.sum(Lambda_est_rotated ** 2, axis = 0),
    kind="line"
    )
```


```{python}
torch.norm(data_package["train_X_l_list_clean"][0]) ** 2
```


```{python}
TSS = (data_package["train_X_l_list_clean"][0] ** 2).sum()
TSS
```


```{python}
# Rank-1 signal for each factor: (n, p, K) -> compute RSS for each k
# z_k is (n,), lambda_k is (p,), outer product is (n, p)
# Residual: X - z_k lambda_k^T for each k

# Z: (n, K), Lambda: (p, K)
# signal[k] = Z[:, k] outer Lambda[:, k] = (n, 1) * (1, p) -> (n, p)
# Do this for all k simultaneously:
# signal has shape (n, p, K)
est_Lambda0 = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().cpu()

signal = Z_est.unsqueeze(1) * est_Lambda0.unsqueeze(0)  # (n, p, K)
signal.shape
```

```{python}
est_Lambda0
```


```{python}
# Residual: X[:, :, None] - signal, shape (n, p, K)
residual = data_package["train_X_l_list_clean"][0].unsqueeze(2) - signal             # (n, p, K)
residual.shape
```


```{python}
# RSS for each k: sum over n and p
RSS = (residual ** 2).sum(dim=(0, 1))          # (K,)
RSS
```


```{python}
r2 = 1.0 - RSS / TSS 
r2
```

```{python}
r2.sum()
```

```{python}
def compute_r2(X, Z, Lambda):
    """
    Compute MOFA-style R^2 for each factor k in a single view.

    Parameters
    ----------
    X      : (n, p) tensor — observed data, assumed already mean-centered
    Z      : (n, K) tensor — factor scores
    Lambda : (p, K) tensor — factor loadings

    Returns
    -------
    r2 : (K,) tensor — R^2 for each factor k
    """
    # Total sum of squares: scalar
    TSS = (X ** 2).sum()

    # Rank-1 signal for each factor: (n, p, K) -> compute RSS for each k
    # z_k is (n,), lambda_k is (p,), outer product is (n, p)
    # Residual: X - z_k lambda_k^T for each k

    # Z: (n, K), Lambda: (p, K)
    # signal[k] = Z[:, k] outer Lambda[:, k] = (n, 1) * (1, p) -> (n, p)
    # Do this for all k simultaneously:
    # signal has shape (n, p, K)
    signal = Z.unsqueeze(1) * Lambda.unsqueeze(0)  # (n, p, K)

    # Residual: X[:, :, None] - signal, shape (n, p, K)
    residual = X.unsqueeze(2) - signal             # (n, p, K)

    # RSS for each k: sum over n and p
    RSS = (residual ** 2).sum(dim=(0, 1))          # (K,)

    r2 = 1.0 - RSS / TSS                           # (K,)
    return r2
```

```{python}
est_Lambda0_varimax = torch.tensor(est_Lambda0_varimax)
# compute_r2(data_package["train_X_l_list_clean"][0], Z_est, est_Lambda0)
r2_varimax = compute_r2(data_package["train_X_l_list_clean"][0], Z_est, est_Lambda0_varimax)
```


```{python}
sns.relplot(
    r2_varimax.detach().cpu().numpy(),
    # np.sum(Lambda_est_rotated ** 2, axis = 0),
    kind="line"
    )
```

```{python}
est_Lambda0.shape[1]
```


```{python}
# post_train = train_handler.predict(
#         [tmb_data_package["X_train"]], 200,
#         return_sites=["structure", 
#         Sites.Lambda_l.format(l=0), 
#         Sites.psi_l.format(l = 0),
#         Sites.y],
# )


train_post = train_handler.predict(
    data_package["train_X_l_list_clean"],
    300,
    ["Z", "Lambda_l0"],
)
train_post = {k: v.cpu() if isinstance(v, torch.Tensor) else v for k, v in train_post.items()}
```

```{python}
Z_est = train_post['Z'].mean(dim = 0)
```

```{python}
Z_est.shape
```

```{python}
train_post
```


```{python}
(data_package["train_X_l_list_clean"][0] - train_post['joint_structure_l0'].mean(dim = 0)).sum(dim = 0).shape
```

## Compare outcome effects

```{python}
sim_data['beta']
```

```{python}
pyro.param('loc_beta').detach().cpu().double()
```



```{python}
_loc_beta = pyro.param('loc_beta').detach().cpu().double()
est_betas = pd.DataFrame({
        'beta': _loc_beta,
        'beta_rot': torch.from_numpy(R).double().T @ _loc_beta,
        'factor': range(0, len(_loc_beta))
        }
        ).melt(id_vars = ['factor'], var_name = "type")
# est_betas['factor'] = np.tile(range(0, len(pyro.param('loc_beta'))), 2)
# est_betas
```

```{python}
g = sns.catplot(
    data = est_betas,
    kind = "bar",
    x = "factor",
    y = "value",
    hue = "type",

)
g.fig.suptitle("Posterior mean beta_k before and after rotation by varimax")
# g.despine(left = True)
```


## Factor Interpretation

Collect posterior-mean loadings and scores from the trained global model.

### Factor summary

```{python}
X_list_interp = data_package["train_X_l_list_clean"]
Z_interp = post_samples['Z'].mean(dim = 0)
Lambda_list_interp = [post_samples[f'Lambda_l{l}'].mean(dim = 0).squeeze() \
        for l in range(len(data_package["train_X_l_list_clean"]))]
view_names = [f"View {l}" for l in range(len(data_package["train_X_l_list_clean"]))]
y_interp = post_samples['y'].mean(dim = 0).squeeze()
beta_interp = post_samples['beta'].mean(dim = 0).squeeze()

factor_summary = summarize_factors(
    X_list = X_list_interp,
    Z = Z_interp,
    Lambda_list = Lambda_list_interp,
    beta = beta_interp,
    y = y_interp,
    beta_samples = post_samples['beta'],
    view_names = view_names,
    plot=True,
    verbose=True,
)

R_varimax = factor_summary["R"]
top_factors_interp = factor_summary["post"]["per_factor"]["factor"].values - 1
top_factors_interp = top_factors_interp.tolist()

```

```{python}
# factor_summary = summarize_factors(
#     X_list_interp, Z_interp, Lambda_list_interp,
#     view_names=view_names,
#     plot=True,
#     verbose=True,
# )
# Rotation matrix for downstream use (e.g. rotating beta)

```

### Proportion of variance explained

```{python}
pve = plot_pve(
    Lambda_list_interp,
    view_names=view_names,
    title="PVE per factor — SupMultiviewShared (unrotated)",
)
```

Comparing measures of variance explained by each factor

```{python}
Lambda_list_interp[0] ** 2
```






```{python}
S_est = (X_list_interp[0].T @ X_list_interp[0] / X_list_interp[0].shape[0])
```

```{python}
Cov_est = (Lambda_list_interp[0] @ Lambda_list_interp[0].T) + torch.diag(psi_l0_interp)
```

```{python}
((sim_data['Lambda_l'][0] ** 2).sum(dim = 0) / (torch.trace(S_est)))
```

```{python}
((Lambda_list_interp[0] ** 2).sum(dim = 0) / (torch.trace(S_est)))
```

```{python}
torch.trace(Lambda_list_interp[0] @ Lambda_list_interp[0].T) / torch.trace(S_est)
```

```{python}
torch.trace(sim_data['Lambda_l'][0] @ sim_data['Lambda_l'][0].T)
```

```{python}
torch.trace(Lambda_list_interp[0] @ Lambda_list_interp[0].T)
```

```{python}
torch.trace(sim_data['Lambda_l'][0] @ sim_data['Lambda_l'][0].T) / torch.trace(S_est)
```

```{python}
torch.diag(Lambda_list_interp[0] @ Lambda_list_interp[0].T)
```

```{python}
Lambda_list_interp[0] ** 2
```


```{python}
((Lambda_list_interp[0] ** 2).sum(dim = 0) / ((Lambda_list_interp[0] ** 2).sum(dim = 0).sum() + psi_l0_interp.sum())).sum()
```

```{python}
(torch.trace(X_list_interp[0].T @ X_list_interp[0] / X_list_interp[0].shape[0])) / ((Lambda_list_interp[0] ** 2).sum(dim = 0).sum() + psi_l0_interp.sum())
```

```{python}
torch.trace(X_list_interp[0].T @ X_list_interp[0] / X_list_interp[0].shape[0])
```

Now do the same after rotation


```{python}
Lambda_rot, R = varimax(Lambda_list_interp[0])
```

```{python}
# sns.heatmap(
#     Lambda_rot,
# # sim_data_multiview_torch.get('Lambda_l')[0],
# cmap="coolwarm"
# )
```

```{python}
((torch.tensor(Lambda_rot) ** 2).sum(dim = 0) / (torch.trace(X_list_interp[0].T @ X_list_interp[0] / X_list_interp[0].shape[0])))
```

```{python}
(torch.tensor(Lambda_rot) ** 2).sum(dim = 0) / ((torch.tensor(Lambda_rot) ** 2).sum(dim = 0).sum() + psi_l0_interp.sum())
```

```{python}
print((torch.tensor(Lambda_rot) ** 2).sum(dim = 0).sum(), psi_l0_interp.sum())
```


```{python}
pve_rot = plot_pve(
    Lambda_list_interp,
    view_names=view_names,
    rotate=True,
    title="PVE per factor — SupMultiviewShared (varimax-rotated)",
)
```

### R² per factor

```{python}
r2 = plot_r2(
    X_list_interp, Z_interp, Lambda_list_interp,
    view_names=view_names,
    title="R² per factor — SupMultiviewShared",
)
r2
```

### Factor loadings heatmap

```{python}
Lambda_rot_list = plot_factor_loadings(
    Lambda_list_interp,
    view_names=view_names,
    rotate=True,
    title="Factor loadings — SupMultiviewShared (varimax-rotated)",
)
```

### Factor score scatter plots

```{python}
plot_factor_scores_2d(
    Z_interp, y=y_interp,
    top_factors=top_factors_interp,
    n_factors=5,
    y_label="outcome",
    title="Factor score scatterplot matrix (coloured by outcome)\nTop active factors",
)
```

### Outcome vs. factor score

```{python}
plot_factor_outcome(
    Z_interp, y_interp,
    top_factors=top_factors_interp,
    n_factors_show=5,
    outcome_label="outcome",
    title="Outcome along samples ranked by factor score — top active factors",
)
```


```{python}
_loc_beta = pyro.param('loc_beta').detach().cpu().double()
est_betas = pd.DataFrame({
        'beta': _loc_beta,
        'beta_rot': torch.from_numpy(R_varimax).double().T @ _loc_beta,
        'factor': range(0, len(_loc_beta))
        }
        ).melt(id_vars = ['factor'], var_name = "type")
```

```{python}
g = sns.catplot(
    data = est_betas,
    kind = "bar",
    x = "factor",
    y = "value",
    hue = "type",
)
g.fig.suptitle("Posterior mean beta_k before and after rotation by varimax")
```

### Top features per factor

```{python}
top_feature_tables = tabulate_top_features(
    Lambda_list_interp,
    n_top_factors=min(8, K_FIT),
    n_top_features=10,
    rotate=True,
)
for l, tbl in enumerate(top_feature_tables):
    print(f"\nView {l} — top features per factor (by |loading|, varimax-rotated):")
    display(tbl)
```


## Convergence criterion comparison — SupMultiviewShared

Compare the three convergence criteria on the same shared-factor data and model.
Global training varies by criterion; local inference always uses `elbo_min` so
that only the stopping rule differs.

```{python}
#| label: scc-setup
import importlib, time
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

for _mod in ("multiview_shared", "handler", "run_methods"):
    if _mod in sys.modules:
        importlib.reload(sys.modules[_mod])

from multiview_shared import SupMultiviewShared
from handler import ModelHandler
from run_methods import train_model_locally_shared, evaluate_fitted_model_shared
from pyro.optim import AdagradRMSProp
from pyro.infer import Trace_ELBO

# ── shared hyperparameters (mirror the train_config already in scope) ──────
SCC_MIN_EPOCHS     = train_config["min_epochs"]
SCC_NUM_EPOCHS     = train_config["max_epochs"]
SCC_MINIBATCH_SIZE = train_config["minibatch_size"]
SCC_N_PARTICLES    = train_config["num_particles"]
SCC_ETA            = train_config["eta"]
SCC_DELTA          = train_config["delta"]
SCC_T              = train_config["t"]

# elbo_snr settings
SCC_WINDOW         = 50
SCC_SNR_THRESHOLD  = 0.1

# grad_norm settings
SCC_GRAD_NORM_TOL  = 1e-3

SCC_N_POST_SAMPLES = 200
```

```{python}
#| label: scc-runner
def run_shared_criterion(criterion):
    """Global train + local inference for SupMultiviewShared under one criterion."""
    pyro.clear_param_store()

    model = SupMultiviewShared(K_FIT, dense=False, device=DEVICE)
    opt   = AdagradRMSProp({"eta": SCC_ETA, "delta": SCC_DELTA, "t": SCC_T})
    loss  = Trace_ELBO(num_particles=SCC_N_PARTICLES)
    handler = ModelHandler("train", model, opt=opt, loss=loss, device=DEVICE)

    t0 = time.time()
    handler.do_inference(
        train_dataset=train_subset,
        min_epochs=SCC_MIN_EPOCHS,
        epochs=SCC_NUM_EPOCHS,
        minibatch_flag=True,
        minibatch_size=SCC_MINIBATCH_SIZE,
        convergence_criterion=criterion,
        window=SCC_WINDOW,
        snr_threshold=SCC_SNR_THRESHOLD,
        grad_norm_tol=SCC_GRAD_NORM_TOL,
        verbose=True,
    )
    elapsed_global = time.time() - t0
    global_state = {"inference_time": elapsed_global, "epochs": model.total_epochs}

    # Local inference uses the standard elbo_min stopping rule
    _, local_handler, local_state = train_model_locally_shared(
        model, train_config, test_subset, opt="adagrad", verbose=False,
        device=DEVICE,
    )

    eval_table, _ = evaluate_fitted_model_shared(
        rep_config, data_package,
        handler, local_handler,
        global_state, local_state,
        N_POSTERIOR_SAMPLES=SCC_N_POST_SAMPLES,
        metric_out_filename="/tmp/scc_eval",
    )

    print(f"[{criterion}]  global epochs={model.total_epochs}  time={elapsed_global:.1f}s")
    return {
        "criterion":    criterion,
        "epochs":       model.total_epochs,
        "elapsed":      elapsed_global,
        "loss_history": model.loss_history,
        "var_history":  model.var_param_convergence_history,
        "eval_table":   eval_table,
    }
```

```{python}
#| label: scc-run
scc_results = {}
for _criterion in ["grad_norm"]: #"elbo_min", "elbo_snr", "grad_norm"]:
    scc_results[_criterion] = run_shared_criterion(_criterion)
```

```{python}
#| label: scc-elbo-plot
_scc_palette = {"elbo_min": "steelblue", "elbo_snr": "darkorange", "grad_norm": "seagreen"}
_n_train_shared = train_subset.__len__()

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for criterion, res in scc_results.items():
    hist   = np.array(res["loss_history"]) / _n_train_shared
    epochs = np.arange(1, len(hist) + 1)
    color  = _scc_palette[criterion]
    axes[0].plot(epochs, hist, label=criterion, color=color, alpha=0.85)
    axes[1].plot(epochs, hist, label=criterion, color=color, alpha=0.85)

axes[0].set_title("Neg-ELBO per datum — full history")
axes[1].set_title("Neg-ELBO per datum — first 200 epochs")
axes[1].set_xlim(0, 200)
for ax in axes:
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Neg-ELBO / n")
    ax.legend()
plt.tight_layout()
plt.show()
```

```{python}
#| label: scc-summary
_scc_rows = []
for criterion, res in scc_results.items():
    tbl = res["eval_table"]
    row = {
        "criterion": criterion,
        "epochs":    res["epochs"],
        "time_s":    round(res["elapsed"], 1),
        "joint_rse": tbl["joint_rse"].mean(),
        "test_rse":  tbl["test_rse"].mean()  if "test_rse"  in tbl.columns else float("nan"),
        "outcome_mse":            tbl["outcome_mse"].iloc[0],
        "outcome_95p_coverage":   tbl["outcome_95p_coverage"].iloc[0],
        "joint_95p_coverage":     tbl["joint_95p_coverage"].mean(),
    }
    _scc_rows.append(row)

scc_summary = pd.DataFrame(_scc_rows).set_index("criterion")
scc_summary
```

```{python}
#| label: scc-metric-plot
_scc_metric_cols = [c for c in scc_summary.columns if c not in ("epochs", "time_s")]
fig, axes = plt.subplots(1, len(_scc_metric_cols) + 2,
                          figsize=(4 * (len(_scc_metric_cols) + 2), 4))

for ax, col, label in zip(axes[:2],
                           ["epochs", "time_s"],
                           ["Epochs to convergence", "Wall-clock time (s)"]):
    ax.bar(scc_summary.index, scc_summary[col],
           color=[_scc_palette[c] for c in scc_summary.index])
    ax.set_title(label)
    ax.set_ylabel(label)
    ax.tick_params(axis="x", rotation=15)

for ax, col in zip(axes[2:], _scc_metric_cols):
    ax.bar(scc_summary.index, scc_summary[col],
           color=[_scc_palette[c] for c in scc_summary.index])
    ax.set_title(col)
    ax.set_ylabel(col)
    ax.tick_params(axis="x", rotation=15)

plt.suptitle("SupMultiviewShared — convergence criterion comparison", y=1.02)
plt.tight_layout()
plt.show()
```

```{python}
#| label: scc-var-param-plot
fig, ax = plt.subplots(figsize=(8, 4))
for criterion, res in scc_results.items():
    hist = np.array(res["var_history"])
    ax.plot(np.arange(1, len(hist) + 1), hist,
            label=criterion, color=_scc_palette[criterion], alpha=0.85)
ax.set_xlabel("Epoch")
ax.set_ylabel("Mean param-norm change")
ax.set_title("SupMultiviewShared — variational parameter convergence history")
ax.legend()
plt.tight_layout()
plt.show()
```

## SVD initialisation

Compare zero initialisation against SVD-based initialisation, holding
`train_config` and data fixed. Using `k=K_TRUE` (no over-specification) to
isolate the effect of initialisation from k_delta instability.



```{python}
X_l_list = [t for t in train_subset.tensors[1:-1]]
svd_init_shared(X_l_list, 15)
```

```{python}
#| label: svd-init-config

model_config_svd = {**model_config, "k": K_FIT, "dense_model": False}
```

```{python}
#| label: svd-init-default
pyro.clear_param_store()
t0 = time.time()
m_default, h_default, gs_default = train_model_shared(
    model_config_svd, train_config, train_subset,
    model_out_filename="", opt="adagrad", verbose=False, write=False,
    device=DEVICE, svd_init=False,
)
t_default = time.time() - t0
print(f"Default init — epochs: {m_default.total_epochs}  time: {t_default:.1f}s")
```

```{python}
#| label: svd-init-svd
pyro.clear_param_store()
t0 = time.time()
m_svd, h_svd, gs_svd = train_model_shared(
    model_config_svd, train_config, train_subset,
    model_out_filename="", opt="adagrad", verbose=False, write=False,
    device=DEVICE, svd_init=True,
)
t_svd = time.time() - t0
print(f"SVD init     — epochs: {m_svd.total_epochs}  time: {t_svd:.1f}s")
```

```{python}
#| label: svd-init-eval
def _eval(m, h_train, gs_train):
    _, h_test, ls_test = train_model_locally_shared(
        m, train_config, test_subset, opt="adagrad", verbose=False, device=DEVICE,
    )
    tbl, _, _, _ = evaluate_fitted_model_shared(
        {**rep_config, "k_delta": 0}, data_package,
        h_train, h_test, gs_train, ls_test,
        N_POSTERIOR_SAMPLES=300, metric_out_filename="",
    )
    return tbl[["outcome_mse", "joint_rse", "test_rse"]]

metrics_default_svd = _eval(m_default, h_default, gs_default)
metrics_svd_svd     = _eval(m_svd,     h_svd,     gs_svd)
```

```{python}
#| label: svd-init-summary
n_train = len(train_subset)
pd.DataFrame([
    {"init": "default", "epochs": m_default.total_epochs, "time_s": round(t_default, 1),
     **metrics_default_svd.iloc[0].to_dict()},
    {"init": "svd",     "epochs": m_svd.total_epochs,     "time_s": round(t_svd, 1),
     **metrics_svd_svd.iloc[0].to_dict()},
])
```

```{python}
#| label: svd-init-loss
fig, ax = plt.subplots(figsize=(7, 3))
ax.plot([l / n_train for l in m_default.loss_history], label="default", alpha=0.8)
ax.plot([l / n_train for l in m_svd.loss_history],     label="SVD",     alpha=0.8)
ax.set_xlabel("Epoch")
ax.set_ylabel("Neg-ELBO per datum")
ax.legend()
ax.set_title(f"SVD vs default init  (N={rep_config['n']}, P={rep_config['p_l']}, K={K_TRUE})")
plt.tight_layout()
plt.show()
```

## Cross-validation for hyperparameter selection

```{python}
import itertools
importlib.reload(sys.modules["run_methods"])
from run_methods import run_cv_grid_shared
from data_utils import zero_variance_col_filter, extract_sim_decomp_shared
```

```{python}
# Pre-filter each view using the full dataset to remove zero-variance columns.
# Normalisation is deferred to inside each fold so there is no cross-fold leakage.
X_l_raw    = sim_data["X_l"]
y_cv_raw   = sim_data["y"].squeeze()

cv_col_filters = [zero_variance_col_filter(X) for X in X_l_raw]
X_l_cv_raw     = [X[:, f] for X, f in zip(X_l_raw, cv_col_filters)]

# Simulation truth used for the covariance reconstruction (cov_frob) metric.
cv_sim_decomp = extract_sim_decomp_shared(sim_data)

print(f"CV data: {X_l_cv_raw[0].shape[0]} observations")
for l, X in enumerate(X_l_cv_raw):
    print(f"  View {l}: {X.shape[1]} features (after zero-var filter)")
```

```{python}
cv_model_config = {"k": K_FIT, "dense_model": False}

N_CV_FOLDS             = 5
CV_SEED                = 42
N_CV_POSTERIOR_SAMPLES = 10
```

```{python}
# ---------------------------------------------------------------------------
# AdagradRMSProp hyperparameter grid
# ---------------------------------------------------------------------------
eta_cv_array              = [0.1, 0.25, 0.5, 0.75, 1.0]
delta_cv_array            = [1e-16]
t_cv_array                = [0.1, 0.25, 0.5, 0.75, 1.0]
particle_cv_array         = [1, 2]
# Minibatch as a fraction of the fold training size. Each fold converts this
# to an absolute count, so comparisons are valid across different n.
minibatch_fraction_cv_array = [0.05, 0.1, 0.2, 0.5]
min_epoch_cv_array        = [100]
max_epoch_cv_array        = [500]
convergence_criterion_array = "elbo_snr",
window_array              = [50]
snr_threshold_array       = [1]

n_obs_cv         = X_l_cv_raw[0].shape[0]
n_train_per_fold = int(n_obs_cv * (N_CV_FOLDS - 1) / N_CV_FOLDS)
print(f"Per-fold training size: {n_train_per_fold}")
print(f"Minibatch fraction grid: {minibatch_fraction_cv_array}")
print(f"  -> absolute sizes at fold scale: "
      f"{[max(1, int(n_train_per_fold * f)) for f in minibatch_fraction_cv_array]}")

cv_train_grid_names = (
    "eta", "delta", "t",
    "num_particles", "minibatch_fraction", "min_epochs", "max_epochs",
    "convergence_criterion", "window", "snr_threshold"
)

cv_train_grid = list(itertools.product(
    eta_cv_array, delta_cv_array, t_cv_array,
    particle_cv_array, minibatch_fraction_cv_array, min_epoch_cv_array, max_epoch_cv_array,
    convergence_criterion_array, window_array, snr_threshold_array
))
print(f"{len(cv_train_grid)} hyperparameter configurations")
```

```{python}
cv_train_grid
```

```{python}
def select_best_config(cv_results, grid_names, metric="outcome_mse", lower_is_better=True):
    """Return (best_config dict, per-config mean metric Series) from a CV results DataFrame."""
    agg      = cv_results.groupby("config_idx")[metric].mean()
    best_idx = int(agg.idxmin() if lower_is_better else agg.idxmax())
    best_row = cv_results[cv_results["config_idx"] == best_idx].iloc[0]

    best_config = {}
    for k in grid_names:
        v = best_row[k]
        if isinstance(v, np.integer):
            v = int(v)
        elif isinstance(v, np.floating):
            v = float(v)
        best_config[k] = v
    return best_config, agg
```

```{python}
# n_workers=1  -> sequential, safe everywhere
# n_workers=N_CV_FOLDS -> all folds in parallel via joblib/loky
N_CV_WORKERS = N_CV_FOLDS

# Checkpoint flushes after every config completes. Set resume=False (or delete
# the file) to start from scratch; otherwise reruns pick up where they stopped.
CV_CHECKPOINT_PATH = (
    f"../sim/results/integration_shared/cv_results_"
    f"n{rep_config['n']}p{rep_config['p_l']}_"
    f"snr{rep_config['snr_x']}.{rep_config['snr_y']}_"
    f"sparse{rep_config['sparsity']}_rep{rep_config['rep']}_"
    f"kdelta{K_DELTA}.csv"
)

cv_results_shared = run_cv_grid_shared(
    X_l_cv_raw, y_cv_raw,
    model_config=cv_model_config,
    train_grid=cv_train_grid,
    train_grid_names=cv_train_grid_names,
    n_folds=N_CV_FOLDS,
    seed=CV_SEED,
    n_posterior_samples=N_CV_POSTERIOR_SAMPLES,
    opt="adagrad",
    n_workers=N_CV_WORKERS,
    sim_decomp=cv_sim_decomp,
    column_filters=cv_col_filters,
    checkpoint_path=CV_CHECKPOINT_PATH,
    resume=True,
)
```

```{python}
cv_results_shared
```

```{python}
cv1 = pd.read_csv("/Users/jonathanhori/multiomic_integration/sim/results/integration_shared/cv_results_n500p1000_snr2.2_sparse0.25_rep1_kdelta10_minibatch32-64.csv")
cv2 = pd.read_csv("/Users/jonathanhori/multiomic_integration/sim/results/integration_shared/cv_results_n500p1000_snr2.2_sparse0.25_rep1_kdelta10_minibatch128-256.csv")
```

```{python}
cv_results_shared = pd.concat([cv1, cv2], ignore_index=True)
```

```{python}
cv_results_shared.loc[(cv_results_shared.effective_minibatch_size == 128) & 
(cv_results_shared.num_particles == 1) & 
(cv_results_shared.t == 0.25) & 
(cv_results_shared.eta == 0.25)]
```

```{python}
cv_results_shared.columns
```

```{python}
# Mean outcome MSE, covariance reconstruction, and training time per config,
# sorted by MSE.
cv_summary_cols = [
    "outcome_mse", "cov_frob",
    "train_time", "local_time", "total_time",
    "epochs", "local_epochs"
]
cv_summary_cols = [c for c in cv_summary_cols if c in cv_results_shared.columns]
cv_summary_shared = (
    cv_results_shared
    .groupby("config_idx")[cv_summary_cols]
    .mean()
    .sort_values("outcome_mse")
)
cv_summary_shared.head(10)
```

```{python}
best_train_config_shared, config_mse_agg_shared = select_best_config(
    cv_results_shared, cv_train_grid_names, metric="outcome_mse"
)
print("Best optimizer config (lowest mean CV outcome MSE):")
for k, v in best_train_config_shared.items():
    print(f"  {k}: {v}")
print(f"\nMean CV outcome MSE: {config_mse_agg_shared.min():.4f}")

if "cov_frob" in cv_results_shared.columns:
    best_train_config_cov, config_cov_agg_shared = select_best_config(
        cv_results_shared, cv_train_grid_names, metric="cov_frob"
    )
    print("\nBest optimizer config (lowest mean CV cov_frob):")
    for k, v in best_train_config_cov.items():
        print(f"  {k}: {v}")
    print(f"\nMean CV cov_frob: {config_cov_agg_shared.min():.4f}")
```

```{python}
# ---------------------------------------------------------------------------
# Multi-metric comparison: rank aggregation across MSE, cov_frob, train time
# ---------------------------------------------------------------------------
# Each metric is ranked independently (rank 1 = best). Mean rank across all
# available metrics gives a single "combined rank" that is scale-invariant and
# robust to outliers in any one metric.

_cv_quality_metrics = [c for c in ["outcome_mse", "cov_frob", "total_time"]
                       if c in cv_results_shared.columns]

cv_multi_summary = (
    cv_results_shared
    # .loc[(cv_results_shared.num_particles == 1)]
    .groupby(["config_idx"])[_cv_quality_metrics] # , "num_particles"
    .mean()
)

# Per-metric ranks (lower value = rank 1)
for col in _cv_quality_metrics:
    cv_multi_summary[f"rank_{col}"] = cv_multi_summary[col].rank()

rank_cols = [f"rank_{c}" for c in _cv_quality_metrics]
cv_multi_summary["mean_rank"] = cv_multi_summary[rank_cols].mean(axis=1)
cv_multi_summary = cv_multi_summary.sort_values("mean_rank")

print(f"Multi-metric ranking across: {_cv_quality_metrics}")
cv_multi_summary[_cv_quality_metrics + ["mean_rank"] + rank_cols].head(15)
```

```{python}
cv_multi_summary = cv_multi_summary.reset_index(level='num_particles')
```


```{python}
cv_multi_summary
```

```{python}
cv_multi_summary.config_idx
```

```{python}
cv_multi_summary.reset_index().loc[cv_multi_summary.reset_index().config_idx == 24]
```

```{python}
# Top 5 configs by combined rank
for rank_pos, config_idx in enumerate(cv_multi_summary.index[:5], start=1):
    config_idx = int(config_idx)
    row = cv_results_shared[cv_results_shared["config_idx"] == config_idx].iloc[0]
    mean_rank = cv_multi_summary.loc[config_idx, "mean_rank"]
    print(f"--- Rank {rank_pos}  (config_idx={config_idx}, mean_rank={mean_rank:.2f}) ---")
    for k in cv_train_grid_names:
        print(f"  {k}: {row[k]}")
    for m in _cv_quality_metrics:
        print(f"  mean {m}: {cv_multi_summary.loc[config_idx, m]:.4f}")
    print()
```

```{python}
# Scatter of the two quality metrics (outcome_mse vs cov_frob) with training
# time as dot size and combined rank as colour.  Top-10 by mean rank are
# labelled with their config_idx.
_top_n_label = 10

if "cov_frob" in cv_multi_summary.columns and "outcome_mse" in cv_multi_summary.columns:
    _plot_df = cv_multi_summary.reset_index().copy()
    _size_col = "total_time" if "total_time" in _plot_df.columns else None

    fig, ax = plt.subplots(figsize=(8, 6))
    sc = ax.scatter(
        _plot_df["outcome_mse"],
        _plot_df["cov_frob"],
        c=_plot_df["mean_rank"],
        s=(_plot_df[_size_col] / _plot_df[_size_col].max() * 300 + 20
           if _size_col else 60),
        cmap="viridis_r",
        alpha=0.75,
        edgecolors="grey",
        linewidths=0.4,
    )
    plt.colorbar(sc, ax=ax, label="Mean rank (lower = better overall)")

    for _, row in _plot_df.head(_top_n_label).iterrows():
        ax.annotate(
            str(int(row["config_idx"])),
            (row["outcome_mse"], row["cov_frob"]),
            fontsize=7, ha="left", va="bottom",
            xytext=(3, 3), textcoords="offset points",
        )

    ax.set_xlabel("CV outcome MSE")
    ax.set_ylabel("CV cov_frob")
    if _size_col:
        ax.set_title("MSE vs cov_frob  (dot size ∝ train time, colour = combined rank)")
    else:
        ax.set_title("MSE vs cov_frob  (colour = combined rank)")
    plt.tight_layout()
    plt.show()
```

```{python}
# Boxplot of outcome MSE for the top configs
top_n = 10
top_config_ids = cv_multi_summary.head(top_n).index.tolist()
top_cv = cv_results_shared[cv_results_shared["config_idx"].isin(top_config_ids)].copy()
top_cv["config_label"] = (
    "eta="   + top_cv["eta"].astype(str)
    + " t="  + top_cv["t"].astype(str)
    + " mbf=" + top_cv["minibatch_fraction"].astype(str)
)
label_order = (
    top_cv.groupby("config_label")["outcome_mse"].mean()
    .sort_values().index.tolist()
)

fig, ax = plt.subplots()
sns.boxplot(data=top_cv, x="outcome_mse", y="config_label", order=label_order, ax=ax)
ax.set_title(f"CV outcome MSE — top {top_n} configs by combined rank")
ax.set_xlabel("Outcome MSE (standardised y)")
ax.set_ylabel("")
plt.tight_layout()
plt.show()
```



```{python}
# select_best_config(
#     cv_results_shared.loc[cv_results_shared.delta == 1e-16], 
#     cv_train_grid_names, 
#     metric="outcome_mse"
# )

cv_results_shared.loc[cv_results_shared.config_idx == 7]
```


## Hyperparam selection with Optuna

```{python}

for _mod in ("optuna_cv",):
    if _mod in sys.modules:
        importlib.reload(sys.modules[_mod])

from optuna_cv import run_optuna_study, pareto_dataframe

```

```{python}
optuna_param_space = {
    # --- tuned (continuous, log scale) ---
    "eta":                {"type": "float",  "low": 0.001, "high": 1.0,  "log": True},
    "t":                  {"type": "float",  "low": 0.01,  "high": 1.0,  "log": True},
    "snr_threshold":      {"type": "float",  "low": 0.1,  "high": 10.0,  "log": True},
    # fraction of fold training size; converted to abs count inside each fold
    "minibatch_fraction": {"type": "float",  "low": 0.05, "high": 0.5,  "log": True},
    # --- tuned (discrete) ---
    # --- fixed ---
    "num_particles":      {"type": "fixed",  "value": 1},
    "delta":              {"type": "fixed",  "value": 1e-16},
    "min_epochs":         {"type": "fixed",  "value": 200},
    "max_epochs":         {"type": "fixed",  "value": 500},
    "convergence_criterion": {"type": "fixed", "value": "elbo_snr"},
    "window":             {"type": "fixed",  "value": 50},
}
```

```{python}
study, labels = run_optuna_study(
    X_l_cv_raw, y_cv_raw,
    model_config=cv_model_config,
    param_space=optuna_param_space,
    sim_decomp=cv_sim_decomp,
    column_filters=cv_col_filters,
    n_trials=50,
    n_folds=N_CV_FOLDS,
    seed=CV_SEED,
    n_posterior_samples=N_CV_POSTERIOR_SAMPLES,
    storage="sqlite:///optuna_cv_shared.db",
    study_name="shared_cv_run2",
)
pareto_dataframe(study, labels)
```


```{python}
pareto_df = pareto_dataframe(study, labels)
for col in ["outcome_mse", "cov_frob", "train_time"]:
    pareto_df[f"{col}_norm"] = (pareto_df[col] - pareto_df[col].min()) / (pareto_df[col].max() - pareto_df[col].min())

norm_cols = [c for c in pareto_df.columns if c.endswith("_norm")]
pareto_df["dist_from_ideal"] = pareto_df[norm_cols].pow(2).sum(axis=1).pow(0.5)
best = pareto_df.sort_values("dist_from_ideal").iloc[0]

```


```{python}
pareto_df.sort_values("dist_from_ideal")#.iloc[0:5]
```

# Convergence criterion comparison

Compare the three convergence criteria on the same dataset and model.
Each criterion is run with a fresh model and identical hyperparameters; we record
ELBO history, epochs to convergence, wall-clock time, and held-out metrics.

```{python}
#| label: conv-criterion-setup
import importlib, copy, time
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import seaborn as sns
import pyro
from pyro.optim import ClippedAdam
from pyro.infer import Trace_ELBO

importlib.reload(sys.modules["model"])
importlib.reload(sys.modules["handler"])
from model import SupMultiviewDecomp
from handler import ModelHandler
from data_utils import calc_all_structures_with_rescaling, extract_sim_decomp, eval_performance
from constants import Sites

# ── shared hyperparameters ─────────────────────────────────────────────────
CC_MIN_EPOCHS       = 50
CC_NUM_EPOCHS       = 1000
CC_MINIBATCH_SIZE   = 32
CC_LR               = 0.001
CC_GAMMA            = 0.1
CC_LRD              = CC_GAMMA ** (1 / (CC_NUM_EPOCHS * CC_MINIBATCH_SIZE))
CC_N_POST_SAMPLES   = 200

# elbo_snr settings
CC_WINDOW           = 50
CC_SNR_THRESHOLD    = 0.1

# grad_norm settings
CC_GRAD_NORM_TOL    = 1e-3

# sites for posterior prediction
_L = int(sim_data_multiview_torch.get("L"))
_sites = (
    [Sites.joint_structure_l.format(l=l) for l in range(_L)]
    + [Sites.view_structure_l.format(l=l) for l in range(_L)]
    + [Sites.Z]
    + [Sites.Phi_l.format(l=l) for l in range(_L)]
)
_outcome_sites = ["y"]

# ground-truth decomp filtered to training rows
_sim_decomp = extract_sim_decomp(sim_data_multiview_torch)
_train_sim_decomp = {k: v for k, v in _sim_decomp.items()}
_train_sim_decomp["SIM_Z"]              = _train_sim_decomp["SIM_Z"][train_idx, :]
_train_sim_decomp["SIM_Phi_l_list"]     = [Phi[train_idx, :] for Phi in _train_sim_decomp["SIM_Phi_l_perp_list"]]
_train_sim_decomp["SIM_Phi_l_perp_list"]= [Phi[train_idx, :] for Phi in _train_sim_decomp["SIM_Phi_l_perp_list"]]
```

```{python}
#| label: conv-criterion-runner
def run_criterion(criterion, **criterion_kwargs):
    """Train SupMultiviewDecomp with the given convergence criterion and return results."""
    pyro.clear_param_store()

    model = SupMultiviewDecomp(
        k_upper, k_l_upper,
        ortho_penalty=0.0,
        include_view_factors=True,
        dense=False,
    )
    opt = ClippedAdam({"lr": CC_LR, "lrd": CC_LRD, "betas": (0.95, 0.999)})
    handler = ModelHandler("train", model, opt=opt, loss=Trace_ELBO(num_particles=2))

    t0 = time.time()
    handler.do_inference(
        train_dataset=train_subset,
        min_epochs=CC_MIN_EPOCHS,
        epochs=CC_NUM_EPOCHS,
        minibatch_flag=True,
        minibatch_size=CC_MINIBATCH_SIZE,
        convergence_criterion=criterion,
        window=CC_WINDOW,
        snr_threshold=CC_SNR_THRESHOLD,
        grad_norm_tol=CC_GRAD_NORM_TOL,
        verbose=False,
        **criterion_kwargs,
    )
    elapsed = time.time() - t0

    post_samples   = handler.predict(train_X_l_list_clean, CC_N_POST_SAMPLES, _sites)
    post_samples_y = handler.predict(test_X_l_list_clean,  CC_N_POST_SAMPLES, _outcome_sites)

    eval_structs = calc_all_structures_with_rescaling(
        _L,
        X_l_list_column_filters,
        X_l_mean_list,
        X_l_sd_list,
        post_samples,
        post_samples_y,
        _train_sim_decomp,
        test_y_clean.squeeze(),
    )
    metrics = eval_performance(**eval_structs)

    print(f"[{criterion}]  epochs={model.total_epochs}  time={elapsed:.1f}s")
    return {
        "criterion":        criterion,
        "epochs":           model.total_epochs,
        "elapsed":          elapsed,
        "loss_history":     model.loss_history,
        "var_history":      model.var_param_convergence_history,
        "metrics":          metrics,
    }
```

```{python}
#| label: conv-criterion-run
cc_results = {}
for _criterion in ["elbo_min", "elbo_snr", "grad_norm"]:
    cc_results[_criterion] = run_criterion(_criterion)
```

```{python}
#| label: conv-criterion-elbo-plot
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

_palette = {"elbo_min": "steelblue", "elbo_snr": "darkorange", "grad_norm": "seagreen"}
_n_train = train_subset.__len__()

for criterion, res in cc_results.items():
    hist = np.array(res["loss_history"]) / _n_train
    epochs = np.arange(1, len(hist) + 1)
    color = _palette[criterion]
    axes[0].plot(epochs, hist, label=criterion, color=color, alpha=0.85)
    axes[1].plot(epochs, hist, label=criterion, color=color, alpha=0.85)

axes[0].set_title("Neg-ELBO per datum — full history")
axes[1].set_title("Neg-ELBO per datum — first 200 epochs")
axes[1].set_xlim(0, 200)

for ax in axes:
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Neg-ELBO / n")
    ax.legend()

plt.tight_layout()
plt.show()
```

```{python}
#| label: conv-criterion-summary
# Wall-clock time and epoch counts
_summary_rows = []
for criterion, res in cc_results.items():
    row = {"criterion": criterion, "epochs": res["epochs"], "time_s": round(res["elapsed"], 1)}
    # flatten metric columns
    for col in res["metrics"].columns:
        row[col] = res["metrics"][col].iloc[0] if len(res["metrics"]) == 1 else res["metrics"][col].mean()
    _summary_rows.append(row)

cc_summary = pd.DataFrame(_summary_rows).set_index("criterion")
cc_summary
```

```{python}
#| label: conv-criterion-metric-plot
_metric_cols = [c for c in cc_summary.columns if c not in ("epochs", "time_s")]

fig, axes = plt.subplots(1, len(_metric_cols) + 2, figsize=(4 * (len(_metric_cols) + 2), 4))

# epochs and time
for ax, col, label in zip(axes[:2], ["epochs", "time_s"], ["Epochs to convergence", "Wall-clock time (s)"]):
    ax.bar(cc_summary.index, cc_summary[col],
           color=[_palette[c] for c in cc_summary.index])
    ax.set_title(label)
    ax.set_ylabel(label)
    ax.set_xlabel("")
    ax.tick_params(axis="x", rotation=15)

# performance metrics
for ax, col in zip(axes[2:], _metric_cols):
    ax.bar(cc_summary.index, cc_summary[col],
           color=[_palette[c] for c in cc_summary.index])
    ax.set_title(col)
    ax.set_ylabel(col)
    ax.set_xlabel("")
    ax.tick_params(axis="x", rotation=15)

plt.suptitle("Convergence criterion comparison", y=1.02)
plt.tight_layout()
plt.show()
```

```{python}
#| label: conv-criterion-var-param-plot
fig, ax = plt.subplots(figsize=(8, 4))
for criterion, res in cc_results.items():
    hist = np.array(res["var_history"])
    ax.plot(np.arange(1, len(hist) + 1), hist,
            label=criterion, color=_palette[criterion], alpha=0.85)
ax.set_xlabel("Epoch")
ax.set_ylabel("Mean param-norm change")
ax.set_title("Variational parameter convergence history")
ax.legend()
plt.tight_layout()
plt.show()
```
