---
jupyter: python3
---

```{python}
import os
import sys
```

```{python}
os.environ["R_HOME"] = "/Library/Frameworks/R.framework/Resources"
# r_home = "/Library/Frameworks/R.framework/Resources"
```

```{python}
os.environ["PATH"] = "/opt/homebrew/bin:" + os.environ["PATH"]
os.environ['PATH']
```

```{python}
import shutil
```

```{python}


import rpy2.robjects as robjects
from rpy2.robjects import r, vectors
from rpy2 import rinterface

import pandas as pd
import numpy as np
import seaborn as sns
import itertools

from rpy2.robjects import pandas2ri, default_converter, conversion

import torch
from torch.utils.data import TensorDataset
from torchvision import transforms
import pyro
import pyro.distributions as dist
from pyro.optim import Adam, ClippedAdam, AdagradRMSProp
from pyro.infer import SVI, Trace_ELBO, RBFSteinKernel

import importlib

# import sklearn
from sklearn.model_selection import train_test_split


from pathlib import Path
import time
```

```{python}
#| label: Insert path
sys.path.insert(1, "/Users/jonathanhori/multiomic_integration/python")
```

```{python}
#| label: Load data utils
# importlib.reload(sys.modules["data_utils"])

# from data_utils import floatmatrix_to_torch, r_to_torch, load_and_process_rds_data_for_condition, normalize_tensor_by_col, extract_est_decomp, extract_sim_decomp, calc_struct, scale_est_struct, scale_sim_struct, eval_rse, eval_mse, summarise_post_samples, summarise_structure_list, eval_post_coverage, eval_credible_interval, obtain_posterior_pred_samples, calc_all_structures_with_rescaling, eval_performance
from data_utils import r_to_torch, normalize_tensor_by_col, \
    zero_variance_col_filter, obtain_posterior_pred_samples, \
        calc_all_structures_with_rescaling, extract_sim_decomp, eval_performance, varimax, align_tensor_shapes, calc_cov, scale_sim_cov, summarise_post_samples, eval_post_coverage
```

```{python}
#| label: Load model objects
# importlib.reload(sys.modules["matrix_decomp"])
# importlib.reload(sys.modules["handler"])

from matrix_decomp import MatrixDecomp
from handler import ModelHandler
# from model import SupMultiviewDecomp, do_inference
```

```{python}
from constants import Params, Sites
```

# Load data

## Load single dataset for MatrixDecomp

```{python}
conversion._converter = None
conversion.set_conversion(default_converter)
readRDS = robjects.r['readRDS']

# sim_data = readRDS('~/multiomic_integration/sim/data/single_view/factor_data_n500p1000_snr2.2_sparse0.25.rds')
sim_data = readRDS('~/multiomic_integration/sim/data/single_view_withoutcome/k.5/factor_data_n500p100_snr2.2_sparse0.25.rds')
# sim_data = readRDS('~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/simple_data/factor_data_n2000p10000_snr2.2.rds')
        
```

```{python}
print(sim_data)
```

```{python}
conversion.set_conversion(default_converter)

sim_data_torch = {name: r_to_torch(sim_data.rx2(name)) for name in sim_data.names}

sim_data_torch
```

```{python}
sim_data_torch
```

```{python}
sns.heatmap(
    sim_data_torch.get('Lambda_l')[0],
    cmap="coolwarm"
)
```


### Extract single view data
```{python}
###
X = sim_data_torch["X_l"][0]
# col_filter = zero_variance_col_filter(X)

# X_summaries = normalize_tensor_by_col(X[:, col_filter])

# X_clean = X_summaries['data_clean']

###
y = sim_data_torch.get("y")
y

# y_mean = torch.mean(y)
# y_std = torch.std(y)
# y_clean = (y - y_mean) / y_std

k = int(sim_data_torch["K"].item())
n = X.shape[0]
```

```{python}
print(X.shape)
print(k)
print(n)
```

Without outcome
```{python}
train_subset = TensorDataset(torch.arange(X_clean.shape[0]), 
                                         X_clean)
```

With outcome
```{python}
train_subset = TensorDataset(torch.arange(X_clean.shape[0]), 
                                         X_clean,
                                         y_clean.squeeze())
```

### New single view data with train/test split

```{python}
TRAINING_SPLIT = True

TRAINING_SIZE = 0.8
RANDOM_SEED = 123
# Perform train/test split if necessary
if TRAINING_SPLIT:
    train_idx, test_idx = train_test_split(
        torch.arange(X.shape[0]),
        train_size = TRAINING_SIZE,
        random_state = RANDOM_SEED,
        shuffle = True
    )
    train_X = X[train_idx, :]
    test_X = X[test_idx, :]
    
    train_y = y[train_idx]
    test_y = y[test_idx]
else:
    train_idx = torch.arange(n)
    test_idx = torch.arange(n)
    
    train_X = X
    test_X = X
    
    train_y = y
    test_y = train_y

# Clean: remove 0 variance columns and standardize. Using Training data            
col_filter = zero_variance_col_filter(X)

train_X = train_X[:, col_filter]
test_X = test_X[:, col_filter]

train_X_summaries = normalize_tensor_by_col(train_X)
X_mean = train_X_summaries['means']
X_sd = train_X_summaries['sds']

test_X_summaries = normalize_tensor_by_col(test_X, X_mean, X_sd)

train_X_clean = train_X_summaries['data_clean']
test_X_clean = test_X_summaries['data_clean']

y_mean = torch.mean(train_y)
y_std = torch.std(train_y)

train_y_clean = (train_y - y_mean) / y_std
test_y_clean = (test_y - y_mean) / y_std
```

```{python}
train_subset = TensorDataset(torch.arange(train_X_clean.shape[0]), 
                                         train_X_clean,
                                         train_y_clean.squeeze())
test_subset = TensorDataset(torch.arange(test_X_clean.shape[0]), 
                                         test_X_clean,
                                         test_y_clean.squeeze())
```


# Load data into model to visualize

```{python}
import importlib
```



```{python}
sim_data_torch["X_l"][0]
```

```{python}
X_l_tensor = torch.utils.data.TensorDataset(sim_data_torch["X_l"][0])
loader = torch.utils.data.DataLoader(X_l_tensor, batch_size = len(X_l_tensor))
one_batch, = next(iter(loader))
one_batch.shape
```

## Visualize model structure


```{python}
factor_model = MatrixDecomp(k)
factor_model.n = X_clean.shape[0]
pyro.render_model(
    factor_model, #bayesian_factor_model, 
    model_args = (X_clean,
                  torch.arange(X_clean.shape[0]),
                  y_clean
    ),
    render_distributions=True, 
    render_params=True,
    render_deterministic = True)
```

Check trace for data dimensions

```{python}

loader = torch.utils.data.DataLoader(train_subset, batch_size = train_subset.__len__())
one_batch = next(iter(loader))


factor_model = MatrixDecomp(
        int(k),
        dense = True,
        supervised = True
    )
# factor_model.n = train_subset.__len__()

trace = pyro.poutine.trace(
    factor_model
    ).get_trace(
        one_batch[1],
        one_batch[0],
        one_batch[2])
        # X_clean,
        # torch.arange(X_clean.shape[0]))

trace.compute_log_prob() # optional, but allows printing of log_prob shapes

print(trace.format_shapes())
```

```{python}

loader = torch.utils.data.DataLoader(train_subset, batch_size = train_subset.__len__())
one_batch = next(iter(loader))


trace = pyro.poutine.trace(
    factor_model
    ).get_trace(
        one_batch[1],
        one_batch[0],
        one_batch[2])
        # X_clean,
        # torch.arange(X_clean.shape[0]))

trace.compute_log_prob() # optional, but allows printing of log_prob shapes

print(trace.format_shapes())
```



# Run model

## Run model: with minibatching

### MatrixDecomp


WITH LEARNING RATE SCHEDULER
```{python}
pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.1
opt_args = {"lr": initial_lr, "betas": (0.9, 0.999)}
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

scheduler_args = {
    'optimizer': torch.optim.Adam, 
    'optim_args': opt_args,
    'step_size': 20,
    'gamma': 0.9,
    'verbose': True
}
scheduler = pyro.optim.StepLR(scheduler_args)

factor_model = MatrixDecomp(
    k_upper,
    supervised = True, 
    dense = False)
train_handler = ModelHandler(
    "train", 
    factor_model, 
    # OPT, 
    loss = LOSS,
    opt_scheduler = scheduler,
    orthogonal_projection = False)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference_type = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 200,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


WITH ADAGRAD

```{python}
pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
# initial_lr = 0.1
opt_args = {"eta": 1.0, "delta": 1e-16, "t": 0.1}
OPT = AdagradRMSProp({
    "eta": opt_args['eta'], 
    "delta": opt_args['delta'], 
    "t": opt_args['t']})
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

# scheduler_args = {
#     'optimizer': torch.optim.Adam, 
#     'optim_args': opt_args,
#     'step_size': 20,
#     'gamma': 0.9,
#     'verbose': True
# }
# scheduler = pyro.optim.StepLR(scheduler_args)

factor_model = MatrixDecomp(
    k_upper,
    supervised = True, 
    dense = False)
train_handler = ModelHandler(
    "train", 
    factor_model, 
    opt = OPT, 
    loss = LOSS,
    opt_scheduler = None,
    orthogonal_projection = False)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference_type = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 200,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")


```

```{python}
pyro.param('loc_beta')
```
### With initial values for Lambda and Z locations set by PCA

```{python}
pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
opt_args = {"lr": initial_lr, "betas": (0.9, 0.999)}
# initial_lr = 0.005 
# gamma = 0.1  # final learning rate will be gamma * initial_lr
# lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))
# OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd, "betas": (0.95, 0.999)})
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

scheduler_args = {
    'optimizer': torch.optim.Adam, 
    'optim_args': opt_args,
    'step_size': 20,
    'gamma': 0.9,
    'verbose': True
}
scheduler = pyro.optim.StepLR(scheduler_args)

X_pca = torch.pca_lowrank(X_clean, q = k_upper)
scores_init = X_pca[0] @ torch.diag(X_pca[1])
loadings_init = X_pca[2]

factor_model = MatrixDecomp(
    k_upper,
    supervised = True, 
    dense = True,
    scores_init = scores_init,
    loadings_init = loadings_init)
train_handler = ModelHandler(
    "train", 
    factor_model, 
    # OPT, 
    loss = LOSS,
    opt_scheduler = scheduler,
    orthogonal_projection = False)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference_type = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 100,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


OLD
```{python}
pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.005 
gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))
OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd, "betas": (0.95, 0.999)})
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

factor_model = MatrixDecomp(k_upper)
train_handler = ModelHandler("train", factor_model, OPT, LOSS)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 30,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


## Run model with loading target


```{python}
# TARGET = sim_data_torch.get('Lambda_l')[0][col_filter, :]
```
```{python}
pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.005 
gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))
OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd, "betas": (0.95, 0.999)})
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10
TARGET = sim_data_torch.get('Lambda_l')[0][col_filter, :]

factor_model = MatrixDecomp(k_upper, 
                            loading_target = TARGET)
train_handler = ModelHandler("train", factor_model, OPT, LOSS)

t0 = time.time()
svi = train_handler.do_inference(
    train_dataset = train_subset,
    inference = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 30,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```


# Plot loss
```{python}
p = sns.relplot(
    data = factor_model.loss_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Negative ELBO")
p.fig.suptitle("Minibatch loss per epoch")
# factor_model.loss_history
```

```{python}
p = sns.relplot(
    data = factor_model.var_param_convergence_history,
    kind = "line"
)
p.set_axis_labels("Epochs", "Norm difference")
p.fig.suptitle("Variational parameter convergence per epoch")
# factor_model.loss_history
```

```{python}
factor_model.var_param_convergence_history
```

```{python}
params = pyro.get_param_store()

```

```{python}
[torch.norm(params[p].grad.detach()) for p in params if params[p].grad is not None ]
```

Pass full dataset as Tensor into model training. Tolerance is at scale of difference in ELBO by iteration.

```{python}
import time
```



## Save model and optimzer state

```{python}
opt.get_state()
# pyro.get_param_store().get_state()
```

```{python}
out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/rmf_ard")
out_filename = os.path.join(out_path, "batch_run_n1000p500_customguide.pth")
```

```{python}
out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/rmf_ard")
out_filename = os.path.join(out_path, "batch_run_n1000p500_customguide.pth")

torch.save({
    "inference_time": run,
    "model_param_store": pyro.get_param_store(),
    "model_state_dict": pyro.get_param_store().get_state(),
    "optimizer_state": opt.get_state(),
    "loss_history": factor_model.loss_history
}, out_filename)
```

```{python}
pyro.get_param_store().get_state()
```

```{python}
# out_filename_base = "batch_run_n500p100_autonormalguide"
# out_filename_base + ".pth"
```

```{python}
out_filename_base = "batch_run_n500p100_autonormalguide"

out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/model")
out_filename = os.path.join(out_path, out_filename_base + ".pth")

torch.save({
    "inference_time": run_minibatch,
    # "model_param_store": pyro.get_param_store(),
    "model_state_dict": pyro.get_param_store().get_state(),
    "optimizer_state": opt.get_state(),
    "loss_history": factor_model.loss_history
}, out_filename)
```


```{python}
pyro.get_param_store().save(os.path.join(out_path, out_filename_base + "_paramstore.pth"))
```

```{python}
mod_info = torch.load(out_filename)
```


```{python}
mod_info.items()
```


```{python}
print(run)
```

Save parameter store 
```{python}
pyro.get_param_store().save("rmf_ard.params_n2000p10000.save")
```

```{python}
pyro.get_param_store().get_all_param_names()
```


```{python}
for name in pyro.get_param_store().get_all_param_names():
    print(name)
    # print(pyro.param(name))
```

```{python}

sns.heatmap(
    pyro.param('AutoNormal.locs.Lambda_l0').detach(),
    cmap="coolwarm"
)

torch.isclose(pyro.param('AutoNormal.locs.Lambda_l0').detach(), torch.tensor(0.))
```

```{python}
def calc_sparsity(tens):
    return sum((tens == 0).flatten()).item() / (tens).flatten().size()[0]
```

```{python}
calc_sparsity(pyro.param('AutoNormal.locs.Lambda_l0').detach())
torch.linalg.matrix_rank(pyro.param('AutoNormal.locs.Lambda_l0').detach())
```

```{python}
sim_data_multiview_torch.get('Lambda_l')[0]
```

# Evaluate

## New code

```{python}
# --- Reload after updating data_utils ---
importlib.reload(sys.modules["data_utils"])
from data_utils import (extract_sim_decomp_single_view,
                        calc_all_structures_with_rescaling_single_view,
                        eval_performance_single_view, eval_mse)

```

Evaluation before local training for test set
```{python}
# Posterior samples — mirrors the SupMultiviewDecomp predict calls
N_SAMPLES = 500

post_samples = train_handler.predict(
    [train_X_clean], 
    N_SAMPLES,
    return_sites=['structure', Sites.Lambda_l.format(l=0), Sites.y]
)
post_samples_y = train_handler.predict(
    [test_X_clean], 
    N_SAMPLES,
    return_sites=[Sites.y] #[Sites.y_pred]
)

```



```{python}
# Ground truth decomposition
SIM_decomp = extract_sim_decomp_single_view(sim_data_torch)

# Compute all structures and rescale — mirrors calc_all_structures_with_rescaling
eval_structures = calc_all_structures_with_rescaling_single_view(
    col_filter,
    train_X_summaries['means'],
    train_X_summaries['sds'],
    post_samples,
    post_samples, #
    # post_samples_y,
    SIM_decomp,
    train_idx,
    # torch.arange(train_X_clean.shape[0]),
    train_y_clean.squeeze()
)

```


```{python}
# eval_structures['sim_struct']
eval_structures['structure_summary']['mean']
```


```{python}
eval_mse(train_y_clean.squeeze(), eval_structures['pred_outcome_summary']['mean']) #post_samples['y'].mean(dim = 0))
```

```{python}
torch.mean(torch.abs(train_y_clean.squeeze() - post_samples['y'].mean(dim = 0)) ** 2)
```
```{python}
# Evaluate — mirrors eval_performance
eval_metric_table = eval_performance_single_view(**eval_structures)
eval_metric_table

```

Plot outcomes

```{python}
train_y_pred = post_samples['y'].mean(dim = 0)

p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = train_y_pred.detach().tolist(), 
                    y = train_y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = train_y_pred.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = train_y_clean.squeeze().tolist(), scatter = False, ax = p)
```

```{python}
post_samples_y
```

```{python}
test_y_pred = post_samples_y['y'].mean(dim = 0)

p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = test_y_pred.detach().tolist(), 
                    y = test_y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = test_y_pred.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = test_y_clean.squeeze().tolist(), scatter = False, ax = p)
```

# Plot loadings

Loadings plot

```{python}
est_Lambda0 = pyro.param(Params.loc_Lambda_l.format(l = 0)).detach().numpy()
est_Lambda0_varimax, R = varimax(est_Lambda0)
```


```{python}
R.shape
```

```{python}
R @ pyro.param('loc_beta').detach().numpy()
```

```{python}
sns.heatmap(
    est_Lambda0,
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)
```


```{python}
sns.heatmap(
    est_Lambda0_varimax,
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)

```


```{python}
Z_rotated = pyro.param("loc_Z").detach().numpy() @ R
beta_rotated = R.T @ pyro.param("loc_beta").detach().numpy()
y_est_rotated = Z_rotated @ beta_rotated
```

```{python}
indx = [1, 2, 5, 7, 8]
y_est_rotated_selected = Z_rotated[:, indx] @ beta_rotated[indx]
```

```{python}
beta_rotated
beta_rotated[indx]
```

```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = y_est.detach().tolist(), 
                    y = y_est_rotated.tolist())
p.set(xlabel = "Predicted y", ylabel = "Y calcualted after rotation")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = y_est.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_est_rotated.tolist(), scatter = False, ax = p)
```

```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = y_est.detach().tolist(), 
                    y = y_est_rotated_selected.tolist())
p.set(xlabel = "Predicted y", ylabel = "Y calcualted after rotation")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = y_est.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_est_rotated_selected.tolist(), scatter = False, ax = p)
```


Structure

```{python}
post_samples['structure'].mean(dim = 0)
```

```{python}
train_X_clean
```

```{python}
SIM_decomp['SIM_Lambda']#[col_filter].shape
```

```{python}
col_filter
```

```{python}
eval_structures['sim_struct']
```


```{python}
eval_rse(post_samples['structure'].mean(dim = 0), train_X_clean)
```

```{python}
eval_rse(post_samples['structure'].mean(dim = 0), eval_structures['sim_struct'])
```


# Local training

For test set evaluation

WITH ADAGRAD

```{python}
# pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
# initial_lr = 0.1
opt_args = {"eta": 1.0, "delta": 1e-16, "t": 0.1}
OPT = AdagradRMSProp({
    "eta": opt_args['eta'], 
    "delta": opt_args['delta'], 
    "t": opt_args['t']})
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

test_handler = ModelHandler(
    "predict", 
    factor_model, 
    opt = OPT, 
    loss = LOSS,
    opt_scheduler = None,
    orthogonal_projection = False)

t0 = time.time()
svi = test_handler.do_inference(
    train_dataset = test_subset,
    inference_type = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 200,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```

With scheduler

```{python}
# pyro.clear_param_store()

MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.1
opt_args = {"lr": initial_lr, "betas": (0.9, 0.999)}
LOSS = Trace_ELBO(num_particles = 2)

k_upper = int(k) + 10

scheduler_args = {
    'optimizer': torch.optim.Adam, 
    'optim_args': opt_args,
    'step_size': 20,
    'gamma': 0.9,
    'verbose': True
}
scheduler = pyro.optim.StepLR(scheduler_args)

test_handler = ModelHandler(
    "predict", 
    factor_model, 
    # OPT, 
    loss = LOSS,
    opt_scheduler = scheduler,
    orthogonal_projection = False)

t0 = time.time()
svi = test_handler.do_inference(
    train_dataset = test_subset,
    inference_type = "svi",
    tol = 0.5, # tolerance is epoch loss per datum
    variational_tol = 0.2,
    min_epochs = 200,
    epochs = NUM_EPOCHS,
    minibatch_flag = True,
    minibatch_size = MINIBATCH_SIZE,
    variational_diff_func = np.mean,
    verbose = True
    )

t1 = time.time()
run_minibatch = t1 - t0
print(f"Minibatch runtime: {run_minibatch / 60} mins, , {factor_model.total_epochs} epochs")
```

# Evaluate after local training

```{python}
# Posterior samples — mirrors the SupMultiviewDecomp predict calls
N_SAMPLES = 500

post_samples = train_handler.predict(
    [train_X_clean], 
    N_SAMPLES,
    return_sites=['structure', Sites.Lambda_l.format(l=0), Sites.y]
)
post_samples_y_test = test_handler.predict(
    [test_X_clean], 
    N_SAMPLES,
    return_sites=[Sites.y_pred] #[Sites.y_pred]
)

```



```{python}
# Ground truth decomposition
SIM_decomp = extract_sim_decomp_single_view(sim_data_torch)

# Compute all structures and rescale — mirrors calc_all_structures_with_rescaling
eval_structures = calc_all_structures_with_rescaling_single_view(
    col_filter,
    train_X_summaries['means'],
    train_X_summaries['sds'],
    post_samples,
    post_samples_y_test, #post_samples_y,
    SIM_decomp,
    train_idx,
    # torch.arange(train_X_clean.shape[0]),
    test_y_clean.squeeze()
    # train_y_clean.squeeze()
)

```


```{python}
# Evaluate — mirrors eval_performance
eval_metric_table = eval_performance_single_view(**eval_structures)
eval_metric_table

```


```{python}
train_y_pred = post_samples['y'].mean(dim = 0)

p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = train_y_pred.detach().tolist(), 
                    y = train_y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = train_y_pred.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = train_y_clean.squeeze().tolist(), scatter = False, ax = p)
```


```{python}
test_y_pred = post_samples_y_test['y_pred'].mean(dim = 0)

p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = test_y_pred.detach().tolist(), 
                    y = test_y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = test_y_pred.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = test_y_clean.squeeze().tolist(), scatter = False, ax = p)
```

### FactorModel


```{python}
# num_to_pad = pyro.param(Params.loc_Lambda_l.format(l = 0)).shape[1] - sim_data_torch["Lambda_l"][0].shape[1]
# torch.nn.functional.pad(sim_data_torch["Lambda_l"][0], (0, num_to_pad)).shape


```

```{python}
# align_tensor_shapes(pyro.param(Params.loc_Lambda_l.format(l = 0)),
# sim_data_torch["Lambda_l"][0]).shape
```

```{python}
def evaluate_matrix_decomp(sim_Z, sim_Lambda, est_Z, est_Lambda, means, sds, col_filter):
    Struct_est = est_Z @ est_Lambda.T
    Struct_sim = sim_Z @ sim_Lambda.T

    Struct_sim_rescaled = (Struct_sim[:,col_filter] - means) / sds

    return torch.norm(Struct_sim_rescaled - Struct_est) ** 2 / torch.norm(Struct_sim_rescaled) ** 2

```

```{python}
pyro.param(Params.loc_Lambda_l.format(l = 0))
```

```{python}
evaluate_matrix_decomp(sim_Z = sim_data_torch["Z"],
                    sim_Lambda = sim_data_torch["Lambda_l"][0],
                    est_Z = pyro.param("loc_Z"),
                    est_Lambda = pyro.param(Params.loc_Lambda_l.format(l = 0)),
                    means = X_summaries['means'],
                    sds = X_summaries['sds'],
                    col_filter = col_filter              
    )
```


```{python}
sim_calulated_y = sim_data_torch["Z"] @ sim_data_torch["beta"]
```

```{python}
sim_data_torch["Lambda_l"][0]
pyro.param(Params.loc_Lambda_l.format(l = 0))
```

```{python}
sim_cov = calc_cov(sim_data_torch["Lambda_l"][0])
est_cov = calc_cov(pyro.param(Params.loc_Lambda_l.format(l = 0)))
est_cov
```

```{python}
sim_cov_scaled = scale_sim_cov(sim_cov, X_summaries['sds'], X_summaries['sds'])
sim_cov_scaled
```

```{python}

torch.norm(sim_cov_scaled - est_cov) ** 2 / (est_cov.shape[0] * est_cov.shape[1])
```

```{python}
sim_cov_scaled
est_cov
```


Outcome

```{python}
pyro.param("loc_beta")
# pyro.param("Z_loc")
```


```{python}
# pyro.get_param_store().keys()
post_samples_outcome_structure = train_handler.predict([X_clean], 200, ['outcome_structure', 'y'])
post_samples_outcome_structure


y_pred_post_mean = post_samples['y'].mean(dim = 0) #post_samples_y['y'].mean(dim = 0)
y_pred_post_mean
# y_pred_post_mean = post_samples_outcome_structure['y'].mean(dim = 0) #post_samples_y['y'].mean(dim = 0)
# y_pred_post_mean

outcome_struct_post_mean = post_samples_outcome_structure['outcome_structure'].mean(dim = 0)
outcome_struct_post_mean
```


```{python}
post_samples['y'].mean(dim = 0)
```

```{python}
print(factor_model.a_sigma_y, factor_model.b_sigma_y)
inv_gamma_moments(factor_model.a_sigma_y, factor_model.b_sigma_y)
```

```{python}
print(pyro.param("a_sigma_y"), pyro.param("b_sigma_y"))
inv_gamma_moments(pyro.param("a_sigma_y"), pyro.param("b_sigma_y"))
```

```{python}
y_est = pyro.param("loc_Z") @ pyro.param("loc_beta")
y_est
```

```{python}
torch.nn.functional.mse_loss(y_est, y_clean)

```

```{python}
torch.nn.functional.mse_loss(y_pred_post_mean, y_clean.squeeze())

```


```{python}
torch.nn.functional.mse_loss(outcome_struct_post_mean, y_clean)

```


```{python}
torch.nn.functional.mse_loss(outcome_struct_post_mean, y_pred_post_mean)
```


```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = y_pred_post_mean.detach().tolist(), 
                    y = y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = y_pred_post_mean.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_clean.squeeze().tolist(), scatter = False, ax = p)
```


```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = y_est.detach().tolist(), 
                    y = y_clean.squeeze().tolist())
p.set(xlabel = "E(Z) @ E(Beta)", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = y_est.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_clean.squeeze().tolist(), scatter = False, ax = p)
```

```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = outcome_struct_post_mean.detach().tolist(), 
                    y = y_pred_post_mean.squeeze().tolist())
p.set(xlabel = "Linear predictor Z @ Beta", ylabel = "Predicted y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = outcome_struct_post_mean.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_pred_post_mean.squeeze().tolist(), scatter = False, ax = p)
```

```{python}
p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = y_est.detach().tolist(), 
                    y = y_pred_post_mean.squeeze().tolist())
p.set(xlabel = "E(Z) @ E(Beta)", ylabel = "Predicted y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = y_est.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_pred_post_mean.squeeze().tolist(), scatter = False, ax = p)
```

```{python}
sim_calculated_y = sim_data_torch["Z"] @ sim_data_torch["beta"]

sim_calculated_y = (sim_calculated_y - sim_calculated_y.mean()) / sim_calculated_y.std()

p = sns.scatterplot(#x = pyro.param('y_loc').detach().tolist(), 
                    x = sim_calculated_y.detach().tolist(), 
                    y = y_clean.squeeze().tolist())
p.set(xlabel = "Y calculated from simulated Z @ beta", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = sim_calculated_y.detach().tolist(), #pyro.param('y_loc').detach().tolist(), 
            y = y_clean.squeeze().tolist(), scatter = False, ax = p)
```

Coverage

```{python}
torch.numel(y_clean.squeeze())
```
```{python}
post_pred_outcome_summaries = summarise_post_samples(post_samples_outcome_structure['y'])

outcome_coverage = eval_post_coverage(
        y_clean.squeeze(),
        post_pred_outcome_summaries.get('q2.5'),
        post_pred_outcome_summaries.get('q97.5')
        ).item()

outcome_coverage
```

```{python}
outcome_coverage
```

```{python}
for k in range(factor_model.k):
    corr_k = torch.corrcoef(torch.stack([pyro.param("loc_Z")[:, k], y_clean.squeeze()]))[0, 1]
    print(f"Z_loc[:,{k}] correlation with y_true: {corr_k.item():.3f}")

```

Scores

```{python}
import matplotlib.pyplot as plt
```

```{python}
Z_pred = train_handler.predict([X_clean], 200, ['Z'])
```

```{python}
Z_pred['Z'].shape
```


```{python}
plt.hist(Z_pred['Z'][:, 0, 0].numpy(), bins=50, edgecolor='black')
```

```{python}
Z_pred['Z'].mean(dim = 0)
```

Beta

```{python}
beta_pred = train_handler.predict([X_clean], 200, ['beta'])
```


```{python}
beta_pred['beta'][:, 0, 1].std()
```
```{python}
plt.hist(beta_pred['beta'][:, 0, 1].numpy(), bins=50, edgecolor='black')
```

```{python}
pyro.param('Z_scale').shape
```

```{python}
X_pca = torch.pca_lowrank(X_clean, q = 15)
```






```{python}
R
```
```{python}
sns.heatmap(
    varimax(loadings_init),
# sim_data_multiview_torch.get('Lambda_l')[0],
cmap="coolwarm"
)

```

With AutoNormal guide
```{python}
Lambda_est = pyro.param("AutoNormal.locs.Lambda")
Z_est = pyro.param("AutoNormal.locs.Z")
Z_est
```





With custom guide
```{python}
Lambda_est = pyro.param(Params.loc_Lambda_l.format(l = 0)) #"Lambda_loc")
Z_est = pyro.param("Z_loc")
Z_est
```

```{python}
Lambda_est
```

```{python}
Z_est.shape
# pyro.param("AutoNormal.scales.Z_batch").shape
```

Structure from fit model 

```{python}
Struct_est = Z_est @ Lambda_est.T
Struct_est
```

```{python}
torch.std(Struct_est, 0)
```

Rescaled structure to have ORIGINAL mean and variance

```{python}

```

```{python}
Struct_est_rescaled = (Struct_est * X_summaries['sds']) + X_summaries['means']
# Struct_est_rescaled = (Struct_est * X_stds) + X_means
Struct_est_rescaled
```

Structure from simulated edata

```{python}
Struct_sim = sim_data_torch["Z"] @ sim_data_torch["Lambda_l"][0].T
Struct_sim
```

Rescaled to have mean 0 and variance 1
```{python}
# Struct_sim_rescaled = (Struct_sim * X_stds) + X_means
Struct_sim_rescaled = (Struct_sim[:,col_filter] - X_summaries['means']) /  X_summaries['sds']
Struct_sim_rescaled
```

```{python}
Struct_sim_rescaled.shape
Struct_est_rescaled.shape
# sim_data_torch["Lambda_l"][0]
```

```{python}
# torch.norm(sim_data_torch["X_l"][0] - Struct_est) ** 2 / torch.norm(sim_data_torch["X_l"][0]) ** 2
```

```{python}
torch.norm(Struct_est)
```

```{python}
torch.norm(Struct_sim - Struct_est) ** 2 / torch.norm(Struct_sim) ** 2
```

Compare rescaled 
```{python}
# torch.norm(Struct_sim - Struct_est_rescaled) ** 2 / torch.norm(Struct_est_rescaled) ** 2

torch.norm(Struct_sim_rescaled - Struct_est) ** 2 / torch.norm(Struct_sim_rescaled) ** 2
```

```{python}
# torch.norm(Struct_sim - Struct_est_rescaled) ** 2 / torch.norm(Struct_sim) ** 2
```

### Loading interpretation

```{python}
Lambda_est = pyro.param(Params.loc_Lambda_l.format(l = 0)) 
Lambda_sim = sim_data_torch["Lambda_l"][0]
Lambda_sim_pad = torch.nn.functional.pad(Lambda_sim[col_filter, :], (0, k_upper - Lambda_sim.shape[1]))
# pad_amount = k_upper - Lambda_sim.shape[1]

matrix_diff = Lambda_est - Lambda_sim_pad
torch.norm(matrix_diff)
```

```{python}

```

```{python}
sns.heatmap(
    Lambda_est.detach(),
    cmap="coolwarm"
)
```

```{python}
Lambda_est_rotated = varimax(Lambda_est.detach().numpy())
```

```{python}

```

```{python}
sns.heatmap(
    Lambda_est_rotated,
    cmap="coolwarm"
)
```

```{python}
sns.relplot(
    np.sum(Lambda_est.detach().numpy() ** 2, axis = 0),
    # np.sum(Lambda_est_rotated ** 2, axis = 0),
    kind="line"
    )
```

```{python}
# Lambda_est_svd = np.linalg.svd(Lambda_est_rotated)
Lambda_est_svd = np.linalg.svd(Lambda_est.detach().numpy())
np.cumsum(Lambda_est_svd.S ** 2) / sum(Lambda_est_svd.S ** 2)
```

```{python}
Lambda_est_trunc = Lambda_est_svd.U[:,0:5] @ np.diag(Lambda_est_svd.S[0:5]) @ Lambda_est_svd.Vh[0:5, :]
```

```{python}
sns.heatmap(
    Lambda_est_trunc,
    cmap="coolwarm"
)
```

```{python}
np.nonzero(Lambda_est_trunc[0,])
```

```{python}
Lambda_est_svd.Vh.shape
```
When does variance explained decrease?
```{python}
Lambda_est_rotated
Lambda_colsums = np.sum(Lambda_est_rotated ** 2, axis = 0)
# Lambda_colsums = np.sum(Lambda_est.detach().numpy() ** 2, axis = 0)
Lambda_totalsum = np.sum(Lambda_colsums)
sns.relplot(
    Lambda_colsums / Lambda_totalsum,
    # np.sum(Lambda_est_rotated ** 2, axis = 0),
    kind="line"
    )
```

When does tau become large?
```{python}
delta_sites = [Sites.delta_lambda_l_k.format(l = 0, m = m) for m in range(k_upper)]
delta_post_samples = train_handler.predict([X_clean], 100, delta_sites)
```

```{python}
delta_means = [np.mean(delta_post_samples[site].squeeze().tolist()) for site in delta_sites]
# delta_post_samples.items() #['delta_lambda_l0_k0'].shape
sns.relplot(1 / np.cumprod(delta_means), kind = "scatter")
```

```{python}
# np.mean(1 / (delta_post_samples[delta_sites[0]]).squeeze().tolist())
# 1 / (delta_post_samples[delta_sites[0]])
```

# Predict 

```{python}
import pyro
import torch
d = torch.load('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n50p50_snr2.2_sparse0_rep1.pth')

pyro.get_param_store().load('/Users/jonathanhori/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models/run_autonormalguide_n50p50_snr2.2_sparse0_rep1_paramstore.pth')
```

```{python}

```

```{python}
os.getcwd()
```

```{python}
#| label: Load param store


pyro.clear_param_store()
# pyro.get_param_store().load("rmf_ard.params_n2000p10000.save")
pyro.get_param_store().load("./results/model/batch_run_n500p100_autonormalguide_paramstore.pth")
```

## SupMultiviewDecomp

```{python}
guide = None
```

Initialize model/guide objects for param store 
```{python}
#| label: Initialize model and guide if not already
factor_model = SupMultiviewDecomp(
    int(k),
    k_l_list.int().tolist(),
    n,
    include_view_factors = True
)

def subsample_create_plates(X, batch_idx, y = None):
    # m = len(batch_idx)
    return pyro.plate("obs", factor_model.n, subsample = batch_idx)
# guide = factor_model.guide

guide = pyro.infer.autoguide.AutoNormal(
    factor_model, 
    create_plates = subsample_create_plates)
```

Posterior samples for structures

```{python}
sites = [f'joint_structure_l{l}' for l in range(L)] + [f'view_structure_l{l}' for l in range(L)]
sites
```

```{python}
predictive = pyro.infer.Predictive(
    factor_model, 
    guide = guide, 
    num_samples = 1000,
    return_sites = sites)

post_samples = predictive(
    X_l_list_clean,
    torch.arange(n),
    y.squeeze()
    )
```

```{python}
# post_samples = post_samples_
```

```{python}
joint_structure_summaries = summarise_structure_list(post_samples, L, "joint")
individual_structure_summaries = summarise_structure_list(post_samples, L, "individual")

POST_joint_struct_l_list = [summary.get('mean') for summary in joint_structure_summaries]
POST_individual_struct_l_list = [summary.get('mean') for summary in individual_structure_summaries]
```

```{python}
X_l_list_clean
```

Predictions of y

```{python}
predictive_outcome = pyro.infer.Predictive(
    factor_model, 
    guide = guide, 
    num_samples = 1000,
    return_sites=["y"])

post_samples_outcome = predictive_outcome(
    X_l_list_clean,
    torch.arange(n)
    )
```

```{python}
# post_samples_outcome.get('y')
```

```{python}
PRED_outcome_summary = summarise_post_samples(post_samples_outcome.get("y"))
PRED_y = PRED_outcome_summary.get('mean')
```


Evaluation 

```{python}
SIM_joint_struct_l_list_rescaled = SIM_Struct_shared_l_list_rescaled
SIM_individual_struct_l_list_rescaled = SIM_Struct_view_l_list_rescaled
```
```{python}
joint_rse = [eval_rse(est, sim).detach().item() for est, sim in \
    zip(POST_joint_struct_l_list, 
    SIM_joint_struct_l_list_rescaled)]
individual_rse = [eval_rse(est, sim).detach().item() for est, sim in \
    zip(POST_individual_struct_l_list, SIM_individual_struct_l_list_rescaled)]

joint_coverage = eval_credible_interval(
    SIM_joint_struct_l_list_rescaled,
    joint_structure_summaries,
    '95')
individual_coverage = eval_credible_interval(
    SIM_individual_struct_l_list_rescaled,
    individual_structure_summaries,
    '95')

outcome_mse = eval_mse(PRED_y, y_clean.squeeze()).item()
outcome_coverage = eval_post_coverage(
    y_clean.squeeze(),
    PRED_outcome_summary.get('q2.5'),
    PRED_outcome_summary.get('q97.5')
    ).item()

eval_metric_table = pd.wide_to_long(pd.DataFrame({
    "joint.rse": joint_rse,
    "individual.rse": individual_rse,
    "joint.95p_coverage": joint_coverage,
    "individual.95p_coverage": individual_coverage,
    "outcome.mse": outcome_mse,
    "outcome.95p_coverage": outcome_coverage
    }
    ).rename_axis('view').reset_index(),
    stubnames = ['joint', 'individual', 'outcome'],
    i = 'view',
    j = 'metric',
    sep = '.',
    suffix = '.+')
```

```{python}
eval_metric_table
```


```{python}
# USING POSTERIOR SAMPLES
# p = sns.scatterplot(x = sim_y.tolist(), y = y_clean.T.tolist()[0])
p = sns.scatterplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist())
p.set(xlabel = "Predicted y", ylabel = "Simulated y")
p.set_title("Predicted vs. actual outcome")
# plt.plot([-3, -3], [3, 3])
p.axline((0, 0), slope = 1, color = "black", ls = "--")
sns.regplot(x = PRED_y.tolist(), y = y_clean.squeeze().tolist(), scatter = False, ax = p)

```

```{python}
post_samples.keys()
# dict_keys(['sigma2_gamma_l0', 'Gamma_l0', 'sigma2_gamma_l1', 'Gamma_l1', 'sigma2_gamma_l2', 'Gamma_l2', 'sigma2_lambda_l0', 'Lambda_l0', 'sigma2_lambda_l1', 'Lambda_l1', 'sigma2_lambda_l2', 'Lambda_l2', 'psi_l0', 'psi_l1', 'psi_l2', 'sigma2_beta', 'beta', 'sigma2_y', 'Z', 'Phi_l0', 'Phi_l1', 'Phi_l2', 'y', 'joint_structure_l0', 'view_structure_l0', 'X_l0', 'joint_structure_l1', 'view_structure_l1', 'X_l1', 'joint_structure_l2', 'view_structure_l2', 'X_l2', 'outcome_structure'])

```
```{python}
post_samples_with_y.keys()
# dict_keys(['sigma2_gamma_l0', 'Gamma_l0', 'sigma2_gamma_l1', 'Gamma_l1', 'sigma2_gamma_l2', 'Gamma_l2', 'sigma2_lambda_l0', 'Lambda_l0', 'sigma2_lambda_l1', 'Lambda_l1', 'sigma2_lambda_l2', 'Lambda_l2', 'psi_l0', 'psi_l1', 'psi_l2', 'sigma2_beta', 'beta', 'sigma2_y', 'Z', 'Phi_l0', 'Phi_l1', 'Phi_l2', 'joint_structure_l0', 'view_structure_l0', 'X_l0', 'joint_structure_l1', 'view_structure_l1', 'X_l1', 'joint_structure_l2', 'view_structure_l2', 'X_l2', 'outcome_structure', 'y'])
```


```{python}
post_samples_outcome.get("y").shape
```

```{python}
torch.norm(torch.mean(post_samples.get("joint_structure_l0"), dim = 0) - \
    torch.mean(post_samples_with_y.get("joint_structure_l0"), dim = 0))
```

```{python}
torch.norm(torch.mean(post_samples.get("joint_structure_l0"), dim = 0) - \
    EST_Struct_shared_l_list_rescaled[0])
```

```{python}
EST_Struct_shared_l_list_rescaled[0]
```

```{python}
# EST_decomp = 
PRED_Struct_shared_l_list = [torch.mean(post_samples.get(f"joint_structure_l{l}"), dim = 0) \
    for l in range(L)]

# EST_Struct_shared_l_list = list(map(calc_struct, \
#     [EST_decomp.get("EST_Z")] * L, EST_decomp.get("EST_Lambda_l_list")))
# EST_Struct_view_l_list = list(map(calc_struct, \
#     EST_decomp.get("EST_Phi_l_list"), EST_decomp.get("EST_Gamma_l_list")))
```

```{python}
PRED_Struct_shared_l_list
```

```{python}
EST_Struct_shared_l_list
```

```{python}
eval_rse(PRED_Struct_shared_l_list[0], SIM_Struct_shared_l_list_rescaled[0])
```
```{python}
EST_Struct_shared_l_list
SIM_Struct_shared_l_list_rescaled
```

```{python}
y_post_pred = torch.mean(post_samples_outcome.get("y"), dim = 0)
```

Compare posterior sample mean/median with variational location params in the param store.

```{python}
# J1_summary = summarise_post_samples(post_samples.get('joint_structure_l1'))


joint_structure_summaries = summarise_structure_list(post_samples, L, "joint")
individual_structure_summaries = summarise_structure_list(post_samples, L, "individual")
```

```{python}
joint_structure_summaries[0]
```

```{python}
SIM_Struct_shared_l_list_rescaled[0]
```

```{python}


    
# [eval_post_coverage(sim_struct, lower, upper) for sim_struct, post_summary in zip(SIM_Struct_shared_l_list_rescaled, joint_structure_summaries)]

# eval_post_coverage(SIM_Struct_shared_l_list_rescaled[1],
# J1_summary.get('q25'),
# J1_summary.get('q75'))
```

```{python}
[eval_post_coverage(sim_struct, post_summary.get(lower), post_summary.get(upper)) for sim_struct, post_summary in zip(SIM_Struct_shared_l_list_rescaled, joint_structure_summaries)]
```

```{python}
joint_coverage = eval_credible_interval(
    SIM_Struct_shared_l_list_rescaled,
    joint_structure_summaries,
    '95')

individual_coverage = eval_credible_interval(
    SIM_Struct_view_l_list_rescaled,
    individual_structure_summaries,
    '95')
```

```{python}
individual_coverage
```


```{python}
post_outcome_summary = summarise_post_samples(post_samples_outcome.get("y"))
```

```{python}
y_clean.squeeze()
# post_outcome_summary.get('q2.5')
```

```{python}
eval_post_coverage(y_clean.squeeze(),
    post_outcome_summary.get('q2.5'),
    post_outcome_summary.get('q97.5'))
```

```{python}
torch.sum(torch.logical_and(
            torch.less_equal(post_outcome_summary.get('q2.5'), y_clean),
            torch.greater_equal(post_outcome_summary.get('q97.5'), y_clean)
        )) #/ torch.numel(sim_struct)
```

```{python}
# torch.numel(y_clean)
post_outcome_summary.get('q97.5')
```

```{python}
pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage
            }
            ).rename_axis('view').reset_index()
```

```{python}
outcome_mse = eval_mse(post_sample_y, y_clean.squeeze()).item()
outcome_coverage = eval_post_coverage(y_clean.squeeze(),
    post_outcome_summary.get('q2.5'),
    post_outcome_summary.get('q97.5')).item()
```
```{python}
pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage,
            "outcome.rse": outcome_mse,
            "outcome.95pcoverage": outcome_coverage
            }
            ).rename_axis('view').reset_index()
```
```{python}
pd.wide_to_long(pd.DataFrame({
            "joint.rse": shared_rse,
            "individual.rse": view_rse,
            "joint.95p_coverage": joint_coverage,
            "individual.95p_coverage": individual_coverage,
            "outcome.mse": outcome_mse,
            "outcome.95p_coverage": outcome_coverage
            }
            ).rename_axis('view').reset_index(),
            stubnames = ['joint', 'individual', 'outcome'],
            i = 'view',
            j = 'metric',
            sep = '.',
            suffix = '.+').\
            assign(n = n,
                p = 40,
                snr_x = 2,
                snr_y = 2,
                runtime = 0
                )
                
```

```{python}
summarise_post_samples('view_structure_l2')
```


```{python}
# J1_summary.get('mean')
eval_rse(J1_summary.get('mean'), SIM_Struct_shared_l_list_rescaled[1])
```

```{python}
J1_summary.get('mean')
```

```{python}
SIM_Struct_shared_l_list_rescaled[1]
```

```{python}
pyro.param("AutoNormal.locs.Z")
```

```{python}
trace = pyro.poutine.trace(factor_model).get_trace(
    X_l_list_clean,
    torch.arange(X_l_list_clean[0].shape[0]),
    y
)
```

```{python}
trace.nodes.get("joint_structure_l0").get("value")
```

```{python}
EST_Struct_shared_l_list[0]
```

```{python}
Lambda_l_post_samples = [post_samples.get(f"Lambda_l{l}") for l in range(L)]

# EST_Lambda_l_list = [pyro.param(f"AutoNormal.locs.Lambda_l{l}") for l in range(L)]
#         EST_Z = pyro.param("AutoNormal.locs.Z")

#         EST_Gamma_l_list = [pyro.param(f"AutoNormal.locs.Gamma_l{l}") for l in range(L)]
#         EST_Phi_l_list = [pyro.param(f"AutoNormal.locs.Phi_l{l}") for l in range(L)]
```

## FactorModelARD
```{python}
pyro.clear_param_store()
pyro.get_param_store().load("rmf_ard.params_n2000p10000.save")
```


```{python}
# guide = AutoNormal(bayesian_factor_model)
post_samples_fromguide = guide.sample_posterior(sample_shape = (1000,))
```

Posterior samples for all latent avriables
```{python}
predictive = pyro.infer.Predictive(guide, num_samples = 1000)
post_samples = predictive(X_clean, torch.arange(X_clean.shape[0]))
```

```{python}
post_samples_subset = dict((k, post_samples[k]) for k in ("sigma2_lambda", "Lambda", "psi", "Z"))
predictive_model = pyro.infer.Predictive(
    factor_model, 
    posterior_samples = post_samples_subset,
    num_samples = 1000,
    return_sites = ["structure"])

post_samples_from_model = predictive_model(X_clean, torch.arange(X_clean.shape[0]))

```

```{python}
post_samples.keys()

dict(k, post_samples[k] for k in ("sigma2_lambda", "Lambda", "psi", "Z"))
```

```{python}
post_samples.get("Z").shape
```

```{python}
pyro.param("AutoNormal.locs.Z").squeeze(0)
```

```{python}
# post_pred = predict_factor_model(bayesian_factor_model,
#                                  g,
#                                  1000,
#                                 #  [X, 5, X.shape[0]])
#                                  {"X": X,
#                                   "k": 5,
#                                   "n": X.shape[0]})
```

```{python}
Lambda_post_mean = torch.mean(post_samples.get("Lambda"), dim = 0).squeeze(0)
Z_post_mean = torch.mean(post_samples.get("Z"), dim = 0).squeeze(0)
```
```{python}
Struct_post_mean = Z_post_mean @ Lambda_post_mean.T
Struct_post_mean
```

```{python}
Struct_sim
```

```{python}
Struct_deterministic_post_mean = torch.mean(post_samples.get("structure"), dim = 0)
```

Check structure from posterior mean:

```{python}
# print(torch.norm(Struct_deterministic_post_mean - Struct_est_rescaled) ** 2 / torch.norm(Struct_est_rescaled) ** 2)
print(torch.norm(Struct_post_mean - Struct_sim_rescaled) ** 2 / torch.norm(Struct_sim_rescaled) ** 2)
```


```{python}
structure_summary = summarise_post_samples(post_samples.get("structure"))
```

## Elementwise posterior credible interval nominal coverage


```{python}
eval_post_coverage(SIM_Struct_shared_l_list_rescaled[1],
J1_summary.get('q25'),
J1_summary.get('q75'))

# J1_summary.get('q25')
```

```{python}
J1_summary.get('q75')
```

```{python}
# structure_summary["std"]

```

```{python}
Lambda_post_mean
```

```{python}
Struct_est
```

```{python}
def test_fn(X, k, n):
      print(X, k, n)

test_fn(**{"X": X, "k": 5,"n": X.shape[0]})
```

```{python}
[(a, b) for (a, b) in post_pred.items()]
```

```{python}
torch.mean(post_pred["Lambda"], dim = 0)
```

```{python}


svi_samples = {k: v.reshape(1000).detach().cpu().numpy()
                for k, v in post_pred.items()a
                if k != "obs"}
```

# _____________________________
# Simulation replicates

```{python}
sim_data_path = "~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/"

# Absolute paths to directories containing dataset replicates
dirs = [os.path.join(sim_data_path, dir) \
    for dir in os.listdir(os.path.expanduser(sim_data_path)) \
        if os.path.isdir(os.path.expanduser(os.path.join(sim_data_path, dir)))]

dirs[0:5]
```

```{python}
filename_dict = {os.path.basename(name): os.listdir(os.path.expanduser(name)) for name in dirs}
```

Parameters
```{python}
n_array = (50, 100, 500, 1000)
p_array = (50, 100, 1000)
snr_x_array = (2, 1, 0.5)
snr_y_array = (2, 1, 0.5)
reps = 1
loading_sparsity = 0

sim_grid = itertools.product(
    n_array,
    p_array,
    snr_x_array,
    snr_y_array,
    # range(reps),
    [loading_sparsity]
)
```

Load sim_data_path and filename_dict previously

```{python}
[x+1 for x in range(1)]
```

```{python}
MINIBATCH_SIZE = 32
NUM_EPOCHS = 1000
initial_lr = 0.01

gamma = 0.1  # final learning rate will be gamma * initial_lr
lrd = gamma ** (1 / (NUM_EPOCHS * MINIBATCH_SIZE))

file_dir_base = "n{}p{}_snr{}.{}_sparse{}" #/sim_data_ywithview_rep{}.rds"
file_name_base = "sim_data_ywithview_rep{}"

model_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/models")
model_out_filename_base = "run_autonormalguide_n{}p{}_snr{}.{}_sparse{}_rep{}"

metric_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/metrics")
metric_out_filename_base = "run_autonormalguide_n{}p{}_snr{}.{}_sparse{}_rep{}"

metric_list = []

for n, p, snr_x, snr_y, sparsity in sim_grid:
    pyro.clear_param_store()
    print("Loading:")
    print(file_dir_base.format(n, p, snr_x, snr_y, sparsity))
    # Load data
    # file_name_base.format(n, p, snr_x, snr_y, sparsity) #, rep)
    files_for_condition = load_and_process_rds_data_for_condition(
        file_dir_base.format(n, p, snr_x, snr_y, sparsity), # "n100p100_snr2.2_sparse0", 
        sim_data_path, # loaded above
        filename_dict, # loaded above
        reps) # how many reps to import

    for rep in range(reps):
        ##################
        # Setup replicate data
        print(file_name_base.format(rep))
        sim_data = files_for_condition.get(file_name_base.format(rep))
        
        k = int(sim_data.get("K"))
        X_l_list = sim_data.get("X_l")
        y = sim_data.get("y")
        k_l_list = sim_data.get("K_l").int().tolist()
        n = X_l_list[0].shape[0]
        p_l = int(sim_data.get("p_l")[0])

        # Clean
        clean_X_dict_list = list(map(normalize_tensor_by_col, X_l_list))
        # normalize_tensor_by_col(X)

        # X_clean = clean_X_dict.get("data_clean")
        # X_means = clean_X_dict.get("means")
        # X_stds = clean_X_dict.get("sds")
    
        X_l_list_clean = [clean["data_clean"] for clean in clean_X_dict_list]
        X_l_mean_list = [clean["means"] for clean in clean_X_dict_list]
        X_l_sd_list = [clean["sds"] for clean in clean_X_dict_list]

        y_mean = torch.mean(y)
        y_std = torch.sd(y)
        y_clean = (y - y_mean) / y_std

        ##################
        # Perform model inference
        factor_model = SupMultiviewDecomp(
            k,
            k_l_list,
            n,
            include_view_factors = True
        )

        def subsample_create_plates(X, batch_idx, y = None):
            return pyro.plate("obs", factor_model.n, subsample = batch_idx)
        guide = pyro.infer.autoguide.AutoNormal(
            factor_model, 
            create_plates = subsample_create_plates)

        # OPT = Adam({"lr": initial_lr})
        OPT = ClippedAdam({"lr": initial_lr, "lrd": lrd})
        LOSS = Trace_ELBO(num_particles = 1)

        t0 = time.time()
        svi, opt = do_inference(
            X_l_list_clean,
            y_clean,
            model = factor_model,
            guide = guide,
            opt = OPT,
            elbo = LOSS,
            tol = 0.5, # tolerance is on epoch loss per datum
            epochs = NUM_EPOCHS,
            minibatch_flag = True,
            minibatch_size = MINIBATCH_SIZE
            )
        t1 = time.time()
        run_minibatch = t1 - t0
        
        #################
        # Inference finished, save and evaluate
        # Save model parameters

        model_out_filename = os.path.join(
            model_out_path, 
            model_out_filename_base.format(n, p, snr_x, snr_y, sparsity, rep))
        print("Exporting:")
        print(model_out_filename)
        

        torch.save({
            "inference_time": run_minibatch,
            # "model_param_store": pyro.get_param_store(),
            "model_state_dict": pyro.get_param_store().get_state(),
            "optimizer_state": opt.get_state(),
            "loss_history": factor_model.loss_history
        }, model_out_filename + ".pth")

        pyro.get_param_store().save(model_out_filename + "_paramstore.pth") #os.path.join(model_out_path, model_out_filename + "_paramstore.pth"))
        
        #################
        # Evaluate model 
        EST_decomp = extract_est_decomp(L, True)

        EST_Struct_shared_l_list = list(map(calc_struct, \
            [EST_decomp.get("EST_Z")] * L, EST_decomp.get("EST_Lambda_l_list")))
        EST_Struct_view_l_list = list(map(calc_struct, \
            EST_decomp.get("EST_Phi_l_list"), EST_decomp.get("EST_Gamma_l_list")))

        SIM_decomp = extract_sim_decomp(sim_data_multiview_torch)

        SIM_Struct_shared_l_list = list(map(calc_struct, \
            [SIM_decomp.get("SIM_Z")]* L, SIM_decomp.get("SIM_Lambda_l_list")))
        SIM_Struct_view_l_list = list(map(calc_struct, \
            SIM_decomp.get("SIM_Phi_l_list"), SIM_decomp.get("SIM_Gamma_l_list")))

        EST_Struct_shared_l_list_rescaled = scale_est_struct(EST_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)
        SIM_Struct_shared_l_list_rescaled = scale_sim_struct(SIM_Struct_shared_l_list, X_l_mean_list, X_l_sd_list)

        EST_Struct_view_l_list_rescaled = scale_est_struct(EST_Struct_view_l_list, X_l_mean_list, X_l_sd_list)
        SIM_Struct_view_l_list_rescaled = scale_sim_struct(SIM_Struct_view_l_list, X_l_mean_list, X_l_sd_list)

        shared_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_shared_l_list_rescaled, SIM_Struct_shared_l_list)]
        view_rse = [eval_rse(est, sim).detach().item() for est, sim in zip(EST_Struct_view_l_list_rescaled, SIM_Struct_view_l_list)]

        eval_metric_table = pd.melt(pd.DataFrame({
            "shared": shared_rse,
            "view_specific": view_rse
            }
            ).rename_axis('view').reset_index(),
            id_vars = ["view"],
            value_vars = ["shared", "view_specific"],
            var_name = "structure",
            value_name = "rse").\
            assign(n = n,
                p = p_l,
                snr_x = snr_x,
                snr_y = snr_y,
                runtime = run_minibatch
                )

        # Save evaluation
        metric_out_filename = os.path.join(
            metric_out_path, 
            metric_out_filename_base.format(n, p, snr_x, snr_y, sparsity, rep))
        print("Exporting metrics:")
        print(metric_out_filename)

        eval_metric_table.to_csv(metric_out_filename)
        metric_list.append(eval_metric_table)

```


# Evaluate replicates

```{python}
metric_out_path = os.path.expanduser("~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/results/integration/metrics")
# sim_data_path = "~/Library/Mobile Documents/com~apple~CloudDocs/Projects/multiomic_integration/sim/data3/"

# Absolute paths to directories containing dataset replicates
dirs = os.listdir(metric_out_path)
```

```{python}
metric_csvs = [pd.read_csv(os.path.join(metric_out_path, name)) for name in dirs if name != ".DS_Store"]
```

```{python}
full_metric_table = pd.concat(metric_csvs)
```

```{python}
full_metric_table 
```

```{python}
p = sns.catplot(
    data = full_metric_table.loc[full_metric_table['structure'] == 'shared'],
    x = 'n',
    y = 'rse',
    row = 'snr_y',
    col = 'snr_x',
    hue = 'p',
    kind = 'box',
    palette = sns.color_palette(palette='Accent')
)
p.fig.suptitle("Shared reconstruction RSE")
```

```{python}
p = sns.catplot(
    data = full_metric_table.drop_duplicates(subset = ['n', 'p', 'snr_x', 'snr_y'],),
    x = 'n',
    y = 'runtime',
    # row = 'snr_y',
    col = 'p',
    # hue = 'p',
    kind = 'box',
    palette = sns.color_palette(palette='Accent')
)
p.fig.suptitle("Model runtime")
```

```{python}
full_metric_table['structure'].unique()
```

# _____________________________



DEBUG

```{python}
importlib.reload(sys.modules["run_methods"])
```

```{python}
"""
Hyperparameter tuning script for MatrixDecomp (single-view supervised factor model).

Data layout expected:
    sim/data/single_view_withoutcome/k.<k>/<filename>.rds

Each RDS file contains a single replicate with keys:
    X_l (list of 1 matrix), y, Z, Lambda_l, K, p_l

Outputs per (data_config, train_config):
    sim/results/matrixdecomp/metrics/<filename_base>.csv
"""

import os
import sys
import itertools

import pandas as pd
from pathlib import Path

import pyro

sys.path.insert(1, "/Users/jonathanhori/multiomic_integration/python")

from run_methods import (
    load_rds,
    process_data_single_view,
    train_model_single_view,
    train_model_locally_single_view,
    evaluate_fitted_model_single_view,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DATA_ROOT   = os.path.expanduser("~/multiomic_integration/sim/data/single_view_withoutcome")
METRIC_ROOT = os.path.expanduser("~/multiomic_integration/sim/results/matrixdecomp/metrics")
Path(METRIC_ROOT).mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Data grid
# ---------------------------------------------------------------------------
DATA_FILES = [
    ("k.5", "factor_data_n500p100_snr2.2_sparse0.25")#,
    # ("k.5", "factor_data_n500p500_snr2.2_sparse0.25"),
]

# ---------------------------------------------------------------------------
# Model config grid
# ---------------------------------------------------------------------------
dense_array   = [True, False]
k_delta_array = [0, 5, 10]

# ---------------------------------------------------------------------------
# Training / optimizer grid
# ---------------------------------------------------------------------------
lr_array        = [0.05, 0.01, 0.005]
betas_array     = [(0.9, 0.999), (0.95, 0.999)]
lr_step_array   = [10, 20]
lr_decay_array  = [0.9, 0.5]
particle_array  = [1, 2]
minibatch_array = [16, 32]
min_epoch_array = [100, 200]
max_epoch_array = [500]

train_grid_names = (
    "initial_lr", "betas", "lr_step_size", "lr_decay_factor",
    "num_particles", "minibatch_size", "min_epochs", "max_epochs",
)

# ---------------------------------------------------------------------------
# Other settings
# ---------------------------------------------------------------------------
TRAINING_SIZE       = 0.8
RANDOM_SEED         = 123
N_POSTERIOR_SAMPLES = 300

```


```{python}
# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


train_grid = list(itertools.product(
    lr_array, betas_array, lr_step_array, lr_decay_array,
    particle_array, minibatch_array, min_epoch_array, max_epoch_array,
))

all_metrics = pd.DataFrame()
```


```{python}
for k_subdir, filename_stem in DATA_FILES:
    rds_path = os.path.join(DATA_ROOT, k_subdir, filename_stem + ".rds")
    print(f"\n=== Loading: {rds_path} ===")

    sim_data = load_rds(rds_path)
    train_subset, test_subset, data_package = process_data_single_view(
        sim_data, TRAINING_SIZE, RANDOM_SEED
    )
    k_true = data_package["k"]
    break
```


```{python}
# for dense, k_delta in itertools.product(dense_array, k_delta_array):
dense = dense_array[0]
k_delta = k_delta_array[0]
k_fit      = k_true + k_delta
model_config = {"k": k_fit, "dense": dense}
model_tag  = f"dense{dense}_kdelta{k_delta}"

train_params = train_grid[0]
```


```{python}
# for train_params in train_grid:
train_config = dict(zip(train_grid_names, train_params))
train_tag    = ".".join(f"{k}{v}" for k, v in train_config.items())

out_stem = os.path.join(
    METRIC_ROOT, f"{filename_stem}_{model_tag}_{train_tag}"
)
if os.path.isfile(out_stem + ".csv"):
    print(f"  Already done, skipping: {model_tag} | {train_tag}")

print(f"  {model_tag} | lr={train_config['initial_lr']} "
        f"bs={train_config['minibatch_size']} "
        f"step={train_config['lr_step_size']} "
        f"decay={train_config['lr_decay_factor']}")
```


```{python}
pyro.clear_param_store()

# try:
factor_model, train_handler, global_runtime = train_model_single_view(
    model_config, train_config, train_subset
)
```


```{python}
test_handler, local_runtime = train_model_locally_single_view(
    factor_model, train_config, test_subset
)
```


```{python}
metrics = evaluate_fitted_model_single_view(
    train_handler, test_handler, data_package, N_POSTERIOR_SAMPLES
)
```

```{python}
metrics
```


```{python}
metrics = metrics.assign(
    data_file      = filename_stem,
    k_subdir       = k_subdir,
    k_true         = k_true,
    k_fit          = k_fit,
    k_delta        = k_delta,
    dense          = dense,
    global_epochs  = factor_model.total_epochs,
    local_epochs   = factor_model.local_epochs,
    global_runtime = global_runtime,
    local_runtime  = local_runtime#,
    # **train_config,
)
```

```{python}
train_config['betas'] = str(train_config['betas'])
metrics.assign(**train_config)
```

```{python}
metrics.to_csv(out_stem + ".csv", index=False)
all_metrics = pd.concat([all_metrics, metrics], ignore_index=True)

# except Exception as e:
#     print(f"    FAILED: {e}")
#     continue

```

```{python}

```

```{python}
concat_path = os.path.join(METRIC_ROOT, "all_metrics_concat.csv")
all_metrics.to_csv(concat_path, index=False)
print(f"\nDone. Combined metrics written to {concat_path}")

```


```{python}

```
