

class Sites:
    """For sparse model only"""
    delta_gamma_l_k = "delta_gamma_l{l}_k{m}"
    rho_gamma_l = "rho_gamma_l{l}"
    sigma2_gamma_l = "sigma2_gamma_l{l}" # for dense model
    Gamma_l = "Gamma_l{l}"
    delta_lambda_l_k = "delta_lambda_l{l}_k{m}"
    delta_lambda_l = "delta_lambda_l{l}"
    rho_lambda_l = 'rho_lambda_l{l}'
    sigma2_lambda_l = "sigma2_lambda_l{l}" # for dense model
    Lambda_l = "Lambda_l{l}"
    psi_l = "psi_l{l}"
    sigma2_beta = "sigma2_beta"
    beta = "beta"
    sigma2_y = "sigma2_y"
    weibull_concentration = "weibull_concentration"
    Z = "Z"
    Phi_l = "Phi_l{l}"
    joint_structure_l = "joint_structure_l{l}"
    view_structure_l = "view_structure_l{l}"
    X_l = "X_l{l}"
    outcome_structure = "outcome_structure"
    y = "y"
    censored = "censored"
    Z_pred = "Z_pred"
    Phi_l_pred = "Phi_l{l}_pred"
    joint_structure_l_pred = "joint_structure_l{l}_pred"
    view_structure_l_pred = "view_structure_l{l}_pred"
    X_l_pred = "X_l{l}_pred"
    outcome_structure_pred = "outcome_structure_pred"
    y_pred = "y_pred"

   
class Params:
    """For sparse model"""
    a_delta_gamma_l_k = "a_delta_gamma_l{l}_k{m}"
    b_delta_gamma_l_k = "b_delta_gamma_l{l}_k{m}"
    a_rho_gamma_l = "a_rho_gamma_l{l}"
    b_rho_gamma_l = "b_rho_gamma_l{l}"
    a_sigma_gamma_l = "a_sigma_gamma_l{l}" # for dense guide
    b_sigma_gamma_l = "b_sigma_gamma_l{l}" # for dense guide
    loc_Gamma_l = "loc_Gamma_l{l}"
    scale_Gamma_l = "scale_Gamma_l{l}"
    a_delta_lambda_l_k = "a_delta_lambda_l{l}_k{m}"
    b_delta_lambda_l_k = "b_delta_lambda_l{l}_k{m}"
    a_delta_lambda_l = "a_delta_lambda_l{l}"
    b_delta_lambda_l = "b_delta_lambda_l{l}"
    a_rho_lambda_l = "a_rho_lambda_l{l}"
    b_rho_lambda_l = "b_rho_lambda_l{l}"
    a_sigma_lambda_l = "a_sigma_lambda_l{l}" # for dense guide
    b_sigma_lambda_l = "b_sigma_lambda_l{l}" # for dense guide
    loc_Lambda_l = "loc_Lambda_l{l}"
    scale_Lambda_l = "scale_Lambda_l{l}"
    a_psi_l = "a_psi_l{l}"
    b_psi_l = "b_psi_l{l}"
    a_sigma_beta = "a_sigma_beta"
    b_sigma_beta = "b_sigma_beta"
    loc_beta = "loc_beta"
    scale_beta = "scale_beta"
    a_sigma_y = "a_sigma_y"
    b_sigma_y = "b_sigma_y"
    a_weibull_concentration = "a_weibull_concentration"
    b_weibull_concentration = "b_weibull_concentration"
    loc_Z = "loc_Z"
    scale_Z = "scale_Z"
    loc_Phi_l = "loc_Phi_l{l}"
    scale_Phi_l = "scale_Phi_l{l}"
    loc_Z_pred = "loc_Z_pred"
    scale_Z_pred = "scale_Z_pred"
    loc_Phi_l_pred = "loc_Phi_l{l}_pred"
    scale_Phi_l_pred = "scale_Phi_l{l}_pred"