"""
Hyperparameter tuning script for MatrixDecomp (single-view supervised factor model).

Data layout expected (generated by generate_data.Rmd, "Multiple reps - single view"):
    sim/data/single_view/k.<K>/train/<condition>/sim_data_rep<i>.rds
    sim/data/single_view/k.<K>/test/<condition>/sim_data_rep<i>.rds   (TRAINING_SPLIT=False)

Each RDS file contains keys:
    X_l (list of 1 matrix), y, Z, Lambda_l (list of 1 matrix), K, p_l, beta

Outputs per (condition, rep, model_config, train_config):
    sim/results/matrixdecomp/metrics/<condition>_k<K>_rep<i>_<model_tag>_<train_tag>.csv
    sim/results/matrixdecomp/metrics/all_metrics_concat.csv
"""

import os
import sys
import itertools
from pathlib import Path

import pandas as pd
import pyro

sys.path.insert(1, "/Users/jonathanhori/multiomic_integration/python")

from run_methods import (
    load_rds,
    process_data_single_view,
    train_model_single_view,
    train_model_locally_single_view,
    evaluate_fitted_model_single_view,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DATA_ROOT   = os.path.expanduser("~/multiomic_integration/sim/data/single_view")
METRIC_ROOT = os.path.expanduser("~/multiomic_integration/sim/results/matrixdecomp/metrics")
Path(METRIC_ROOT).mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Mode: train/test split vs. separate files
# ---------------------------------------------------------------------------
TRAINING_SPLIT = False   # True => random split of training file
                        # False => load separate test files from test/ subdir
TRAINING_SIZE  = 0.8
RANDOM_SEED    = 123

# ---------------------------------------------------------------------------
# Data grid (must match what was generated in generate_data.Rmd)
# ---------------------------------------------------------------------------
n_array          = [100]
p_array          = [100, 500]
K_array          = [5] #, 10]
snr_x_array      = [2] #[1, 2]
snr_y_array      = [2] #[1, 2]
sparsity_array   = [0.25]
reps             = 10

COND_DIR_BASE = "n{}p{}_snr{}.{}_sparse{}"  # condition subdir template
REP_FILE_BASE = "sim_data_rep{}"             # replicate stem (without .rds)

# ---------------------------------------------------------------------------
# Model config grid
# ---------------------------------------------------------------------------
dense_array   = [False]
k_delta_array = [5] #[0, 5]

# ---------------------------------------------------------------------------
# Training / optimizer grid
# ---------------------------------------------------------------------------
# First set of parameters
# lr_array        = [0.05, 0.01, 0.005]
# betas_array     = [(0.9, 0.999), (0.95, 0.999)]
# lr_step_array   = [10, 20]
# lr_decay_array  = [0.9, 0.5]
# particle_array  = [1, 2]
# minibatch_array = [16, 32]
# min_epoch_array = [100, 200]
# max_epoch_array = [500]

# Second set of parameters - based on performance in first set
lr_array        = [0.1, 0.15, 0.2]
betas_array     = [(0.9, 0.999), (0.95, 0.999)]
lr_step_array   = [10, 20]
lr_decay_array  = [0.9, 0.5]
particle_array  = [2]
minibatch_array = [16, 32]
min_epoch_array = [200]
max_epoch_array = [500]

train_grid_names = (
    "initial_lr", "betas", "lr_step_size", "lr_decay_factor",
    "num_particles", "minibatch_size", "min_epochs", "max_epochs",
)

N_POSTERIOR_SAMPLES = 200


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _load_rep_files(cond_path, n_reps):
    """Load up to n_reps RDS files from cond_path; return dict stem -> tensor dict."""
    fnames = sorted(f for f in os.listdir(cond_path) if f.endswith(".rds"))[:n_reps]
    return {Path(f).stem: load_rds(os.path.join(cond_path, f)) for f in fnames}


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------
if __name__ == "__main__":

    train_grid = list(itertools.product(
        lr_array, betas_array, lr_step_array, lr_decay_array,
        particle_array, minibatch_array, min_epoch_array, max_epoch_array,
    ))

    data_grid = itertools.product(
        n_array, p_array, K_array, snr_x_array, snr_y_array, sparsity_array
    )

    all_metrics = pd.DataFrame()

    for n, p, K, snr_x, snr_y, sparsity in data_grid:
        # Load data and process
        cond_dir = COND_DIR_BASE.format(n, p, snr_x, snr_y, sparsity)
        k_dir    = f"k.{K}"

        cond_train_path = os.path.expanduser(
            os.path.join(DATA_ROOT, k_dir, "train", cond_dir)
        )
        if not os.path.isdir(cond_train_path):
            print(f"Skipping (no data): {cond_train_path}")
            continue

        print(f"\n=== {cond_dir} | {k_dir} ===")
        train_files = _load_rep_files(cond_train_path, reps)

        if not TRAINING_SPLIT:
            cond_test_path = os.path.expanduser(
                os.path.join(DATA_ROOT, k_dir, "test", cond_dir)
            )
            test_files = _load_rep_files(cond_test_path, reps) \
                if os.path.isdir(cond_test_path) else {}
        else:
            test_files = {}
        
        # Iterating over model configurations
        for dense, k_delta in itertools.product(dense_array, k_delta_array):
            k_fit        = K + k_delta
            model_config = {"k": k_fit, "dense": dense}
            model_tag    = f"dense{dense}_kdelta{k_delta}"
            
            # Iterating over optimizer grid
            for train_params in train_grid:
                train_config = dict(zip(train_grid_names, train_params))
                train_tag    = ".".join(f"{k}{v}" for k, v in train_config.items())

                pyro.clear_param_store()

                for rep in range(1, len(train_files) + 1):
                    rep_stem = REP_FILE_BASE.format(rep)

                    out_stem = os.path.join(
                        METRIC_ROOT,
                        f"{cond_dir}_{k_dir}_rep{rep}_{model_tag}_{train_tag}",
                    )
                    if os.path.isfile(out_stem + ".csv"):
                        print(f"  Already done: rep{rep} {model_tag}")
                        continue

                    sim_data = train_files.get(rep_stem)
                    if sim_data is None:
                        print(f"  Missing rep {rep}, skipping")
                        continue
                    sim_data_test = test_files.get(rep_stem) if not TRAINING_SPLIT else None

                    try:
                        train_subset, test_subset, data_package = process_data_single_view(
                            sim_data,
                            training_size=TRAINING_SIZE,
                            seed=RANDOM_SEED,
                            training_split=TRAINING_SPLIT,
                            sim_data_test=sim_data_test,
                        )

                        print(f"  rep{rep} | {model_tag} | "
                              f"lr={train_config['initial_lr']} "
                              f"bs={train_config['minibatch_size']} "
                              f"step={train_config['lr_step_size']} "
                              f"decay={train_config['lr_decay_factor']}")

                        factor_model, train_handler, global_runtime = train_model_single_view(
                            model_config, train_config, train_subset
                        )
                        test_handler, local_runtime = train_model_locally_single_view(
                            factor_model, train_config, test_subset
                        )
                        metrics = evaluate_fitted_model_single_view(
                            train_handler, test_handler, data_package, N_POSTERIOR_SAMPLES
                        )

                        tc = dict(train_config)
                        tc["betas"] = str(tc["betas"])
                        metrics = metrics.assign(
                            n=n, p=p, K=K, snr_x=snr_x, snr_y=snr_y,
                            sparsity=sparsity, rep=rep,
                            k_fit=k_fit, k_delta=k_delta, dense=dense,
                            global_epochs=factor_model.total_epochs,
                            local_epochs=factor_model.local_epochs,
                            global_runtime=global_runtime,
                            local_runtime=local_runtime,
                            **tc,
                        )

                        metrics.to_csv(out_stem + ".csv", index=False)
                        all_metrics = pd.concat([all_metrics, metrics], ignore_index=True)

                    except Exception as e:
                        print(f"    FAILED (rep {rep}): {e}")
                        continue

    concat_path = os.path.join(METRIC_ROOT, "all_metrics_concat.csv")
    all_metrics.to_csv(concat_path, index=False)
    print(f"\nDone. Combined metrics written to {concat_path}")
